"""Canonical public metadata-container API surface.

This package re-exports metadata-container contracts only. Concrete
implementations live under ``LiuXin_alpha.metadata.containers``.
"""

from __future__ import annotations

from LiuXin_alpha.metadata.api.metadata_container_api.storage_containers_api import (
    AssetReplicaIdentityAPI,
    AssetReplicaMetadataAPI,
    DigitalAssetIdentityAPI,
    DigitalAssetMetadataAPI,
)
from LiuXin_alpha.metadata.api.metadata_container_api.wemi_containers_api import (
    AgentIdentityAPI,
    AgentProfileAPI,
    ExpressionIdentityAPI,
    ExpressionIdentityPropertiesAPI,
    ExpressionMetadataAPI,
    ExpressionRelationLink,
    ExpressionRelationTarget,
    ItemIdentityAPI,
    ItemIdentityPropertiesAPI,
    ItemMetadataAPI,
    ItemRelationLink,
    ItemRelationTarget,
    MetadataRecord,
    MetadataScalar,
    MetadataValue,
    MutableMetadataRecord,
    RelationTarget,
    SupportsMetadataMapping,
    SupportsRowMapping,
    ManifestationIdentityAPI,
    ManifestationIdentityPropertiesAPI,
    ManifestationMetadataAPI,
    ManifestationRelationLink,
    ManifestationRelationTarget,
    WorkIdentityAPI,
    WorkIdentityPropertiesAPI,
    WorkMetadataAPI,
    WorkRelationLink,
    WorkRelationTarget,
)

__all__ = [
    "AssetReplicaIdentityAPI",
    "AssetReplicaMetadataAPI",
    "DigitalAssetIdentityAPI",
    "DigitalAssetMetadataAPI",
    "AgentIdentityAPI",
    "AgentProfileAPI",
    "ExpressionIdentityAPI",
    "ExpressionIdentityPropertiesAPI",
    "ExpressionMetadataAPI",
    "ExpressionRelationLink",
    "ExpressionRelationTarget",
    "ItemIdentityAPI",
    "ItemIdentityPropertiesAPI",
    "ItemMetadataAPI",
    "ItemRelationLink",
    "ItemRelationTarget",
    "MetadataRecord",
    "MetadataScalar",
    "MetadataValue",
    "MutableMetadataRecord",
    "RelationTarget",
    "SupportsMetadataMapping",
    "SupportsRowMapping",
    "ManifestationIdentityAPI",
    "ManifestationIdentityPropertiesAPI",
    "ManifestationMetadataAPI",
    "ManifestationRelationLink",
    "ManifestationRelationTarget",
    "WorkIdentityAPI",
    "WorkIdentityPropertiesAPI",
    "WorkMetadataAPI",
    "WorkRelationLink",
    "WorkRelationTarget",
]
