"""Canonical public metadata-container API surface.

This package re-exports metadata-container contracts only. Concrete
implementations live under ``LiuXin_alpha.metadata.containers``.
"""

from __future__ import annotations

from LiuXin_alpha.metadata.api.metadata_container_api.wemi_containers_api import (
    AgentIdentityAPI,
    AgentProfileAPI,
    ExpressionIdentityAPI,
    ExpressionIdentityPropertiesAPI,
    ExpressionMetadataAPI,
    ExpressionRelationEdge,
    ExpressionRelationLink,
    ExpressionRelationTarget,
    ItemIdentityAPI,
    ItemIdentityPropertiesAPI,
    ItemMetadataAPI,
    ItemRelationEdge,
    ItemRelationLink,
    ItemRelationTarget,
    ManyManyRelationEdgeAPI,
    ManyOneRelationEdgeAPI,
    MetadataRecord,
    MetadataScalar,
    MetadataValue,
    MutableMetadataRecord,
    OneManyRelationEdgeAPI,
    OneOneRelationEdgeAPI,
    RelationCardinality,
    RelationCardinalityValue,
    RelationEdge,
    RelationEdgeAPI,
    RelationEdgeID,
    RelationEdgeSource,
    RelationEdgeType,
    RelationTarget,
    SupportsMetadataMapping,
    SupportsRowMapping,
    ManifestationIdentityAPI,
    ManifestationIdentityPropertiesAPI,
    ManifestationMetadataAPI,
    ManifestationRelationEdge,
    ManifestationRelationLink,
    ManifestationRelationTarget,
    WorkIdentityAPI,
    WorkIdentityPropertiesAPI,
    WorkMetadataAPI,
    WorkRelationEdge,
    WorkRelationLink,
    WorkRelationTarget,
    normalize_relation_cardinality,
    validate_relation_edge_cardinality,
)

__all__ = [
    "AgentIdentityAPI",
    "AgentProfileAPI",
    "ExpressionIdentityAPI",
    "ExpressionIdentityPropertiesAPI",
    "ExpressionMetadataAPI",
    "ExpressionRelationEdge",
    "ExpressionRelationLink",
    "ExpressionRelationTarget",
    "ItemIdentityAPI",
    "ItemIdentityPropertiesAPI",
    "ItemMetadataAPI",
    "ItemRelationEdge",
    "ItemRelationLink",
    "ItemRelationTarget",
    "ManyManyRelationEdgeAPI",
    "ManyOneRelationEdgeAPI",
    "MetadataRecord",
    "MetadataScalar",
    "MetadataValue",
    "MutableMetadataRecord",
    "OneManyRelationEdgeAPI",
    "OneOneRelationEdgeAPI",
    "RelationCardinality",
    "RelationCardinalityValue",
    "RelationEdge",
    "RelationEdgeAPI",
    "RelationEdgeID",
    "RelationEdgeSource",
    "RelationEdgeType",
    "RelationTarget",
    "SupportsMetadataMapping",
    "SupportsRowMapping",
    "ManifestationIdentityAPI",
    "ManifestationIdentityPropertiesAPI",
    "ManifestationMetadataAPI",
    "ManifestationRelationEdge",
    "ManifestationRelationLink",
    "ManifestationRelationTarget",
    "WorkIdentityAPI",
    "WorkIdentityPropertiesAPI",
    "WorkMetadataAPI",
    "WorkRelationEdge",
    "WorkRelationLink",
    "WorkRelationTarget",
    "normalize_relation_cardinality",
    "validate_relation_edge_cardinality",
]
