"""Public API contracts for the catalog layer."""

from .catalog import CatalogAPI
from .common import (
    CatalogError,
    CatalogAmbiguousMatchError,
    CatalogMatchConflictError,
    CatalogMatchError,
    CatalogMutationError,
    CatalogNotFoundError,
    EntityId,
    IdentifierCandidate,
    MatchDecision,
    MatchEvidence,
    MatchEvidenceKind,
    MatchResult,
    MetadataCandidate,
    RowInput,
    RowMapping,
    WemiBundle,
    WemiLevel,
)
from .field_metadata_api import (
    CalibreFieldMetadataAPI,
    FieldMetadataAPI,
    FieldMetadataDataType,
    FieldMetadataDeserializerAPI,
    FieldMetadataDisplay,
    FieldMetadataEntry,
    FieldMetadataGetterAPI,
    FieldMetadataKind,
    FieldMetadataMultiplicity,
    FieldMetadataRecord,
    FieldMetadataSearchTarget,
    FieldRecordIndexMap,
    GroupedSearchTerms,
    KnownFieldMetadataDataType,
    SerializedFieldMetadataState,
)
from .metadata_tools_api import (
    AddAPI,
    ApplyAPI,
    BackendGetterAPI,
    CatalogMetadataToolsAPI,
    EnsureAPI,
    FingerprintToolsAPI,
    IntralinkerAPI,
)
from .mutations_api import CatalogMutationsAPI

__all__ = [
    "AddAPI",
    "ApplyAPI",
    "BackendGetterAPI",
    "CalibreFieldMetadataAPI",
    "CatalogAPI",
    "CatalogAmbiguousMatchError",
    "CatalogError",
    "CatalogMatchConflictError",
    "CatalogMatchError",
    "CatalogMetadataToolsAPI",
    "CatalogMutationError",
    "CatalogMutationsAPI",
    "CatalogNotFoundError",
    "EnsureAPI",
    "EntityId",
    "FieldMetadataAPI",
    "FieldMetadataDataType",
    "FieldMetadataDeserializerAPI",
    "FieldMetadataDisplay",
    "FieldMetadataEntry",
    "FieldMetadataGetterAPI",
    "FieldMetadataKind",
    "FieldMetadataMultiplicity",
    "FieldMetadataRecord",
    "FieldMetadataSearchTarget",
    "FieldRecordIndexMap",
    "FingerprintToolsAPI",
    "GroupedSearchTerms",
    "IdentifierCandidate",
    "IntralinkerAPI",
    "KnownFieldMetadataDataType",
    "MatchDecision",
    "MatchEvidence",
    "MatchEvidenceKind",
    "MatchResult",
    "MetadataCandidate",
    "RowInput",
    "RowMapping",
    "SerializedFieldMetadataState",
    "WemiBundle",
    "WemiLevel",
]
