
"""
Text manipulation tools.
"""

from typing import Optional, Union

import re

from LiuXin_alpha.constants import preferred_encoding


def isbytestring(obj : Union[bytes, str]) -> bool:
    return isinstance(obj, (str, bytes))


def url_slash_cleaner(url: str) -> str:
    """
    Removes redundant /'s from urls.
    """
    return re.sub(r"(?<!:)/{2,}", "/", url)



def as_unicode(obj, enc: Optional[None] = None):

    from LiuXin_alpha.constants import force_unicode
    from LiuXin_alpha.utils.libraries.calibre_polyglot.builtins import native_string_type

    if enc is None:
        from LiuXin_alpha.constants import preferred_encoding
        enc = preferred_encoding

    if not isbytestring(obj):
        try:
            obj = str(obj)
        except Exception:
            try:
                obj = native_string_type(obj)
            except Exception:
                obj = repr(obj)

    return force_unicode(obj, enc=enc)


def human_readable(size, sep=" "):
    """Convert a size in bytes into a human-readable form."""
    divisor, suffix = 1, "B"
    for i, candidate in enumerate(("B", "KB", "MB", "GB", "TB", "PB", "EB")):
        if size < (1 << ((i + 1) * 10)):
            divisor, suffix = (1 << (i * 10)), candidate
            break
    size = str(float(size) / divisor)
    if size.find(".") > -1:
        size = size[: size.find(".") + 2]
    if size.endswith(".0"):
        size = size[:-2]
    return size + sep + suffix


def remove_bracketed_text(src, brackets: Optional[dict[str, str]] = None) -> str:
    """
    Remove bracketed text from a given string.

    :param src:
    :param brackets: Optional dict keyed with the left bracket, valued with the right.
                     Defaults to {"(": ")", "[": "]", "{": "}"}
    :return:
    """
    brackets = brackets if brackets is not None else {"(": ")", "[": "]", "{": "}"}

    from collections import Counter

    counts = Counter()
    buf = []
    src = str(src)
    rmap = dict([(v, k) for k, v in brackets.items()])
    for char in src:
        if char in brackets:
            counts[char] += 1
        elif char in rmap:
            idx = rmap[char]
            if counts[idx] > 0:
                counts[idx] -= 1
        elif sum(counts.values()) < 1:
            buf.append(char)
    return "".join(buf)


def my_unichr(num):
    from LiuXin_alpha.utils.text.icu import safe_chr
    try:
        return safe_chr(num)
    except (ValueError, OverflowError):
        return "?"


def entity_to_unicode(match, exceptions=[], encoding="cp1252", result_exceptions={}):
    """
    :param match: A match object such that '&'+match.group(1)';' is the entity.

    :param exceptions: A list of entities to not convert (Each entry is the name of the entity, e.g. 'apos' or '#1234'

    :param encoding: The encoding to use to decode numeric entities between 128 and 256.
    If None, the Unicode UCS encoding is used. A common encoding is cp1252.

    :param result_exceptions: A mapping of characters to entities. If the result
    is in result_exceptions, result_exception[result] is returned instead.
    Convenient way to specify exception for things like < or > that can be
    specified by various actual entities.
    """

    def check(ch):
        return result_exceptions.get(ch, ch)

    ent = match.group(1)
    if ent in exceptions:
        return "&" + ent + ";"
    if ent in {"apos", "squot"}:  # squot is generated by some broken CMS software
        return check("'")
    if ent == "hellips":
        ent = "hellip"
    if ent.startswith("#"):
        try:
            if ent[1] in ("x", "X"):
                num = int(ent[2:], 16)
            else:
                num = int(ent[1:])
        except:
            return "&" + ent + ";"
        if encoding is None or num > 255:
            return check(my_unichr(num))
        try:
            return check(bytes(bytearray((num,))).decode(encoding))
        except UnicodeDecodeError:
            return check(my_unichr(num))
    from LiuXin.file_formats.html_entities import html5_entities

    try:
        return check(html5_entities[ent])
    except KeyError:
        pass
    from LiuXin.utils.calibre_utils.calibre_polyglot.html_entities import name2codepoint

    try:
        return check(my_unichr(name2codepoint[ent]))
    except KeyError:
        return "&" + ent + ";"