

"""
Normalize XML text, entities and namespace-aware element operations.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise xml utils through a consuming regression::

        python -m pytest -q tests/utils/text/test_text_core.py
"""
import re

from functools import partial


def my_unichr(num):
    """
    Perform the my unichr utility operation under explicit compatibility rules.

    Example:
        Exercise my unichr through a consuming regression::

            python -m pytest -q tests/utils/text/test_text_core.py


    :param num: Value supplied for num under the utility contract.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    from LiuXin_alpha.utils.text.icu import safe_chr
    try:
        return safe_chr(num)
    except (ValueError, OverflowError):
        return "?"

def entity_to_unicode(match, exceptions=[], encoding="cp1252", result_exceptions={}):
    """
    Perform the entity to unicode utility operation under explicit compatibility rules.

    Example:
        Exercise entity to unicode through a consuming regression::

            python -m pytest -q tests/utils/text/test_text_core.py


    :param match: Value supplied for match under the utility contract.
    :param exceptions: Value supplied for exceptions under the utility contract.
    :param encoding: Value supplied for encoding under the utility contract.
    :param result_exceptions: Value supplied for result exceptions under the utility
        contract.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """

    def check(ch):
        """
        Perform the check utility operation under explicit compatibility rules.

        Example:
            Exercise entity to unicode.check through a consuming regression::

                python -m pytest -q tests/utils/text/test_text_core.py


        :param ch: Value supplied for ch under the utility contract.
        :return: The normalized value, metadata record, path, stream result or collection
            described above.
        """
        return result_exceptions.get(ch, ch)

    ent = match.group(1)
    if ent in exceptions:
        return "&" + ent + ";"
    if ent in {"apos", "squot"}:  # squot is generated by some broken CMS software
        return check("'")
    if ent == "hellips":
        ent = "hellip"
    if ent.startswith("#"):
        try:
            if ent[1] in ("x", "X"):
                num = int(ent[2:], 16)
            else:
                num = int(ent[1:])
        except:
            return "&" + ent + ";"
        if encoding is None or num > 255:
            return check(my_unichr(num))
        try:
            return check(bytes(bytearray((num,))).decode(encoding))
        except UnicodeDecodeError:
            return check(my_unichr(num))
    from LiuXin_alpha.file_formats.html_entities import html5_entities

    try:
        return check(html5_entities[ent])
    except KeyError:
        pass
    from LiuXin_alpha.utils.libraries.calibre_polyglot.html_entities import name2codepoint

    try:
        return check(my_unichr(name2codepoint[ent]))
    except KeyError:
        return "&" + ent + ";"



_ent_pat = re.compile(r"&(\S+?);")
xml_entity_to_unicode = partial(
    entity_to_unicode, result_exceptions={'"': "&quot;", "'": "&apos;", "<": "&lt;", ">": "&gt;", "&": "&amp;"}
)


def replace_entities(raw, encoding="cp1252"):
    """
    Perform the replace entities utility operation under explicit compatibility rules.

    Example:
        Exercise replace entities through a consuming regression::

            python -m pytest -q tests/utils/text/test_text_core.py


    :param raw: Value supplied for raw under the utility contract.
    :param encoding: Value supplied for encoding under the utility contract.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return _ent_pat.sub(partial(entity_to_unicode, encoding=encoding), raw)


def xml_replace_entities(raw, encoding="cp1252"):
    """
    Perform the xml replace entities utility operation under explicit compatibility rules.

    Example:
        Exercise xml replace entities through a consuming regression::

            python -m pytest -q tests/utils/text/test_text_core.py


    :param raw: Value supplied for raw under the utility contract.
    :param encoding: Value supplied for encoding under the utility contract.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return _ent_pat.sub(partial(xml_entity_to_unicode, encoding=encoding), raw)


def prepare_string_for_xml(raw, attribute=False):
    """
    Perform the prepare string for xml utility operation under explicit compatibility rules.

    Example:
        Exercise prepare string for xml through a consuming regression::

            python -m pytest -q tests/utils/text/test_text_core.py


    :param raw: Value supplied for raw under the utility contract.
    :param attribute: Value supplied for attribute under the utility contract.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    raw = _ent_pat.sub(entity_to_unicode, raw)
    raw = raw.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    if attribute:
        raw = raw.replace('"', "&quot;").replace("'", "&apos;")
    return raw
