#!/usr/bin/env python
# vim:fileencoding=UTF-8:ts=4:sw=4:sta:et:sts=4:a

"""
Store legacy LiuXin book metadata with Calibre-style writes and value-to-row mappings.

Most collection fields use ordered mappings from values to optional database row
information. Creator roles and identifier schemes have separate top-level stores,
with mixins providing grouped views and conversion. This container keeps legacy
behavior, including asymmetric copy and update rules.

Example:
    Exercise the owning behavior with pytest::

        python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py
"""


from __future__ import division, absolute_import, print_function, annotations

import copy
from typing import Optional, Union

import os
import re
import pprint
from collections import OrderedDict
from copy import deepcopy
from numbers import Number

from LiuXin_alpha.constants import ALLOWED_DOC_TYPES
from LiuXin_alpha.constants import check_image_tuple

# from LiuXin.databases.row_collection import RowCollection
#
# from LiuXin.exceptions import InputIntegrityError
# from LiuXin.exceptions import LogicalError
# from LiuXin.exceptions import DatabaseIntegrityError
#
# from LiuXin.file_formats.chardet import force_encoding
#
from LiuXin_alpha.metadata.utils import check_isbn
# from LiuXin_alpha.metadata import string_to_authors
# from LiuXin_alpha.metadata import authors_to_sort_string
# from LiuXin.metadata.book.base import calibreMetadata
from LiuXin_alpha.metadata.constants import CREATOR_DROP_REGEX_SET, CREATOR_CATEGORIES, CREATOR_TYPES, CREATOR_TYPE_CAT_DIR, EXTERNAL_EBOOK_ID_SCHEMA, EXTERNAL_EBOOK_REKEY_SCHEME
from LiuXin_alpha.metadata.constants import INTERNAL_EBOOK_ID_SCHEMA
from LiuXin_alpha.metadata.constants import INTERNAL_EBOOK_REKEY_SCHEME
from LiuXin_alpha.metadata.constants import METADATA_NULL_VALUES
from LiuXin_alpha.metadata.standardize import standardize_id_name, standardize_creator_category, string_to_authors, standardize_lang, standardize_internal_id_name, standardize_rating_type, standardize_tag

from LiuXin_alpha.utils.localization import trans as _
from LiuXin_alpha.utils.logging import default_log

from LiuXin_alpha.utils.libraries.liuxin_six import six_string_types
from LiuXin_alpha.utils.libraries.liuxin_six import dict_iterkeys as iterkeys
from LiuXin_alpha.utils.libraries.liuxin_six import dict_iteritems as iteritems
from LiuXin_alpha.utils.libraries.liuxin_six import six_unicode

from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.help_methods import BookMetadataHelpMixin


from LiuXin_alpha.errors import InputIntegrityError

from LiuXin_alpha.metadata.metadata_types import CalibreMetadataLike

from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.calibre_identifiers_mixin import IdentifiersMethodsMixin
from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.calibre_creators_mixin import CreatorsMethodsMixin, AutogeneratedCreator
from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.calibre_files_mixin import FileMethodsMixin
from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.calibre_covers_mixin import CoverMethodsMixin
from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.calibre_ratings_mixin import RatingsMethodsMixin
from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.calibre_to_and_from_mixin import ToAndFromCalibreMetadataMixin
from LiuXin_alpha.metadata.containers.calibre_like_book_metadata.factory_methods import FactoryMethodsMixin



__author__ = "Cameron"
__license__ = "GPL v3"
__object_version__ = "3.0.0"



# TODO: user_metadata - need a way to determine which columns of a user defined table should be automatically included.


# Todo: This is a bad class. There shouldn't be this mucn processing in what is, effectively, a data class.
#       That should live elsewhere.


class CalibreLikeLiuXinBookMetaData(
    BookMetadataHelpMixin,
    IdentifiersMethodsMixin,
    CreatorsMethodsMixin,
    FileMethodsMixin,
    CoverMethodsMixin,
    RatingsMethodsMixin,
    ToAndFromCalibreMetadataMixin,
    FactoryMethodsMixin,
    CalibreMetadataLike
):
    """
    Represent a book with normalized field assignment, typed relation collections, and Calibre adapters.

    Assignments generally append to collection fields; nullify clears a supported field
    first. Direct access exposes internal storage while ordinary reads usually copy it,
    except creator and identifier stores. Metadata copying does not copy the cleanup
    registry. This legacy container is distinct from the simpler Calibre book.base
    container.

    Example:
        >>> book = CalibreLikeLiuXinBookMetaData('Example', ['Writer'])
        >>> book.tags = ['history']
        >>> list(book.tags), book.get_authors_copy()
        (['history'], ['Writer'])
    """

    def __init__(self, title: Optional[str] = None, authors: Union[str, list[str], tuple[str, ...]]=None, other=None):
        """
        Create independent defaults, merge other metadata, then apply explicit title and authors.

        A string of authors is first split on ampersands; lists/tuples are assigned entry by
        entry. Those assignments use creator parsing and accumulate with merged authors.
        Dictionaries and unsupported author shapes produce NotImplementedError.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param title: Optional title override; None retains the default or merged title.
        :param authors: Optional author string, list, or tuple.
        :param other: Optional instance of this metadata family to merge before explicit
            values.
        :return: None.
        """
        _data = deepcopy(METADATA_NULL_VALUES)

        # The __setattr__ and __getattr__ methods will be overridden - thus sorting the data somewhere else
        object.__setattr__(self, "_data", _data)

        # Needed to that open files can be made safe
        object.__setattr__(self, "_files_for_cleanup", [])

        # Do this first, so that the title and authors, if provided, will write over it
        if other is not None:
            self.smart_update(other)

        if title is not None:
            self.__setattr__("title", title)

        # Todo: Find string_to_authors - use it here
        if authors is not None:

            # If authors is just a string, tokenized it on the & and add all the authors
            if isinstance(authors, six_string_types):
                author_tokens = authors.split("&")
                for author in author_tokens:
                    self.__setattr__("authors", author)

            elif isinstance(authors, (tuple, list)):
                for author in authors:
                    self.__setattr__("authors", author)

            elif isinstance(authors, (dict, OrderedDict)):
                raise NotImplementedError("Use another method to add row information")

            else:
                raise NotImplementedError("This possibility has not been adequately addressed")

    def setattr(self, key, value):
        """
        Assign a field through the public normalization and collection-dispatch path.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param key: Metadata storage key.
        :param value: Value to store using the operation's field rules.
        :return: None.
        """
        self.__setattr__(key, value)

    @classmethod
    def from_opf(cls, source):
        """
        Read OPF using the shared LiuXin adapter and return this metadata class.

        An adapter result already satisfying cls is returned directly; otherwise the class
        is constructed with other set to that result.

        Example:
            Exercise OPF adapters with pytest::

                python -m pytest -q tests/metadata/test_opf_tools.py


        :param source: OPF path, bytes, XML text, or readable stream; the adapter retains
            caller-owned streams.
        :return: Metadata instance populated from the OPF.
        """
        from LiuXin_alpha.metadata.opf_tools import liuxin_metadata_from_opf

        metadata = liuxin_metadata_from_opf(source)
        if isinstance(metadata, cls):
            return metadata
        return cls(None, None, other=metadata)

    def to_opf_bytes(self, *, default_lang=None):
        """
        Serialize this metadata through the shared OPF adapter.

        Example:
            Exercise OPF adapters with pytest::

                python -m pytest -q tests/metadata/test_opf_tools.py


        :param default_lang: Optional default language forwarded to OPF serialization.
        :return: UTF-8 OPF bytes.
        """
        from LiuXin_alpha.metadata.opf_tools import metadata_to_opf_bytes

        return metadata_to_opf_bytes(self, default_lang=default_lang)

    def write_to_opf(self, path, *, default_lang=None):
        """
        Write this metadata to an OPF file through the shared adapter.

        Example:
            Exercise OPF adapters with pytest::

                python -m pytest -q tests/metadata/test_opf_tools.py


        :param path: Destination OPF path; the shared adapter creates parents and overwrites
            the file.
        :param default_lang: Optional default language forwarded to OPF serialization.
        :return: Destination Path returned by the adapter.
        """
        from LiuXin_alpha.metadata.opf_tools import metadata_to_opf_file

        return metadata_to_opf_file(self, path, default_lang=default_lang)

    def write_to_database(
        self,
        database,
        *,
        fields=None,
        target_level="work",
        item_id=None,
        target_row=None,
        replace=False,
        mark_dirty=True,
    ):
        """
        Persist supported relation fields through LiuXinWEMIMetadataWriter.

        Supply item_id or target_row unless the object has been enriched with database-id
        fields. The writer owns target resolution, validation, and error/skip reporting;
        this facade does not manage a transaction.

        Example:
            Exercise persistence with pytest::

                python -m pytest -q tests/metadata/containers/test_item_metadata_hydrator.py


        :param database: Caller-owned database used by the WEMI writer for persistence; this
            method does not close it.
        :param fields: Optional relation-field iterable; None selects writer defaults.
        :param target_level: WEMI level for the target relations, defaulting to work.
        :param item_id: Optional LiuXin item id used to resolve the write target.
        :param target_row: Optional explicit row or mapping identifying the write target.
        :param replace: Whether to replace selected existing relations.
        :param mark_dirty: Whether the writer should mark changed metadata dirty.
        :return: Metadata write report describing row/link changes, skips, and errors.
        """
        from LiuXin_alpha.metadata.containers.metadata_containers.liuxin_wemi_metadata_writer import (
            LiuXinWEMIMetadataWriter,
        )

        return LiuXinWEMIMetadataWriter(database).write(
            self,
            fields=fields,
            target_level=target_level,
            item_id=item_id,
            target_row=target_row,
            replace=replace,
            mark_dirty=mark_dirty,
        )

    def __setattr__(self, key: str, value):
        """
        Normalize a field name and dispatch its value to the legacy metadata stores.

        Names are lower-cased and trimmed; string values are trimmed. Creator and identifier
        aliases dispatch to their mixins. Collection fields usually accumulate values;
        unknown fields replace an entry in _data. Special grouped/custom fields may reject
        assignment. Series indices support (series, index) pairs or a cached scalar;
        assigning a scalar after one series uses a legacy keys-view indexing path that fails
        on Python 3. Direct storage access can bypass these rules.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param key: Metadata storage key.
        :param value: Value to store using the operation's field rules.
        :return: None.
        """
        _data = object.__getattribute__(self, "_data")
        key = key.lower().strip()
        if isinstance(value, six_string_types):
            value = value.strip()

        # Check that the user isn't trying to set fields which should not be directly set
        if key in ["identifiers", "internal_identifers", "creators"]:
            err_str = "Attribute cannot be directly set - please use the specialized set methods."
            err_str = default_log.log_variables(err_str, "ERROR", ("key", key))
            raise AttributeError(err_str)

        # Dealing with fields that expect a single entry
        if key.lower() in ["comment", "comments"]:
            value = value.strip()
            if value not in _data["comments"]:
                _data["comments"][value] = None
                return
            else:
                return

        if key.lower() == "cover_data":
            if len(value) != 2:
                err_str = "Warning - cover data not of recognized form.\n"
                raise InputIntegrityError(err_str)
            _data["cover_data"][value] = None
            return

        creator_key = standardize_creator_category(key, logging=False)
        if creator_key:
            self._set_creator_from_normed_key(creator_key, value)
            return

        # Creator sort is just a string
        if key.lower() == "creator_sort":
            _data["creator_sort"] = value
            return

        if key.lower() == "custom_fields_keys":
            raise NotImplementedError

        if key.lower() == "custom_fields":
            raise NotImplementedError

        if key.lower() == "doc_type":
            _data["doc_type"] = value
            return

        if key.lower() == "genre" or key.lower() == "genres":
            _data["genre"][value] = None
            return

        if key.lower() == "filename":
            _data["filename"].append(value)
            return

        if key.lower() == "filepath":
            _data["filepath"].append(value)
            return

        if key.lower() == "files":
            _data["files"][value] = None
            return

        identifiers_key = standardize_id_name(key, logging=False)
        if identifiers_key is not None:
            self._set_identifier_from_normed_key(identifiers_key, value)
            return

        if key.lower() == "imprint":
            _data["imprint"][value] = None
            return

        internal_ids_key = standardize_internal_id_name(key, logging=False)
        if internal_ids_key is not None:
            self._set_internal_identifier_from_normed_key(internal_ids_key, value)
            return

        if key.lower() == "language":
            lang_value = standardize_lang(value)
            if lang_value:
                _data["language"] = lang_value
            else:
                # Failed to standardize the language string - just writing it and continuing
                _data["language"] = value
                return

        if key.lower() == "languages":
            if isinstance(value, six_string_types):
                _data["languages"].append(value)
                return
            elif hasattr(value, "__iter__"):
                for val in value:
                    _data["languages"].append(val)
                return
            else:
                raise NotImplementedError("Unrecognized value type - {}".format(type(value)))

        if key.lower() in ["label", "labels"]:
            if isinstance(value, six_string_types):
                label_vals = value.split(";")
                for label_val in label_vals:
                    label_val = label_val.strip()
                    if label_val:
                        _data["labels"][label_val] = None
            elif isinstance(value, (list, set, tuple)):
                for v in value:
                    if v not in (None, ""):
                        _data["labels"][v] = None
            else:
                err_str = "Couldn't parse the given type of value into labels\n"
                err_str += "type(value): {}\n".format(type(value))
                err_str += "value: {}".format(value)
                raise NotImplementedError(err_str)
            return

        if key.lower() == "languages_available":
            lang_value = standardize_lang(value)
            if lang_value not in _data["languages_available"]:
                _data["languages_available"][lang_value] = None
                return
            else:
                return

        if key.lower() == "last_modified":
            _data["last_modified"] = value
            return

        if key.lower() == "metadata_date":
            _data["metadata_date"] = value
            return

        if key.lower() == "metadata_language":
            _data["metadata_language"] = standardize_lang(value)
            return

        if key.lower() in ["note", "notes"]:
            if value not in _data["notes"]:
                _data["notes"][value] = None
                return
            else:
                return

        if key.lower() == "page_count":
            _data["page_count"] = value

        if key.lower() == "pubdate":
            _data["pubdate"] = value
            return

        if key.lower() == "publisher":
            if isinstance(value, six_string_types):
                _data["publisher"][value] = None
            elif isinstance(value, list):
                for pub_name in value:
                    _data["publisher"][pub_name] = None
            return

        if key.lower() == "ratings":
            self._set_ratings_from_value(value)
            return

        if key.lower() == "rights":
            _data["rights"] = value
            return

        if key.lower() == "series":
            _data["series"][value] = None
            # If this was the first series set, and there is a float series index stored as calibre_series_index then
            # assign that series index to this series
            # (this is so you can make a call of md.series_index = something, then md.series = something_else and it'll
            # group the series and the series index properly
            if len(_data["series"]) == 1 and "calibre_series_index" in _data:
                _data["series_index"][value] = _data["calibre_series_index"]
                del _data["calibre_series_index"]
            return

        if key.lower() == "series_index":
            # LiuXin supports the same work being in multiple series at the same time - thus the series the index
            # corresponds to must be specified (by name).
            # series_index thus takes a tuple or a list - the first element being the name of the series and the
            # second element being the series_index
            if isinstance(value, (tuple, list)):
                assert len(value) == 2
                _data["series_index"][value[0]] = value[1]
                return
            elif isinstance(value, (six_string_types, Number)):
                # If there is only one series set then set the series to be that
                if len(_data["series"]) == 1:
                    _data["series_index"][_data["series"].keys()[0]] = value
                else:
                    # Cache for later processing
                    _data["calibre_series_index"] = value
                return

        if key.lower() == "subject":
            if isinstance(value, six_string_types):
                _data["subject"][value] = None
            elif isinstance(value, (list, set, tuple)):
                for v in value:
                    _data["subject"][v] = None
            else:
                raise NotImplementedError
            return

        if key.lower() in ["synopsis", "synopses"]:
            if isinstance(value, six_string_types):
                _data["synopses"][value] = None
            elif hasattr(value, "__iter__"):
                value = deepcopy(value)
                for synopsis in value:
                    _data["synopses"][synopsis] = None
            else:
                raise NotImplementedError
            return

        if key.lower() in ["tag", "tags"]:

            # Split on semi-colon separations
            if isinstance(value, six_string_types):
                tag_vals = value.split(";")
                for tag_val in tag_vals:
                    tag_val = tag_val.strip()
                    _data["tags"][tag_val] = None

            elif isinstance(value, (list, set, tuple)):
                for v in value:
                    _data["tags"][v] = None

            else:
                err_str = "Couldn't parse the given type of value into tags\n"
                err_str += "type(value): {}\n".format(type(value))
                err_str += "value: {}".format(value)
                raise NotImplementedError(err_str)
            return

        if key.lower() == "timestamp":
            _data["timestamp"] = value
            return

        if key.lower() in ["title_sort", "titlesort"]:
            _data["title_sort"] = value
            return

        if key.lower() == "user_metadata":
            raise NotImplementedError

        if key.lower() == "wordcount":
            _data["wordcount"] = value
            return

        # If the method hasn't been specially handled, add the _data anyway
        _data[key] = value
        return

    def get(self, field, default=None):
        """
        Read a field through __getattr__, returning the default only for AttributeError.

        Example:
            >>> CalibreLikeLiuXinBookMetaData('Example').get('missing', 'fallback')
            'fallback'


        :param field: Metadata field name.
        :param default: Fallback used by the implementation for a missing value.
        :return: Resolved value or default; ownership follows __getattr__.
        """
        try:
            return self.__getattr__(field)
        except AttributeError:
            return default

    def get_extra(self, field, default=None):
        """
        Read the whole stored user-metadata entry for a defined field.

        This legacy helper does not extract a #extra# slot. Undefined fields produce
        AttributeError; the default is only used if the indexed read itself raises
        AttributeError.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param field: Metadata field name.
        :param default: Fallback used by the implementation for a missing value.
        :return: Stored user-metadata entry or the narrow fallback; the entry is shared.
        """
        _data = object.__getattribute__(self, "_data")
        if field in iterkeys(_data["user_metadata"]):
            try:
                return _data["user_metadata"][field]
            except AttributeError:
                return default
        raise AttributeError("Metadata object has no attribute named: " + repr(field))

    def direct_get(self, item: str):
        """
        Return an exact internal storage entry without copying or alias normalization.

        A missing key produces AttributeError.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param item: Exact field or column lookup name.
        :return: Stored value, including its mutable references.
        """
        _data = object.__getattribute__(self, "_data")

        if item in _data.keys():
            return _data[item]

        raise AttributeError("Metadata object has no attribute named: " + repr(item))

    def __getattr__(self, item: str):
        """
        Resolve creator/identifier aliases or copy a named metadata value.

        Creator and identifier stores are returned by reference and initialized if missing.
        Comments, title-sort aliases, genre aliases, and ordinary stored fields are
        deep-copied. Unknown attributes are logged and produce AttributeError.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param item: Exact field or column lookup name.
        :return: Live creator/identifier store or deep-copied ordinary value.
        """
        _data = object.__getattribute__(self, "_data")

        creator_item = standardize_creator_category(item)
        if creator_item is not None:
            if creator_item in _data:
                return _data[creator_item]
            else:
                _data[creator_item] = OrderedDict()
                return _data[creator_item]

        external_id_name = standardize_id_name(item)
        if external_id_name is not None:
            if external_id_name in _data:
                return _data[external_id_name]
            else:
                _data[external_id_name] = set()
                return _data[external_id_name]

        internal_id_name = standardize_internal_id_name(item)
        if internal_id_name is not None:
            if internal_id_name in _data:
                return _data[internal_id_name]
            else:
                _data[internal_id_name] = set()
                return _data[internal_id_name]

        # Check to see if the attribute is in the creator types - if it is then return the appropriate entry
        if item in CREATOR_TYPES:
            return _data[CREATOR_TYPE_CAT_DIR[item]]

        # Return the best guess if they're asking for comment
        if item in ["comment", "comments"]:
            return deepcopy(_data["comments"])

        # Probably want the title sort
        if item in ["titlesort", "title_sort"]:
            return deepcopy(_data["title_sort"])

        if item in ["genre", "genres"]:
            return deepcopy(_data["genre"])

        if item in _data.keys():
            current_val = _data[item]
            return deepcopy(current_val)

        # The attribute has not been set - attribute error
        err_str = "Unable to recognize attribute in LiuXin Metadata. Returning False.\n"
        err_str = default_log.log_variables(err_str, "INFO", ("item", item))
        raise AttributeError(err_str)

    def __getitem__(self, item):
        """
        Read an exact key directly from internal storage.

        Unknown keys produce KeyError with a metadata-specific message; mutable results
        remain shared.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param item: Exact field or column lookup name.
        :return: Stored value without copying.
        """
        try:
            _data = object.__getattribute__(self, "_data")
            return _data[item]
        except KeyError as e:
            raise KeyError("MetaData object has no attribute name: " + repr(item)) from e

    def nullify(self, field: str) -> None:
        """
        Reset grouped creator/identifier stores or a known field to its default.

        Group names are trimmed and lower-cased; ordinary field reset uses the original
        exact spelling and requires a METADATA_NULL_VALUES entry. Unknown or nondefault
        custom fields produce KeyError.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param field: Metadata field name.
        :return: None.
        """
        field_key = field.lower().strip()
        _data = object.__getattribute__(self, "_data")

        if field_key.lower() == "creators":
            for typ in CREATOR_CATEGORIES:
                try:
                    _data[typ] = OrderedDict()
                except KeyError:
                    pass
            return

        if field_key == "identifiers":
            for typ in EXTERNAL_EBOOK_ID_SCHEMA:
                try:
                    _data[typ] = OrderedDict()
                except KeyError:
                    pass
            return

        if field_key == "internal_identifiers":
            for typ in INTERNAL_EBOOK_ID_SCHEMA:
                try:
                    _data[typ] = OrderedDict()
                except KeyError:
                    pass
            return

        if field in _data:
            _data[field] = deepcopy(METADATA_NULL_VALUES[field])
            return

        raise KeyError("field : '{0}' with field_key: '{1}' not recognized.".format(field, field_key))


    # ----------------------------------------------------------------------------------------------------------------------
    #
    # - SPECIALIZED METHODS TO ADD DATA START HERE

    def direct_add(self, key, value, key_check: bool = True) -> None:
        """
        Replace an internal value without normalization, copying, or merging.

        With key_check enabled, unknown keys are logged and rejected with KeyError.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param key: Metadata storage key.
        :param value: Value to store using the operation's field rules.
        :param key_check: Whether the key must already exist in _data.
        :return: None.
        """
        _data = object.__getattribute__(self, "_data")
        if key_check and key not in _data.keys():
            err_str = "Key not found in _data - consider sources of error"
            err_str = default_log.log_variables(err_str, "ERROR", ("key", key), ("value", value))
            raise KeyError(err_str)
        _data[key] = value

    def set_doc_type(self, doc_type):
        """
        Store a document type after converting to text and checking ALLOWED_DOC_TYPES.

        Unrecognized types produce InputIntegrityError; direct doc_type assignment bypasses
        this check.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param doc_type: Document type value to validate and store.
        :return: None.
        """
        doc_type = six_unicode(doc_type)
        if doc_type not in ALLOWED_DOC_TYPES:
            err_str = "Unable to find doc_type in ALLOWED_DOC_TYPES.\n"
            err_str += "doc_type: " + doc_type + "\n"
            raise InputIntegrityError(err_str)
        self.__setattr__("doc_type", doc_type)


    #
    # ----------------------------------------------------------------------------------------------------------------------
    # ----------------------------------------------------------------------------------------------------------------------
    #
    # - DISPLAY METHODS START HERE
    #
    # ----------------------------------------------------------------------------------------------------------------------

    def __unicode__(self) -> str:
        """
        Pretty-print the raw metadata dictionary for inspection.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Text representation of internal storage.
        """
        _data = object.__getattribute__(self, "_data")
        return pprint.pformat(_data)

    def __str__(self) -> str:
        """
        Return the pretty-printed metadata dictionary via __unicode__.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Unicode string.
        """
        return self.__unicode__()

    def __repr__(self) -> str:
        """
        Return pprint's safe representation of the raw metadata dictionary.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Diagnostic representation string.
        """
        _data = object.__getattribute__(self, "_data")
        return pprint.saferepr(_data)

    def __nonzero__(self) -> bool:
        """
        Implement the legacy truth hook from title, author, comments, or tags.

        Python 3 does not use this method as __bool__.

        Example:
            >>> CalibreLikeLiuXinBookMetaData('Example').__nonzero__()
            True


        :return: True if one of those values is truthy.
        """
        return bool(self.title or self.author or self.comments or self.tags)

    # ------------------------------------------------------------------------------------------------------------------
    #
    # - METHODS TO GET INFORMATION ABOUT THE METADATA OBJECT START HERE
    #
    # ----------------------------------------------------------------------------------------------------------------------

    def __iter__(self):
        """
        Iterate the internal top-level metadata keys without expanding user metadata.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Iterator over stored keys.
        """
        return iterkeys(object.__getattribute__(self, "_data"))

    @staticmethod
    def standard_field_keys():
        """
        Return the names present in the shared null-value template.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Frozenset of standard storage keys.
        """
        return frozenset(iterkeys(METADATA_NULL_VALUES))

    def user_metadata_keys(self):
        """
        Return lookup names from this instance's user_metadata dictionary.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Frozenset of custom metadata keys.
        """
        return frozenset(iterkeys(object.__getattribute__(self, "_data")["user_metadata"]))

    def all_field_keys(self):
        """
        Collect top-level keys plus recognized creator roles and identifier schemes.

        Nested user_metadata keys are not expanded by this implementation.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Frozenset of recognized field names.
        """
        _data = object.__getattribute__(self, "_data")

        top_level_keys = frozenset(iterkeys(_data))
        external_identifier_keys = copy.deepcopy(EXTERNAL_EBOOK_ID_SCHEMA)
        internal_identifier_keys = copy.deepcopy(INTERNAL_EBOOK_ID_SCHEMA)
        creator_keys = frozenset(CREATOR_CATEGORIES)

        return_set = top_level_keys.union(external_identifier_keys)
        return_set = return_set.union(internal_identifier_keys)
        return_set = return_set.union(creator_keys)

        return return_set

    def all_set_fields(self):
        """
        Delegate to the legacy all_non_none_fields selector.

        Despite this method's name, the current selector retains fields for which is_null is
        true.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Dictionary of null/default fields produced by all_non_none_fields.
        """
        return self.all_non_none_fields()

    def all_non_none_fields(self):
        """
        Collect fields for which the legacy is_null predicate returns true.

        The implementation currently selects unset/default fields despite its name;
        populated fields are omitted. Values are obtained through get, with its
        field-specific copy behavior.

        Example:
            >>> book = CalibreLikeLiuXinBookMetaData('Example')
            >>> fields = book.all_non_none_fields()
            >>> 'title' in fields, 'tags' in fields
            (False, True)


        :return: Dictionary mapping null/default field names to their read values.
        """
        set_fields = {}
        all_keys = self.all_field_keys()
        for key in all_keys:
            if self.is_null(key):
                set_fields[key] = self.get(key)

        return set_fields

    def is_null(self, field):
        """
        Treat false, default-valued, missing, or unreadable fields as null.

        Zero counts as null, and lookup exceptions are contained.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param field: Metadata field name.
        :return: Whether the field is considered unset.
        """
        try:
            null_val = METADATA_NULL_VALUES.get(field, None)
            val = getattr(self, field, None)
            return not val or val == null_val
        except Exception:
            # Unknown/missing fields should be treated as unset in compatibility paths.
            return True

    # ----------------------------------------------------------------------------------------------------------------------
    #
    # - COPY AND UPDATE METHODS START HERE
    #
    # ----------------------------------------------------------------------------------------------------------------------

    def dict_add(self, more_metadata):
        """
        Copy only keys absent from this instance using another metadata object's data snapshot.

        Existing keys are left unchanged; this helper does not merge their contents.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param more_metadata: Source exposing get_data with the normal copied-dictionary
            behavior.
        :return: None.
        """
        # Just a case of adding fields together, creating them where there don't exist
        _data = object.__getattribute__(self, "_data")
        new_data = more_metadata.get_data()
        for field in new_data:
            if field not in _data:
                _data[field] = new_data[field]
                continue

    def get_all_attr(self, copy=True):
        """
        Expose the raw metadata dictionary through get_data, optionally copying it.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param copy: Whether to deep-copy internal data.
        :return: Deep copy by default, or the live dictionary.
        """
        return self.get_data(rtn_deepcopy=copy)

    def get_data(self, rtn_deepcopy=True):
        """
        Return the internal metadata dictionary or its deep copy.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param rtn_deepcopy: Whether to return independent copied data.
        :return: Copied storage by default; a live mutable mapping when rtn_deepcopy is
            false.
        """
        _data = object.__getattribute__(self, "_data")
        if rtn_deepcopy:
            return deepcopy(_data)
        else:
            return _data

    def deepcopy_metadata(self):
        """
        Construct the same class with deep-copied data and an empty cleanup registry.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: Independent metadata instance; arbitrary non-data attributes are not
            copied.
        """
        m = type(self)(None, None, None)
        object.__setattr__(m, "_data", deepcopy(object.__getattribute__(self, "_data")))
        return m

    def __deepcopy__(self, memo):
        """
        Copy the metadata data dictionary while honoring the stdlib memo for shared references and cycles.

        Reuse an existing memoized result or register the new same-class instance before
        copying its data. The cleanup registry is recreated empty.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param memo: Mutable id-to-copy dictionary supplied by copy.deepcopy.
        :return: Memoized or newly copied metadata instance.
        """
        existing = memo.get(id(self))
        if existing is not None:
            return existing

        m = type(self)(None, None, None)
        memo[id(self)] = m
        object.__setattr__(m, "_data", deepcopy(object.__getattribute__(self, "_data"), memo))
        return m

    def smart_update(self, other, replace_metadata=False):
        """
        Merge another instance according to each field's default container type.

        Nonstandard fields overwrite existing values. Dictionaries merge or replace;
        meaningful scalar values replace; lists append distinct values, with nonempty
        replacement lists taking precedence. Empty lists do not clear old values. The legacy
        nonreplacement set branch computes a union without assigning it, so that branch
        leaves the target unchanged. Source data is copied before applying changes.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param other: Instance of CalibreLikeLiuXinBookMetaData; enforced by an assertion.
        :param replace_metadata: Whether dictionary/set fields replace and nonempty lists
            start from the source values.
        :return: None.
        """
        assert isinstance(other, CalibreLikeLiuXinBookMetaData)

        # Get the _data from another MetaData object. Filter for null values.
        _data = object.__getattribute__(self, "_data")
        default_data_keys = deepcopy([ky for ky in METADATA_NULL_VALUES.keys()])
        new_data = other.get_all_attr(copy=True)
        new_data_fields = deepcopy([ky for ky in new_data.keys()])

        # Copying over and removing the fields which aren't present in this objects _data
        for field in new_data_fields:
            if field not in default_data_keys:
                _data[field] = deepcopy(new_data[field])
                new_data.pop(field, None)

        # Copying over and replacing the fields which cannot be added to
        new_data_fields = deepcopy([ky for ky in new_data.keys()])
        while len(new_data_fields) > 0:

            field = new_data_fields.pop()
            try:
                base_value = deepcopy(METADATA_NULL_VALUES[field])
            except KeyError as e:
                err_str = "smart_update metadata has failed.\nA field which should have been eliminated hasn't been.\n"
                err_str = default_log.log_exception(
                    err_str,
                    e,
                    "ERROR",
                    ("field", field),
                    ("new_data_fields", new_data_fields),
                )
                raise KeyError(err_str)

            if isinstance(base_value, dict):
                current_values = new_data[field]
                if replace_metadata:
                    _data[field] = current_values
                    continue
                for value in current_values:
                    _data[field][value] = new_data[field][value]

            elif base_value is None:
                if not other.is_null(field):
                    _data[field] = new_data[field]
                    continue

            elif isinstance(base_value, six_string_types):
                if not other.is_null(field):
                    _data[field] = new_data[field]
                    continue

            elif isinstance(base_value, set):
                if replace_metadata:
                    _data[field] = new_data[field]
                    continue
                _data[field].union(new_data[field])
                continue

            elif isinstance(base_value, list):
                values = deepcopy(new_data[field])
                if replace_metadata:
                    if values:
                        _data[field] = values
                for value in values:
                    if value not in _data[field]:
                        _data[field] += [
                            value,
                        ]

            else:
                err_str = "Unable to update given value.\nValue is of unrecognized type.\n"
                err_str = default_log.log_variables(
                    err_str,
                    "ERROR",
                    ("field", field),
                    ("new_data[field]", new_data[field]),
                )
                raise NotImplementedError(err_str)

        assert len(new_data_fields) == 0

    def clean(self):
        """
        Title-case creator names, title, and tags, and normalize an existing isbn10 mapping.

        Rekeying can collapse duplicates, retaining the last mapped row value. Invalid ISBN
        keys can become None. This does not invoke finalize.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: None.
        """
        from LiuXin_alpha.utils.libraries.titlecase import titlecase

        def title_case_rekey(target_dict):
            """
            Build a title-cased ordered mapping while retaining the original mapped values.

            Example:
                Exercise the owning behavior with pytest::

                    python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


            :param target_dict: Creator or tag mapping keyed by text.
            :return: New OrderedDict; collisions keep the last value.
            """
            new_dict = OrderedDict()
            for k, v in iteritems(target_dict):
                new_dict[titlecase(k)] = v
            return new_dict

        def isbn_check_rekey(target_dict):
            """
            Rekey a mapping through check_isbn, retaining row values even for a None key.

            Example:
                Exercise the owning behavior with pytest::

                    python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


            :param target_dict: ISBN-to-row mapping to normalize.
            :return: New OrderedDict with normalized ISBN or None keys.
            """
            new_dict = OrderedDict()
            for k, v in iteritems(target_dict):
                new_dict[check_isbn(k)] = v
            return new_dict

        # Make sure all the creator names are in title case
        _data = object.__getattribute__(self, "_data")
        for creator_type in CREATOR_CATEGORIES:
            _data[creator_type] = title_case_rekey(_data[creator_type])

        # Make sure the title is in title case
        _data["title"] = titlecase(_data["title"])

        _data["tags"] = title_case_rekey(_data["tags"])

        if "isbn10" in _data.keys():
            _data["isbn10"] = isbn_check_rekey(_data["isbn10"])

    # ----------------------------------------------------------------------------------------------------------------------
    #
    # - METHODS TO INTERACT WITH USER METADATA START HERE
    #
    # ----------------------------------------------------------------------------------------------------------------------

    def get_all_user_metadata(self, make_copy):
        """
        Return custom metadata descriptors by reference or as individually deep-copied values.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :param make_copy: True for independent copied metadata; False to expose the stored
            mapping.
        :return: Stored dictionary or new dictionary of deep copies.
        """
        _data = object.__getattribute__(self, "_data")
        user_metadata = _data["user_metadata"]
        if not make_copy:
            return user_metadata
        res = {}
        for k in user_metadata:
            res[k] = deepcopy(user_metadata[k])
        return res

    # ----------------------------------------------------------------------------------------------------------------------
    #
    # - INTERACTION METHODS WITH THE DATABASE START HERE
    #
    # ----------------------------------------------------------------------------------------------------------------------

    # Todo: ONce finalize has been called all the public methods of CHANGING the data should go away
    def finalize(self):
        """
        Resolve cached Calibre title/series values, remove Unknown creators, and normalize tags.

        An index cache without a series cache produces NotImplementedError. Splitting
        semicolon tags drops their row ids; unsplit tags retain ids. Creator deletion occurs
        during key iteration and may fail on Python 3 when Unknown is present. This mutates
        the object without freezing later writes.

        Example:
            >>> book = CalibreLikeLiuXinBookMetaData('Example', ['Writer'])
            >>> book.tags = ['History']
            >>> book.finalize() is book
            True


        :return: This same metadata instance after successful normalization.
        """
        _data = object.__getattribute__(self, "_data")

        # SERIES
        # If metadata has been written from calibre then there should be a calibre_series attribute and a
        # calibre_series_index attribute set. Process these two into the series structure
        # In order to set the series properly in this metadata object both the series name and the series position must
        # be known at the same time (to make sure that the index is being set for the right series).
        # During metadata read this is not always true - the series_index might be found before the series -so
        # storing them both as explicitly calibre things, and then combining them at the end
        # Todo: Make series_name a unique key
        # Todo: Deal with the case where there is a LiuXin AND a calibre series structure
        if "calibre_series" in _data and "calibre_series_index" in _data:

            series_name = _data["calibre_series"]
            series_index = _data["calibre_series_index"]

            _data["series"][series_name] = None
            _data["series_index"][series_name] = series_index

        elif "calibre_series" in _data and "calibre_series_index" not in _data:

            series_name = _data["calibre_series"]
            _data["series"][series_name] = None

        elif "calibre_series" not in _data and "calibre_series_index" in _data:

            err_str = "calibre_series_index was found - but not calibre_series."
            raise NotImplementedError(err_str)
        # ------

        # TITLE
        # If a calibre_title or a calibre_title_sort is present, then prefer the calibre variables over the regular one
        if "calibre_title" in _data:
            _data["title"] = _data["calibre_title"]
            del _data["calibre_title"]

        if "calibre_title_sort" in _data:
            _data["title_sort"] = _data["calibre_title_sort"]
            del _data["calibre_title_sort"]
        # -----

        # CREATORS
        # Filter the creators to remove any Unknowns
        # Todo: Drop unknowns in any language
        # Todo: Standardize language to lang code
        for creator_role in CREATOR_CATEGORIES:
            for key in iterkeys(_data[creator_role]):
                if key.lower() == "unknown":
                    del _data[creator_role][key]

        # TAGS
        # If any tags are found to have a semi-colon in them then splits them down into individual tags
        # If there is a semi-colon in the tags field then the field is split down into individual tags - discarding
        # any id data stored in the OrderedDict's values
        # Todo: Make a central standardize_tag method
        new_tags_dict = OrderedDict()
        old_tags_dict = _data["tags"]
        for tag in old_tags_dict:
            split_tags = tag.split(";")
            if len(split_tags) == 1:
                new_tags_dict[standardize_tag(tag)] = old_tags_dict[tag]
            elif len(split_tags) > 1:
                for new_tag in split_tags:
                    new_tags_dict[standardize_tag(new_tag)] = None
            else:
                raise NotImplementedError("split on a string should never produce a 0 length list")
        _data["tags"] = new_tags_dict

        # Todo: After finalize is called it should be much harder to actually change the metadata object
        # Todo: Detect if title sort has been set and set it if it hasn't automatically

        return self

    def __del__(self):
        """
        Close registered cleanup resources and closeable payloads still stored as files or covers.

        AttributeError from a missing close method is ignored; other close failures are not
        contained here. Handles already consumed to bytes by add_file/add_cover are not
        automatically retained in the cleanup registry.

        Example:
            Exercise the owning behavior with pytest::

                python -m pytest -q tests/metadata/containers/calibre_like_book_metadata/test_metadata_core.py


        :return: None.
        """
        self.close_cleanup_files()

        # -------------------
        # SHUT ALL OPEN FILES
        _data = object.__getattribute__(self, "_data")

        file_tuples = _data["files"].keys()
        for file_tuple in file_tuples:
            try:
                file_tuple[1].close()
            except AttributeError:
                pass

        cover_tuples = _data["cover_data"]
        for cover_tuple in cover_tuples:
            try:
                cover_tuple[1].close()
            except AttributeError:
                pass
        # -------------------






class CalibreLikeLiuXinBookMetaInformation(CalibreLikeLiuXinBookMetaData):
    """
    Provide the historical MetaInformation spelling as a subclass of CalibreLikeLiuXinBookMetaData.

    Initialization, storage, conversion, and cleanup behavior are inherited without
    overrides.

    Example:
        >>> info = CalibreLikeLiuXinBookMetaInformation('Example', ['Writer'])
        >>> isinstance(info, CalibreLikeLiuXinBookMetaData)
        True
    """
    pass
