# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF chart elements.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise chart through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_modernized.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import CHARTNS
from LiuXin_alpha.file_formats.odf.element import Element


# Autogenerated
def Axis(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Axis operation under explicit file-format and conversion rules.

    Example:
        Exercise Axis through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "axis"), **args)


def Categories(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Categories operation under explicit file-format and conversion rules.

    Example:
        Exercise Categories through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "categories"), **args)


def Chart(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Chart operation under explicit file-format and conversion rules.

    Example:
        Exercise Chart through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "chart"), **args)


def DataPoint(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPoint operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPoint through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "data-point"), **args)


def Domain(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Domain operation under explicit file-format and conversion rules.

    Example:
        Exercise Domain through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "domain"), **args)


def ErrorIndicator(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ErrorIndicator operation under explicit file-format and conversion rules.

    Example:
        Exercise ErrorIndicator through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "error-indicator"), **args)


def Floor(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Floor operation under explicit file-format and conversion rules.

    Example:
        Exercise Floor through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "floor"), **args)


def Footer(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Footer operation under explicit file-format and conversion rules.

    Example:
        Exercise Footer through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "footer"), **args)


def Grid(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Grid operation under explicit file-format and conversion rules.

    Example:
        Exercise Grid through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "grid"), **args)


def Legend(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Legend operation under explicit file-format and conversion rules.

    Example:
        Exercise Legend through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "legend"), **args)


def MeanValue(**args: _typing.Any) -> _typing.Any:
    """
    Perform the MeanValue operation under explicit file-format and conversion rules.

    Example:
        Exercise MeanValue through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "mean-value"), **args)


def PlotArea(**args: _typing.Any) -> _typing.Any:
    """
    Perform the PlotArea operation under explicit file-format and conversion rules.

    Example:
        Exercise PlotArea through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "plot-area"), **args)


def RegressionCurve(**args: _typing.Any) -> _typing.Any:
    """
    Perform the RegressionCurve operation under explicit file-format and conversion rules.

    Example:
        Exercise RegressionCurve through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "regression-curve"), **args)


def Series(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Series operation under explicit file-format and conversion rules.

    Example:
        Exercise Series through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "series"), **args)


def StockGainMarker(**args: _typing.Any) -> _typing.Any:
    """
    Perform the StockGainMarker operation under explicit file-format and conversion rules.

    Example:
        Exercise StockGainMarker through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "stock-gain-marker"), **args)


def StockLossMarker(**args: _typing.Any) -> _typing.Any:
    """
    Perform the StockLossMarker operation under explicit file-format and conversion rules.

    Example:
        Exercise StockLossMarker through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "stock-loss-marker"), **args)


def StockRangeLine(**args: _typing.Any) -> _typing.Any:
    """
    Perform the StockRangeLine operation under explicit file-format and conversion rules.

    Example:
        Exercise StockRangeLine through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "stock-range-line"), **args)


def Subtitle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Subtitle operation under explicit file-format and conversion rules.

    Example:
        Exercise Subtitle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "subtitle"), **args)


def SymbolImage(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SymbolImage operation under explicit file-format and conversion rules.

    Example:
        Exercise SymbolImage through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "symbol-image"), **args)


def Title(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Title operation under explicit file-format and conversion rules.

    Example:
        Exercise Title through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "title"), **args)


def Wall(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Wall operation under explicit file-format and conversion rules.

    Example:
        Exercise Wall through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(CHARTNS, "wall"), **args)
