# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF three-dimensional drawing elements.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise dr3d through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_modernized.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import DR3DNS
from LiuXin_alpha.file_formats.odf.draw import StyleRefElement

# Autogenerated
def Cube(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Cube operation under explicit file-format and conversion rules.

    Example:
        Exercise Cube through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DR3DNS, "cube"), **args)


def Extrude(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Extrude operation under explicit file-format and conversion rules.

    Example:
        Exercise Extrude through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DR3DNS, "extrude"), **args)


def Light(Element: _typing.Any) -> _typing.Any:
    """
    Perform the Light operation under explicit file-format and conversion rules.

    Example:
        Exercise Light through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param Element: Value supplied for Element under the utility contract.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DR3DNS, "light"), **args)


def Rotate(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Rotate operation under explicit file-format and conversion rules.

    Example:
        Exercise Rotate through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DR3DNS, "rotate"), **args)


def Scene(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Scene operation under explicit file-format and conversion rules.

    Example:
        Exercise Scene through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DR3DNS, "scene"), **args)


def Sphere(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Sphere operation under explicit file-format and conversion rules.

    Example:
        Exercise Sphere through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DR3DNS, "sphere"), **args)
