# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF drawing, shape and presentation elements.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise draw through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_modernized.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import DRAWNS, STYLENS, PRESENTATIONNS
from LiuXin_alpha.file_formats.odf.element import Element


def StyleRefElement(stylename: _typing.Any = None, classnames: _typing.Any = None, **args: _typing.Any) -> _typing.Any:
    """
    Perform the StyleRefElement operation under explicit file-format and conversion rules.

    Example:
        Exercise StyleRefElement through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param stylename: Value supplied for stylename under the utility contract.
    :param classnames: Value supplied for classnames under the utility contract.
    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    qattrs = {}
    if stylename is not None:
        f = stylename.getAttrNS(STYLENS, "family")
        if f == "graphic":
            qattrs[(DRAWNS, "style-name")] = stylename
        elif f == "presentation":
            qattrs[(PRESENTATIONNS, "style-name")] = stylename
        else:
            raise ValueError("Style's family must be either 'graphic' or 'presentation'")
    if classnames is not None:
        f = classnames[0].getAttrNS(STYLENS, "family")
        if f == "graphic":
            qattrs[(DRAWNS, "class-names")] = classnames
        elif f == "presentation":
            qattrs[(PRESENTATIONNS, "class-names")] = classnames
        else:
            raise ValueError("Style's family must be either 'graphic' or 'presentation'")
    return Element(qattributes=qattrs, **args)


def DrawElement(name: _typing.Any = None, **args: _typing.Any) -> _typing.Any:
    """
    Perform the DrawElement operation under explicit file-format and conversion rules.

    Example:
        Exercise DrawElement through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param name: Field, file, function or resource name addressed by the operation.
    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    e = Element(name=name, **args)
    if "displayname" not in args:
        e.setAttrNS(DRAWNS, "display-name", name)
    return e


# Autogenerated
def A(**args: _typing.Any) -> _typing.Any:
    """
    Perform the A operation under explicit file-format and conversion rules.

    Example:
        Exercise A through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "a"), **args)


def Applet(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Applet operation under explicit file-format and conversion rules.

    Example:
        Exercise Applet through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "applet"), **args)


def AreaCircle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the AreaCircle operation under explicit file-format and conversion rules.

    Example:
        Exercise AreaCircle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "area-circle"), **args)


def AreaPolygon(**args: _typing.Any) -> _typing.Any:
    """
    Perform the AreaPolygon operation under explicit file-format and conversion rules.

    Example:
        Exercise AreaPolygon through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "area-polygon"), **args)


def AreaRectangle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the AreaRectangle operation under explicit file-format and conversion rules.

    Example:
        Exercise AreaRectangle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "area-rectangle"), **args)


def Caption(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Caption operation under explicit file-format and conversion rules.

    Example:
        Exercise Caption through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "caption"), **args)


def Circle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Circle operation under explicit file-format and conversion rules.

    Example:
        Exercise Circle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "circle"), **args)


def Connector(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Connector operation under explicit file-format and conversion rules.

    Example:
        Exercise Connector through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "connector"), **args)


def ContourPath(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ContourPath operation under explicit file-format and conversion rules.

    Example:
        Exercise ContourPath through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "contour-path"), **args)


def ContourPolygon(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ContourPolygon operation under explicit file-format and conversion rules.

    Example:
        Exercise ContourPolygon through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "contour-polygon"), **args)


def Control(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Control operation under explicit file-format and conversion rules.

    Example:
        Exercise Control through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "control"), **args)


def CustomShape(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CustomShape operation under explicit file-format and conversion rules.

    Example:
        Exercise CustomShape through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "custom-shape"), **args)


def Ellipse(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Ellipse operation under explicit file-format and conversion rules.

    Example:
        Exercise Ellipse through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "ellipse"), **args)


def EnhancedGeometry(**args: _typing.Any) -> _typing.Any:
    """
    Perform the EnhancedGeometry operation under explicit file-format and conversion rules.

    Example:
        Exercise EnhancedGeometry through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "enhanced-geometry"), **args)


def Equation(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Equation operation under explicit file-format and conversion rules.

    Example:
        Exercise Equation through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "equation"), **args)


def FillImage(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FillImage operation under explicit file-format and conversion rules.

    Example:
        Exercise FillImage through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return DrawElement(qname=(DRAWNS, "fill-image"), **args)


def FloatingFrame(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FloatingFrame operation under explicit file-format and conversion rules.

    Example:
        Exercise FloatingFrame through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "floating-frame"), **args)


def Frame(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Frame operation under explicit file-format and conversion rules.

    Example:
        Exercise Frame through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "frame"), **args)


def G(**args: _typing.Any) -> _typing.Any:
    """
    Perform the G operation under explicit file-format and conversion rules.

    Example:
        Exercise G through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "g"), **args)


def GluePoint(**args: _typing.Any) -> _typing.Any:
    """
    Perform the GluePoint operation under explicit file-format and conversion rules.

    Example:
        Exercise GluePoint through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "glue-point"), **args)


def Gradient(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Gradient operation under explicit file-format and conversion rules.

    Example:
        Exercise Gradient through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return DrawElement(qname=(DRAWNS, "gradient"), **args)


def Handle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Handle operation under explicit file-format and conversion rules.

    Example:
        Exercise Handle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "handle"), **args)


def Hatch(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Hatch operation under explicit file-format and conversion rules.

    Example:
        Exercise Hatch through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return DrawElement(qname=(DRAWNS, "hatch"), **args)


def Image(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Image operation under explicit file-format and conversion rules.

    Example:
        Exercise Image through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "image"), **args)


def ImageMap(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ImageMap operation under explicit file-format and conversion rules.

    Example:
        Exercise ImageMap through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "image-map"), **args)


def Layer(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Layer operation under explicit file-format and conversion rules.

    Example:
        Exercise Layer through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "layer"), **args)


def LayerSet(**args: _typing.Any) -> _typing.Any:
    """
    Perform the LayerSet operation under explicit file-format and conversion rules.

    Example:
        Exercise LayerSet through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "layer-set"), **args)


def Line(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Line operation under explicit file-format and conversion rules.

    Example:
        Exercise Line through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "line"), **args)


def Marker(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Marker operation under explicit file-format and conversion rules.

    Example:
        Exercise Marker through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return DrawElement(qname=(DRAWNS, "marker"), **args)


def Measure(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Measure operation under explicit file-format and conversion rules.

    Example:
        Exercise Measure through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "measure"), **args)


def Object(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Object operation under explicit file-format and conversion rules.

    Example:
        Exercise Object through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "object"), **args)


def ObjectOle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ObjectOle operation under explicit file-format and conversion rules.

    Example:
        Exercise ObjectOle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "object-ole"), **args)


def Opacity(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Opacity operation under explicit file-format and conversion rules.

    Example:
        Exercise Opacity through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return DrawElement(qname=(DRAWNS, "opacity"), **args)


def Page(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Page operation under explicit file-format and conversion rules.

    Example:
        Exercise Page through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "page"), **args)


def PageThumbnail(**args: _typing.Any) -> _typing.Any:
    """
    Perform the PageThumbnail operation under explicit file-format and conversion rules.

    Example:
        Exercise PageThumbnail through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "page-thumbnail"), **args)


def Param(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Param operation under explicit file-format and conversion rules.

    Example:
        Exercise Param through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "param"), **args)


def Path(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Path operation under explicit file-format and conversion rules.

    Example:
        Exercise Path through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "path"), **args)


def Plugin(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Plugin operation under explicit file-format and conversion rules.

    Example:
        Exercise Plugin through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "plugin"), **args)


def Polygon(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Polygon operation under explicit file-format and conversion rules.

    Example:
        Exercise Polygon through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "polygon"), **args)


def Polyline(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Polyline operation under explicit file-format and conversion rules.

    Example:
        Exercise Polyline through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "polyline"), **args)


def Rect(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Rect operation under explicit file-format and conversion rules.

    Example:
        Exercise Rect through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "rect"), **args)


def RegularPolygon(**args: _typing.Any) -> _typing.Any:
    """
    Perform the RegularPolygon operation under explicit file-format and conversion rules.

    Example:
        Exercise RegularPolygon through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(DRAWNS, "regular-polygon"), **args)


def StrokeDash(**args: _typing.Any) -> _typing.Any:
    """
    Perform the StrokeDash operation under explicit file-format and conversion rules.

    Example:
        Exercise StrokeDash through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return DrawElement(qname=(DRAWNS, "stroke-dash"), **args)


def TextBox(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TextBox operation under explicit file-format and conversion rules.

    Example:
        Exercise TextBox through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(DRAWNS, "text-box"), **args)
