# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF form controls and property elements.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise form through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_modernized.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import FORMNS
from LiuXin_alpha.file_formats.odf.element import Element


# Autogenerated
def Button(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Button operation under explicit file-format and conversion rules.

    Example:
        Exercise Button through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "button"), **args)


def Checkbox(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Checkbox operation under explicit file-format and conversion rules.

    Example:
        Exercise Checkbox through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "checkbox"), **args)


def Column(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Column operation under explicit file-format and conversion rules.

    Example:
        Exercise Column through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "column"), **args)


def Combobox(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Combobox operation under explicit file-format and conversion rules.

    Example:
        Exercise Combobox through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "combobox"), **args)


def ConnectionResource(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ConnectionResource operation under explicit file-format and conversion rules.

    Example:
        Exercise ConnectionResource through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "connection-resource"), **args)


def Date(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Date operation under explicit file-format and conversion rules.

    Example:
        Exercise Date through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "date"), **args)


def File(**args: _typing.Any) -> _typing.Any:
    """
    Perform the File operation under explicit file-format and conversion rules.

    Example:
        Exercise File through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "file"), **args)


def FixedText(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FixedText operation under explicit file-format and conversion rules.

    Example:
        Exercise FixedText through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "fixed-text"), **args)


def Form(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Form operation under explicit file-format and conversion rules.

    Example:
        Exercise Form through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "form"), **args)


def FormattedText(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FormattedText operation under explicit file-format and conversion rules.

    Example:
        Exercise FormattedText through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "formatted-text"), **args)


def Frame(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Frame operation under explicit file-format and conversion rules.

    Example:
        Exercise Frame through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "frame"), **args)


def GenericControl(**args: _typing.Any) -> _typing.Any:
    """
    Perform the GenericControl operation under explicit file-format and conversion rules.

    Example:
        Exercise GenericControl through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "generic-control"), **args)


def Grid(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Grid operation under explicit file-format and conversion rules.

    Example:
        Exercise Grid through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "grid"), **args)


def Hidden(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Hidden operation under explicit file-format and conversion rules.

    Example:
        Exercise Hidden through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "hidden"), **args)


def Image(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Image operation under explicit file-format and conversion rules.

    Example:
        Exercise Image through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "image"), **args)


def ImageFrame(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ImageFrame operation under explicit file-format and conversion rules.

    Example:
        Exercise ImageFrame through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "image-frame"), **args)


def Item(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Item operation under explicit file-format and conversion rules.

    Example:
        Exercise Item through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "item"), **args)


def ListProperty(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ListProperty operation under explicit file-format and conversion rules.

    Example:
        Exercise ListProperty through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "list-property"), **args)


def ListValue(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ListValue operation under explicit file-format and conversion rules.

    Example:
        Exercise ListValue through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "list-value"), **args)


def Listbox(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Listbox operation under explicit file-format and conversion rules.

    Example:
        Exercise Listbox through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "listbox"), **args)


def Number(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Number operation under explicit file-format and conversion rules.

    Example:
        Exercise Number through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "number"), **args)


def Option(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Option operation under explicit file-format and conversion rules.

    Example:
        Exercise Option through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "option"), **args)


def Password(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Password operation under explicit file-format and conversion rules.

    Example:
        Exercise Password through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "password"), **args)


def Properties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Properties operation under explicit file-format and conversion rules.

    Example:
        Exercise Properties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "properties"), **args)


def Property(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Property operation under explicit file-format and conversion rules.

    Example:
        Exercise Property through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "property"), **args)


def Radio(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Radio operation under explicit file-format and conversion rules.

    Example:
        Exercise Radio through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "radio"), **args)


def Text(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Text operation under explicit file-format and conversion rules.

    Example:
        Exercise Text through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "text"), **args)


def Textarea(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Textarea operation under explicit file-format and conversion rules.

    Example:
        Exercise Textarea through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "textarea"), **args)


def Time(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Time operation under explicit file-format and conversion rules.

    Example:
        Exercise Time through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "time"), **args)


def ValueRange(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ValueRange operation under explicit file-format and conversion rules.

    Example:
        Exercise ValueRange through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(FORMNS, "value-range"), **args)
