# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import METANS
from LiuXin_alpha.file_formats.odf.element import Element

# Autogenerated
def AutoReload(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "auto-reload"), **args)


def CreationDate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "creation-date"), **args)


def DateString(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "date-string"), **args)


def DocumentStatistic(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "document-statistic"), **args)


def EditingCycles(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "editing-cycles"), **args)


def EditingDuration(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "editing-duration"), **args)


def Generator(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "generator"), **args)


def HyperlinkBehaviour(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "hyperlink-behaviour"), **args)


def InitialCreator(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "initial-creator"), **args)


def Keyword(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "keyword"), **args)


def PrintDate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "print-date"), **args)


def PrintedBy(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "printed-by"), **args)


def Template(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "template"), **args)


def UserDefined(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(METANS, "user-defined"), **args)
