# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF number, date, time and currency styles.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise number through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_modernized.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import NUMBERNS
from LiuXin_alpha.file_formats.odf.element import Element
from LiuXin_alpha.file_formats.odf.style import StyleElement


# Autogenerated
def AmPm(**args: _typing.Any) -> _typing.Any:
    """
    Perform the AmPm operation under explicit file-format and conversion rules.

    Example:
        Exercise AmPm through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "am-pm"), **args)


def Boolean(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Boolean operation under explicit file-format and conversion rules.

    Example:
        Exercise Boolean through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "boolean"), **args)


def BooleanStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the BooleanStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise BooleanStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(NUMBERNS, "boolean-style"), **args)


def CurrencyStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CurrencyStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise CurrencyStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(NUMBERNS, "currency-style"), **args)


def CurrencySymbol(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CurrencySymbol operation under explicit file-format and conversion rules.

    Example:
        Exercise CurrencySymbol through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "currency-symbol"), **args)


def DateStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DateStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise DateStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(NUMBERNS, "date-style"), **args)


def Day(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Day operation under explicit file-format and conversion rules.

    Example:
        Exercise Day through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "day"), **args)


def DayOfWeek(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DayOfWeek operation under explicit file-format and conversion rules.

    Example:
        Exercise DayOfWeek through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "day-of-week"), **args)


def EmbeddedText(**args: _typing.Any) -> _typing.Any:
    """
    Perform the EmbeddedText operation under explicit file-format and conversion rules.

    Example:
        Exercise EmbeddedText through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "embedded-text"), **args)


def Era(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Era operation under explicit file-format and conversion rules.

    Example:
        Exercise Era through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "era"), **args)


def Fraction(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Fraction operation under explicit file-format and conversion rules.

    Example:
        Exercise Fraction through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "fraction"), **args)


def Hours(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Hours operation under explicit file-format and conversion rules.

    Example:
        Exercise Hours through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "hours"), **args)


def Minutes(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Minutes operation under explicit file-format and conversion rules.

    Example:
        Exercise Minutes through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "minutes"), **args)


def Month(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Month operation under explicit file-format and conversion rules.

    Example:
        Exercise Month through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "month"), **args)


def Number(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Number operation under explicit file-format and conversion rules.

    Example:
        Exercise Number through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "number"), **args)


def NumberStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the NumberStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise NumberStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(NUMBERNS, "number-style"), **args)


def PercentageStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the PercentageStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise PercentageStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(NUMBERNS, "percentage-style"), **args)


def Quarter(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Quarter operation under explicit file-format and conversion rules.

    Example:
        Exercise Quarter through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "quarter"), **args)


def ScientificNumber(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ScientificNumber operation under explicit file-format and conversion rules.

    Example:
        Exercise ScientificNumber through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "scientific-number"), **args)


def Seconds(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Seconds operation under explicit file-format and conversion rules.

    Example:
        Exercise Seconds through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "seconds"), **args)


def Text(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Text operation under explicit file-format and conversion rules.

    Example:
        Exercise Text through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "text"), **args)


def TextContent(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TextContent operation under explicit file-format and conversion rules.

    Example:
        Exercise TextContent through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "text-content"), **args)


def TextStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TextStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise TextStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(NUMBERNS, "text-style"), **args)


def TimeStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TimeStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise TimeStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(NUMBERNS, "time-style"), **args)


def WeekOfYear(**args: _typing.Any) -> _typing.Any:
    """
    Perform the WeekOfYear operation under explicit file-format and conversion rules.

    Example:
        Exercise WeekOfYear through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "week-of-year"), **args)


def Year(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Year operation under explicit file-format and conversion rules.

    Example:
        Exercise Year through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_modernized.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(NUMBERNS, "year"), **args)
