# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF office document and body elements.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise office through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import OFFICENS
from LiuXin_alpha.file_formats.odf.element import Element
from LiuXin_alpha.file_formats.odf.draw import StyleRefElement


# Autogenerated
def Annotation(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Annotation operation under explicit file-format and conversion rules.

    Example:
        Exercise Annotation through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleRefElement(qname=(OFFICENS, "annotation"), **args)


def AutomaticStyles(**args: _typing.Any) -> _typing.Any:
    """
    Perform the AutomaticStyles operation under explicit file-format and conversion rules.

    Example:
        Exercise AutomaticStyles through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "automatic-styles"), **args)


def BinaryData(**args: _typing.Any) -> _typing.Any:
    """
    Perform the BinaryData operation under explicit file-format and conversion rules.

    Example:
        Exercise BinaryData through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "binary-data"), **args)


def Body(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Body operation under explicit file-format and conversion rules.

    Example:
        Exercise Body through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "body"), **args)


def ChangeInfo(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ChangeInfo operation under explicit file-format and conversion rules.

    Example:
        Exercise ChangeInfo through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "change-info"), **args)


def Chart(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Chart operation under explicit file-format and conversion rules.

    Example:
        Exercise Chart through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "chart"), **args)


def DdeSource(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DdeSource operation under explicit file-format and conversion rules.

    Example:
        Exercise DdeSource through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "dde-source"), **args)


def Document(version: str = "1.1", **args: _typing.Any) -> _typing.Any:
    """
    Perform the Document operation under explicit file-format and conversion rules.

    Example:
        Exercise Document through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param version: Value supplied for version under the utility contract.
    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "document"), version=version, **args)


def DocumentContent(version: str = "1.1", **args: _typing.Any) -> _typing.Any:
    """
    Perform the DocumentContent operation under explicit file-format and conversion rules.

    Example:
        Exercise DocumentContent through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param version: Value supplied for version under the utility contract.
    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "document-content"), version=version, **args)


def DocumentMeta(version: str = "1.1", **args: _typing.Any) -> _typing.Any:
    """
    Perform the DocumentMeta operation under explicit file-format and conversion rules.

    Example:
        Exercise DocumentMeta through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param version: Value supplied for version under the utility contract.
    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "document-meta"), version=version, **args)


def DocumentSettings(version: str = "1.1", **args: _typing.Any) -> _typing.Any:
    """
    Perform the DocumentSettings operation under explicit file-format and conversion rules.

    Example:
        Exercise DocumentSettings through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param version: Value supplied for version under the utility contract.
    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "document-settings"), version=version, **args)


def DocumentStyles(version: str = "1.1", **args: _typing.Any) -> _typing.Any:
    """
    Perform the DocumentStyles operation under explicit file-format and conversion rules.

    Example:
        Exercise DocumentStyles through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param version: Value supplied for version under the utility contract.
    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "document-styles"), version=version, **args)


def Drawing(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Drawing operation under explicit file-format and conversion rules.

    Example:
        Exercise Drawing through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "drawing"), **args)


def EventListeners(**args: _typing.Any) -> _typing.Any:
    """
    Perform the EventListeners operation under explicit file-format and conversion rules.

    Example:
        Exercise EventListeners through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "event-listeners"), **args)


def FontFaceDecls(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FontFaceDecls operation under explicit file-format and conversion rules.

    Example:
        Exercise FontFaceDecls through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "font-face-decls"), **args)


def Forms(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Forms operation under explicit file-format and conversion rules.

    Example:
        Exercise Forms through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "forms"), **args)


def Image(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Image operation under explicit file-format and conversion rules.

    Example:
        Exercise Image through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "image"), **args)


def MasterStyles(**args: _typing.Any) -> _typing.Any:
    """
    Perform the MasterStyles operation under explicit file-format and conversion rules.

    Example:
        Exercise MasterStyles through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "master-styles"), **args)


def Meta(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Meta operation under explicit file-format and conversion rules.

    Example:
        Exercise Meta through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "meta"), **args)


def Presentation(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Presentation operation under explicit file-format and conversion rules.

    Example:
        Exercise Presentation through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "presentation"), **args)


def Script(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Script operation under explicit file-format and conversion rules.

    Example:
        Exercise Script through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "script"), **args)


def Scripts(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Scripts operation under explicit file-format and conversion rules.

    Example:
        Exercise Scripts through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "scripts"), **args)


def Settings(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Settings operation under explicit file-format and conversion rules.

    Example:
        Exercise Settings through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "settings"), **args)


def Spreadsheet(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Spreadsheet operation under explicit file-format and conversion rules.

    Example:
        Exercise Spreadsheet through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "spreadsheet"), **args)


def Styles(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Styles operation under explicit file-format and conversion rules.

    Example:
        Exercise Styles through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "styles"), **args)


def Text(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Text operation under explicit file-format and conversion rules.

    Example:
        Exercise Text through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(OFFICENS, "text"), **args)


# Autogenerated end
