# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF presentation elements and settings.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise presentation through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import PRESENTATIONNS
from LiuXin_alpha.file_formats.odf.element import Element

# ODF 1.0 section 9.6 and 9.7
# Autogenerated
def AnimationGroup(**args: _typing.Any) -> _typing.Any:
    """
    Perform the AnimationGroup operation under explicit file-format and conversion rules.

    Example:
        Exercise AnimationGroup through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "animation-group"), **args)


def Animations(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Animations operation under explicit file-format and conversion rules.

    Example:
        Exercise Animations through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "animations"), **args)


def DateTime(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DateTime operation under explicit file-format and conversion rules.

    Example:
        Exercise DateTime through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "date-time"), **args)


def DateTimeDecl(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DateTimeDecl operation under explicit file-format and conversion rules.

    Example:
        Exercise DateTimeDecl through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "date-time-decl"), **args)


def Dim(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Dim operation under explicit file-format and conversion rules.

    Example:
        Exercise Dim through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "dim"), **args)


def EventListener(**args: _typing.Any) -> _typing.Any:
    """
    Perform the EventListener operation under explicit file-format and conversion rules.

    Example:
        Exercise EventListener through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "event-listener"), **args)


def Footer(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Footer operation under explicit file-format and conversion rules.

    Example:
        Exercise Footer through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "footer"), **args)


def FooterDecl(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FooterDecl operation under explicit file-format and conversion rules.

    Example:
        Exercise FooterDecl through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "footer-decl"), **args)


def Header(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Header operation under explicit file-format and conversion rules.

    Example:
        Exercise Header through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "header"), **args)


def HeaderDecl(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HeaderDecl operation under explicit file-format and conversion rules.

    Example:
        Exercise HeaderDecl through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "header-decl"), **args)


def HideShape(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HideShape operation under explicit file-format and conversion rules.

    Example:
        Exercise HideShape through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "hide-shape"), **args)


def HideText(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HideText operation under explicit file-format and conversion rules.

    Example:
        Exercise HideText through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "hide-text"), **args)


def Notes(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Notes operation under explicit file-format and conversion rules.

    Example:
        Exercise Notes through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "notes"), **args)


def Placeholder(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Placeholder operation under explicit file-format and conversion rules.

    Example:
        Exercise Placeholder through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "placeholder"), **args)


def Play(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Play operation under explicit file-format and conversion rules.

    Example:
        Exercise Play through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "play"), **args)


def Settings(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Settings operation under explicit file-format and conversion rules.

    Example:
        Exercise Settings through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "settings"), **args)


def Show(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Show operation under explicit file-format and conversion rules.

    Example:
        Exercise Show through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "show"), **args)


def ShowShape(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ShowShape operation under explicit file-format and conversion rules.

    Example:
        Exercise ShowShape through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "show-shape"), **args)


def ShowText(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ShowText operation under explicit file-format and conversion rules.

    Example:
        Exercise ShowText through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "show-text"), **args)


def Sound(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Sound operation under explicit file-format and conversion rules.

    Example:
        Exercise Sound through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(PRESENTATIONNS, "sound"), **args)
