# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF style, page-layout and formatting property elements.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise style through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import STYLENS
from LiuXin_alpha.file_formats.odf.element import Element


def StyleElement(**args: _typing.Any) -> _typing.Any:
    """
    Perform the StyleElement operation under explicit file-format and conversion rules.

    Example:
        Exercise StyleElement through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    e = Element(**args)
    if args.get("check_grammar", True) == True:
        if "displayname" not in args:
            e.setAttrNS(STYLENS, "display-name", args.get("name"))
    return e


# Autogenerated
def BackgroundImage(**args: _typing.Any) -> _typing.Any:
    """
    Perform the BackgroundImage operation under explicit file-format and conversion rules.

    Example:
        Exercise BackgroundImage through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "background-image"), **args)


def ChartProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ChartProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise ChartProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "chart-properties"), **args)


def Column(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Column operation under explicit file-format and conversion rules.

    Example:
        Exercise Column through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "column"), **args)


def ColumnSep(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ColumnSep operation under explicit file-format and conversion rules.

    Example:
        Exercise ColumnSep through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "column-sep"), **args)


def Columns(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Columns operation under explicit file-format and conversion rules.

    Example:
        Exercise Columns through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "columns"), **args)


def DefaultStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DefaultStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise DefaultStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "default-style"), **args)


def DrawingPageProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DrawingPageProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise DrawingPageProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "drawing-page-properties"), **args)


def DropCap(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DropCap operation under explicit file-format and conversion rules.

    Example:
        Exercise DropCap through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "drop-cap"), **args)


def FontFace(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FontFace operation under explicit file-format and conversion rules.

    Example:
        Exercise FontFace through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "font-face"), **args)


def Footer(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Footer operation under explicit file-format and conversion rules.

    Example:
        Exercise Footer through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "footer"), **args)


def FooterLeft(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FooterLeft operation under explicit file-format and conversion rules.

    Example:
        Exercise FooterLeft through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "footer-left"), **args)


def FooterStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FooterStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise FooterStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "footer-style"), **args)


def FootnoteSep(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FootnoteSep operation under explicit file-format and conversion rules.

    Example:
        Exercise FootnoteSep through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "footnote-sep"), **args)


def GraphicProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the GraphicProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise GraphicProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "graphic-properties"), **args)


def HandoutMaster(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HandoutMaster operation under explicit file-format and conversion rules.

    Example:
        Exercise HandoutMaster through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "handout-master"), **args)


def Header(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Header operation under explicit file-format and conversion rules.

    Example:
        Exercise Header through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "header"), **args)


def HeaderFooterProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HeaderFooterProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise HeaderFooterProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "header-footer-properties"), **args)


def HeaderLeft(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HeaderLeft operation under explicit file-format and conversion rules.

    Example:
        Exercise HeaderLeft through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "header-left"), **args)


def HeaderStyle(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HeaderStyle operation under explicit file-format and conversion rules.

    Example:
        Exercise HeaderStyle through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "header-style"), **args)


def ListLevelProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ListLevelProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise ListLevelProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "list-level-properties"), **args)


def Map(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Map operation under explicit file-format and conversion rules.

    Example:
        Exercise Map through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "map"), **args)


def MasterPage(**args: _typing.Any) -> _typing.Any:
    """
    Perform the MasterPage operation under explicit file-format and conversion rules.

    Example:
        Exercise MasterPage through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(STYLENS, "master-page"), **args)


def PageLayout(**args: _typing.Any) -> _typing.Any:
    """
    Perform the PageLayout operation under explicit file-format and conversion rules.

    Example:
        Exercise PageLayout through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "page-layout"), **args)


def PageLayoutProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the PageLayoutProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise PageLayoutProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "page-layout-properties"), **args)


def ParagraphProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ParagraphProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise ParagraphProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "paragraph-properties"), **args)


def PresentationPageLayout(**args: _typing.Any) -> _typing.Any:
    """
    Perform the PresentationPageLayout operation under explicit file-format and conversion rules.

    Example:
        Exercise PresentationPageLayout through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(STYLENS, "presentation-page-layout"), **args)


def RegionCenter(**args: _typing.Any) -> _typing.Any:
    """
    Perform the RegionCenter operation under explicit file-format and conversion rules.

    Example:
        Exercise RegionCenter through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "region-center"), **args)


def RegionLeft(**args: _typing.Any) -> _typing.Any:
    """
    Perform the RegionLeft operation under explicit file-format and conversion rules.

    Example:
        Exercise RegionLeft through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "region-left"), **args)


def RegionRight(**args: _typing.Any) -> _typing.Any:
    """
    Perform the RegionRight operation under explicit file-format and conversion rules.

    Example:
        Exercise RegionRight through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "region-right"), **args)


def RubyProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the RubyProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise RubyProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "ruby-properties"), **args)


def SectionProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SectionProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise SectionProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "section-properties"), **args)


def Style(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Style operation under explicit file-format and conversion rules.

    Example:
        Exercise Style through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return StyleElement(qname=(STYLENS, "style"), **args)


def TabStop(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TabStop operation under explicit file-format and conversion rules.

    Example:
        Exercise TabStop through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "tab-stop"), **args)


def TabStops(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TabStops operation under explicit file-format and conversion rules.

    Example:
        Exercise TabStops through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "tab-stops"), **args)


def TableCellProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableCellProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise TableCellProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "table-cell-properties"), **args)


def TableColumnProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableColumnProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise TableColumnProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "table-column-properties"), **args)


def TableProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise TableProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "table-properties"), **args)


def TableRowProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableRowProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise TableRowProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "table-row-properties"), **args)


def TextProperties(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TextProperties operation under explicit file-format and conversion rules.

    Example:
        Exercise TextProperties through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(STYLENS, "text-properties"), **args)
