# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

"""
Construct ODF tables, rows, columns, cells and database ranges.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise table through a consuming regression::

        python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py
"""
from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.namespaces import TABLENS
from LiuXin_alpha.file_formats.odf.element import Element


# Autogenerated
def Body(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Body operation under explicit file-format and conversion rules.

    Example:
        Exercise Body through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "body"), **args)


def CalculationSettings(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CalculationSettings operation under explicit file-format and conversion rules.

    Example:
        Exercise CalculationSettings through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "calculation-settings"), **args)


def CellAddress(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CellAddress operation under explicit file-format and conversion rules.

    Example:
        Exercise CellAddress through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "cell-address"), **args)


def CellContentChange(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CellContentChange operation under explicit file-format and conversion rules.

    Example:
        Exercise CellContentChange through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "cell-content-change"), **args)


def CellContentDeletion(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CellContentDeletion operation under explicit file-format and conversion rules.

    Example:
        Exercise CellContentDeletion through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "cell-content-deletion"), **args)


def CellRangeSource(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CellRangeSource operation under explicit file-format and conversion rules.

    Example:
        Exercise CellRangeSource through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "cell-range-source"), **args)


def ChangeDeletion(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ChangeDeletion operation under explicit file-format and conversion rules.

    Example:
        Exercise ChangeDeletion through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "change-deletion"), **args)


def ChangeTrackTableCell(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ChangeTrackTableCell operation under explicit file-format and conversion rules.

    Example:
        Exercise ChangeTrackTableCell through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "change-track-table-cell"), **args)


def Consolidation(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Consolidation operation under explicit file-format and conversion rules.

    Example:
        Exercise Consolidation through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "consolidation"), **args)


def ContentValidation(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ContentValidation operation under explicit file-format and conversion rules.

    Example:
        Exercise ContentValidation through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "content-validation"), **args)


def ContentValidations(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ContentValidations operation under explicit file-format and conversion rules.

    Example:
        Exercise ContentValidations through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "content-validations"), **args)


def CoveredTableCell(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CoveredTableCell operation under explicit file-format and conversion rules.

    Example:
        Exercise CoveredTableCell through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "covered-table-cell"), **args)


def CutOffs(**args: _typing.Any) -> _typing.Any:
    """
    Perform the CutOffs operation under explicit file-format and conversion rules.

    Example:
        Exercise CutOffs through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "cut-offs"), **args)


def DataPilotDisplayInfo(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotDisplayInfo operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotDisplayInfo through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-display-info"), **args)


def DataPilotField(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotField operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotField through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-field"), **args)


def DataPilotFieldReference(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotFieldReference operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotFieldReference through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-field-reference"), **args)


def DataPilotGroup(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotGroup operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotGroup through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-group"), **args)


def DataPilotGroupMember(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotGroupMember operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotGroupMember through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-group-member"), **args)


def DataPilotGroups(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotGroups operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotGroups through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-groups"), **args)


def DataPilotLayoutInfo(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotLayoutInfo operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotLayoutInfo through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-layout-info"), **args)


def DataPilotLevel(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotLevel operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotLevel through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-level"), **args)


def DataPilotMember(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotMember operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotMember through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-member"), **args)


def DataPilotMembers(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotMembers operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotMembers through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-members"), **args)


def DataPilotSortInfo(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotSortInfo operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotSortInfo through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-sort-info"), **args)


def DataPilotSubtotal(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotSubtotal operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotSubtotal through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-subtotal"), **args)


def DataPilotSubtotals(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotSubtotals operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotSubtotals through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-subtotals"), **args)


def DataPilotTable(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotTable operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotTable through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-table"), **args)


def DataPilotTables(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DataPilotTables operation under explicit file-format and conversion rules.

    Example:
        Exercise DataPilotTables through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "data-pilot-tables"), **args)


def DatabaseRange(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DatabaseRange operation under explicit file-format and conversion rules.

    Example:
        Exercise DatabaseRange through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "database-range"), **args)


def DatabaseRanges(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DatabaseRanges operation under explicit file-format and conversion rules.

    Example:
        Exercise DatabaseRanges through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "database-ranges"), **args)


def DatabaseSourceQuery(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DatabaseSourceQuery operation under explicit file-format and conversion rules.

    Example:
        Exercise DatabaseSourceQuery through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "database-source-query"), **args)


def DatabaseSourceSql(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DatabaseSourceSql operation under explicit file-format and conversion rules.

    Example:
        Exercise DatabaseSourceSql through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "database-source-sql"), **args)


def DatabaseSourceTable(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DatabaseSourceTable operation under explicit file-format and conversion rules.

    Example:
        Exercise DatabaseSourceTable through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "database-source-table"), **args)


def DdeLink(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DdeLink operation under explicit file-format and conversion rules.

    Example:
        Exercise DdeLink through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "dde-link"), **args)


def DdeLinks(**args: _typing.Any) -> _typing.Any:
    """
    Perform the DdeLinks operation under explicit file-format and conversion rules.

    Example:
        Exercise DdeLinks through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "dde-links"), **args)


def Deletion(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Deletion operation under explicit file-format and conversion rules.

    Example:
        Exercise Deletion through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "deletion"), **args)


def Deletions(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Deletions operation under explicit file-format and conversion rules.

    Example:
        Exercise Deletions through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "deletions"), **args)


def Dependencies(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Dependencies operation under explicit file-format and conversion rules.

    Example:
        Exercise Dependencies through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "dependencies"), **args)


def Dependency(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Dependency operation under explicit file-format and conversion rules.

    Example:
        Exercise Dependency through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "dependency"), **args)


def Detective(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Detective operation under explicit file-format and conversion rules.

    Example:
        Exercise Detective through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "detective"), **args)


def ErrorMacro(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ErrorMacro operation under explicit file-format and conversion rules.

    Example:
        Exercise ErrorMacro through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "error-macro"), **args)


def ErrorMessage(**args: _typing.Any) -> _typing.Any:
    """
    Perform the ErrorMessage operation under explicit file-format and conversion rules.

    Example:
        Exercise ErrorMessage through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "error-message"), **args)


def EvenColumns(**args: _typing.Any) -> _typing.Any:
    """
    Perform the EvenColumns operation under explicit file-format and conversion rules.

    Example:
        Exercise EvenColumns through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "even-columns"), **args)


def EvenRows(**args: _typing.Any) -> _typing.Any:
    """
    Perform the EvenRows operation under explicit file-format and conversion rules.

    Example:
        Exercise EvenRows through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "even-rows"), **args)


def Filter(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Filter operation under explicit file-format and conversion rules.

    Example:
        Exercise Filter through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "filter"), **args)


def FilterAnd(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FilterAnd operation under explicit file-format and conversion rules.

    Example:
        Exercise FilterAnd through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "filter-and"), **args)


def FilterCondition(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FilterCondition operation under explicit file-format and conversion rules.

    Example:
        Exercise FilterCondition through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "filter-condition"), **args)


def FilterOr(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FilterOr operation under explicit file-format and conversion rules.

    Example:
        Exercise FilterOr through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "filter-or"), **args)


def FirstColumn(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FirstColumn operation under explicit file-format and conversion rules.

    Example:
        Exercise FirstColumn through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "first-column"), **args)


def FirstRow(**args: _typing.Any) -> _typing.Any:
    """
    Perform the FirstRow operation under explicit file-format and conversion rules.

    Example:
        Exercise FirstRow through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "first-row"), **args)


def HelpMessage(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HelpMessage operation under explicit file-format and conversion rules.

    Example:
        Exercise HelpMessage through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "help-message"), **args)


def HighlightedRange(**args: _typing.Any) -> _typing.Any:
    """
    Perform the HighlightedRange operation under explicit file-format and conversion rules.

    Example:
        Exercise HighlightedRange through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "highlighted-range"), **args)


def Insertion(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Insertion operation under explicit file-format and conversion rules.

    Example:
        Exercise Insertion through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "insertion"), **args)


def InsertionCutOff(**args: _typing.Any) -> _typing.Any:
    """
    Perform the InsertionCutOff operation under explicit file-format and conversion rules.

    Example:
        Exercise InsertionCutOff through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "insertion-cut-off"), **args)


def Iteration(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Iteration operation under explicit file-format and conversion rules.

    Example:
        Exercise Iteration through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "iteration"), **args)


def LabelRange(**args: _typing.Any) -> _typing.Any:
    """
    Perform the LabelRange operation under explicit file-format and conversion rules.

    Example:
        Exercise LabelRange through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "label-range"), **args)


def LabelRanges(**args: _typing.Any) -> _typing.Any:
    """
    Perform the LabelRanges operation under explicit file-format and conversion rules.

    Example:
        Exercise LabelRanges through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "label-ranges"), **args)


def LastColumn(**args: _typing.Any) -> _typing.Any:
    """
    Perform the LastColumn operation under explicit file-format and conversion rules.

    Example:
        Exercise LastColumn through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "last-column"), **args)


def LastRow(**args: _typing.Any) -> _typing.Any:
    """
    Perform the LastRow operation under explicit file-format and conversion rules.

    Example:
        Exercise LastRow through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "last-row"), **args)


def Movement(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Movement operation under explicit file-format and conversion rules.

    Example:
        Exercise Movement through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "movement"), **args)


def MovementCutOff(**args: _typing.Any) -> _typing.Any:
    """
    Perform the MovementCutOff operation under explicit file-format and conversion rules.

    Example:
        Exercise MovementCutOff through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "movement-cut-off"), **args)


def NamedExpression(**args: _typing.Any) -> _typing.Any:
    """
    Perform the NamedExpression operation under explicit file-format and conversion rules.

    Example:
        Exercise NamedExpression through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "named-expression"), **args)


def NamedExpressions(**args: _typing.Any) -> _typing.Any:
    """
    Perform the NamedExpressions operation under explicit file-format and conversion rules.

    Example:
        Exercise NamedExpressions through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "named-expressions"), **args)


def NamedRange(**args: _typing.Any) -> _typing.Any:
    """
    Perform the NamedRange operation under explicit file-format and conversion rules.

    Example:
        Exercise NamedRange through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "named-range"), **args)


def NullDate(**args: _typing.Any) -> _typing.Any:
    """
    Perform the NullDate operation under explicit file-format and conversion rules.

    Example:
        Exercise NullDate through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "null-date"), **args)


def OddColumns(**args: _typing.Any) -> _typing.Any:
    """
    Perform the OddColumns operation under explicit file-format and conversion rules.

    Example:
        Exercise OddColumns through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "odd-columns"), **args)


def OddRows(**args: _typing.Any) -> _typing.Any:
    """
    Perform the OddRows operation under explicit file-format and conversion rules.

    Example:
        Exercise OddRows through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "odd-rows"), **args)


def Operation(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Operation operation under explicit file-format and conversion rules.

    Example:
        Exercise Operation through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "operation"), **args)


def Previous(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Previous operation under explicit file-format and conversion rules.

    Example:
        Exercise Previous through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "previous"), **args)


def Scenario(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Scenario operation under explicit file-format and conversion rules.

    Example:
        Exercise Scenario through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "scenario"), **args)


def Shapes(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Shapes operation under explicit file-format and conversion rules.

    Example:
        Exercise Shapes through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "shapes"), **args)


def Sort(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Sort operation under explicit file-format and conversion rules.

    Example:
        Exercise Sort through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "sort"), **args)


def SortBy(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SortBy operation under explicit file-format and conversion rules.

    Example:
        Exercise SortBy through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "sort-by"), **args)


def SortGroups(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SortGroups operation under explicit file-format and conversion rules.

    Example:
        Exercise SortGroups through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "sort-groups"), **args)


def SourceCellRange(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SourceCellRange operation under explicit file-format and conversion rules.

    Example:
        Exercise SourceCellRange through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "source-cell-range"), **args)


def SourceRangeAddress(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SourceRangeAddress operation under explicit file-format and conversion rules.

    Example:
        Exercise SourceRangeAddress through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "source-range-address"), **args)


def SourceService(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SourceService operation under explicit file-format and conversion rules.

    Example:
        Exercise SourceService through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "source-service"), **args)


def SubtotalField(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SubtotalField operation under explicit file-format and conversion rules.

    Example:
        Exercise SubtotalField through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "subtotal-field"), **args)


def SubtotalRule(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SubtotalRule operation under explicit file-format and conversion rules.

    Example:
        Exercise SubtotalRule through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "subtotal-rule"), **args)


def SubtotalRules(**args: _typing.Any) -> _typing.Any:
    """
    Perform the SubtotalRules operation under explicit file-format and conversion rules.

    Example:
        Exercise SubtotalRules through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "subtotal-rules"), **args)


def Table(**args: _typing.Any) -> _typing.Any:
    """
    Perform the Table operation under explicit file-format and conversion rules.

    Example:
        Exercise Table through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table"), **args)


def TableCell(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableCell operation under explicit file-format and conversion rules.

    Example:
        Exercise TableCell through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-cell"), **args)


def TableColumn(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableColumn operation under explicit file-format and conversion rules.

    Example:
        Exercise TableColumn through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-column"), **args)


def TableColumnGroup(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableColumnGroup operation under explicit file-format and conversion rules.

    Example:
        Exercise TableColumnGroup through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-column-group"), **args)


def TableColumns(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableColumns operation under explicit file-format and conversion rules.

    Example:
        Exercise TableColumns through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-columns"), **args)


def TableHeaderColumns(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableHeaderColumns operation under explicit file-format and conversion rules.

    Example:
        Exercise TableHeaderColumns through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-header-columns"), **args)


def TableHeaderRows(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableHeaderRows operation under explicit file-format and conversion rules.

    Example:
        Exercise TableHeaderRows through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-header-rows"), **args)


def TableRow(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableRow operation under explicit file-format and conversion rules.

    Example:
        Exercise TableRow through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-row"), **args)


def TableRowGroup(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableRowGroup operation under explicit file-format and conversion rules.

    Example:
        Exercise TableRowGroup through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-row-group"), **args)


def TableRows(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableRows operation under explicit file-format and conversion rules.

    Example:
        Exercise TableRows through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-rows"), **args)


def TableSource(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableSource operation under explicit file-format and conversion rules.

    Example:
        Exercise TableSource through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-source"), **args)


def TableTemplate(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TableTemplate operation under explicit file-format and conversion rules.

    Example:
        Exercise TableTemplate through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "table-template"), **args)


def TargetRangeAddress(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TargetRangeAddress operation under explicit file-format and conversion rules.

    Example:
        Exercise TargetRangeAddress through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "target-range-address"), **args)


def TrackedChanges(**args: _typing.Any) -> _typing.Any:
    """
    Perform the TrackedChanges operation under explicit file-format and conversion rules.

    Example:
        Exercise TrackedChanges through a consuming regression::

            python -m pytest -q tests/file_formats/odf/test_odf_full_stack_unicode_torture.py


    :param args: Positional values forwarded to the compatibility implementation.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    return Element(qname=(TABLENS, "tracked-changes"), **args)
