# -*- coding: utf-8 -*-
# Copyright (C) 2006-2007 Søren Roug, European Environment Agency
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Contributor(s):
#

from __future__ import annotations

import typing as _typing
from LiuXin_alpha.file_formats.odf.element import Element
from LiuXin_alpha.file_formats.odf.namespaces import TEXTNS
from LiuXin_alpha.file_formats.odf.style import StyleElement


# Autogenerated
def A(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "a"), **args)


def AlphabeticalIndex(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "alphabetical-index"), **args)


def AlphabeticalIndexAutoMarkFile(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "alphabetical-index-auto-mark-file"), **args)


def AlphabeticalIndexEntryTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "alphabetical-index-entry-template"), **args)


def AlphabeticalIndexMark(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "alphabetical-index-mark"), **args)


def AlphabeticalIndexMarkEnd(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "alphabetical-index-mark-end"), **args)


def AlphabeticalIndexMarkStart(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "alphabetical-index-mark-start"), **args)


def AlphabeticalIndexSource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "alphabetical-index-source"), **args)


def AuthorInitials(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "author-initials"), **args)


def AuthorName(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "author-name"), **args)


def Bibliography(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bibliography"), **args)


def BibliographyConfiguration(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bibliography-configuration"), **args)


def BibliographyEntryTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bibliography-entry-template"), **args)


def BibliographyMark(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bibliography-mark"), **args)


def BibliographySource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bibliography-source"), **args)


def Bookmark(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bookmark"), **args)


def BookmarkEnd(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bookmark-end"), **args)


def BookmarkRef(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bookmark-ref"), **args)


def BookmarkStart(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "bookmark-start"), **args)


def Change(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "change"), **args)


def ChangeEnd(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "change-end"), **args)


def ChangeStart(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "change-start"), **args)


def ChangedRegion(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "changed-region"), **args)


def Chapter(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "chapter"), **args)


def CharacterCount(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "character-count"), **args)


def ConditionalText(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "conditional-text"), **args)


def CreationDate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "creation-date"), **args)


def CreationTime(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "creation-time"), **args)


def Creator(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "creator"), **args)


def DatabaseDisplay(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "database-display"), **args)


def DatabaseName(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "database-name"), **args)


def DatabaseNext(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "database-next"), **args)


def DatabaseRowNumber(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "database-row-number"), **args)


def DatabaseRowSelect(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "database-row-select"), **args)


def Date(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "date"), **args)


def DdeConnection(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "dde-connection"), **args)


def DdeConnectionDecl(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "dde-connection-decl"), **args)


def DdeConnectionDecls(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "dde-connection-decls"), **args)


def Deletion(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "deletion"), **args)


def Description(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "description"), **args)


def EditingCycles(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "editing-cycles"), **args)


def EditingDuration(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "editing-duration"), **args)


def ExecuteMacro(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "execute-macro"), **args)


def Expression(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "expression"), **args)


def FileName(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "file-name"), **args)


def FormatChange(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "format-change"), **args)


def H(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "h"), **args)


def HiddenParagraph(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "hidden-paragraph"), **args)


def HiddenText(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "hidden-text"), **args)


def IllustrationIndex(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "illustration-index"), **args)


def IllustrationIndexEntryTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "illustration-index-entry-template"), **args)


def IllustrationIndexSource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "illustration-index-source"), **args)


def ImageCount(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "image-count"), **args)


def IndexBody(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-body"), **args)


def IndexEntryBibliography(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-bibliography"), **args)


def IndexEntryChapter(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-chapter"), **args)


def IndexEntryLinkEnd(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-link-end"), **args)


def IndexEntryLinkStart(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-link-start"), **args)


def IndexEntryPageNumber(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-page-number"), **args)


def IndexEntrySpan(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-span"), **args)


def IndexEntryTabStop(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-tab-stop"), **args)


def IndexEntryText(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-entry-text"), **args)


def IndexSourceStyle(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-source-style"), **args)


def IndexSourceStyles(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-source-styles"), **args)


def IndexTitle(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-title"), **args)


def IndexTitleTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "index-title-template"), **args)


def InitialCreator(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "initial-creator"), **args)


def Insertion(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "insertion"), **args)


def Keywords(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "keywords"), **args)


def LineBreak(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "line-break"), **args)


def LinenumberingConfiguration(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "linenumbering-configuration"), **args)


def LinenumberingSeparator(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "linenumbering-separator"), **args)


def List(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "list"), **args)


def ListHeader(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "list-header"), **args)


def ListItem(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "list-item"), **args)


def ListLevelStyleBullet(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "list-level-style-bullet"), **args)


def ListLevelStyleImage(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "list-level-style-image"), **args)


def ListLevelStyleNumber(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "list-level-style-number"), **args)


def ListStyle(**args: _typing.Any) -> _typing.Any:
    return StyleElement(qname=(TEXTNS, "list-style"), **args)


def Measure(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "measure"), **args)


def ModificationDate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "modification-date"), **args)


def ModificationTime(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "modification-time"), **args)


def Note(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "note"), **args)


def NoteBody(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "note-body"), **args)


def NoteCitation(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "note-citation"), **args)


def NoteContinuationNoticeBackward(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "note-continuation-notice-backward"), **args)


def NoteContinuationNoticeForward(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "note-continuation-notice-forward"), **args)


def NoteRef(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "note-ref"), **args)


def NotesConfiguration(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "notes-configuration"), **args)


def Number(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "number"), **args)


def NumberedParagraph(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "numbered-paragraph"), **args)


def ObjectCount(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "object-count"), **args)


def ObjectIndex(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "object-index"), **args)


def ObjectIndexEntryTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "object-index-entry-template"), **args)


def ObjectIndexSource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "object-index-source"), **args)


def OutlineLevelStyle(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "outline-level-style"), **args)


def OutlineStyle(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "outline-style"), **args)


def P(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "p"), **args)


def Page(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "page"), **args)


def PageContinuation(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "page-continuation"), **args)


def PageCount(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "page-count"), **args)


def PageNumber(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "page-number"), **args)


def PageSequence(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "page-sequence"), **args)


def PageVariableGet(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "page-variable-get"), **args)


def PageVariableSet(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "page-variable-set"), **args)


def ParagraphCount(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "paragraph-count"), **args)


def Placeholder(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "placeholder"), **args)


def PrintDate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "print-date"), **args)


def PrintTime(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "print-time"), **args)


def PrintedBy(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "printed-by"), **args)


def ReferenceMark(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "reference-mark"), **args)


def ReferenceMarkEnd(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "reference-mark-end"), **args)


def ReferenceMarkStart(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "reference-mark-start"), **args)


def ReferenceRef(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "reference-ref"), **args)


def Ruby(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "ruby"), **args)


def RubyBase(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "ruby-base"), **args)


def RubyText(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "ruby-text"), **args)


def S(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "s"), **args)


def Script(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "script"), **args)


def Section(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "section"), **args)


def SectionSource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "section-source"), **args)


def SenderCity(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-city"), **args)


def SenderCompany(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-company"), **args)


def SenderCountry(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-country"), **args)


def SenderEmail(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-email"), **args)


def SenderFax(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-fax"), **args)


def SenderFirstname(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-firstname"), **args)


def SenderInitials(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-initials"), **args)


def SenderLastname(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-lastname"), **args)


def SenderPhonePrivate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-phone-private"), **args)


def SenderPhoneWork(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-phone-work"), **args)


def SenderPosition(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-position"), **args)


def SenderPostalCode(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-postal-code"), **args)


def SenderStateOrProvince(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-state-or-province"), **args)


def SenderStreet(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-street"), **args)


def SenderTitle(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sender-title"), **args)


def Sequence(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sequence"), **args)


def SequenceDecl(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sequence-decl"), **args)


def SequenceDecls(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sequence-decls"), **args)


def SequenceRef(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sequence-ref"), **args)


def SheetName(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sheet-name"), **args)


def SoftPageBreak(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "soft-page-break"), **args)


def SortKey(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "sort-key"), **args)


def Span(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "span"), **args)


def Subject(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "subject"), **args)


def Tab(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "tab"), **args)


def TableCount(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-count"), **args)


def TableFormula(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-formula"), **args)


def TableIndex(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-index"), **args)


def TableIndexEntryTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-index-entry-template"), **args)


def TableIndexSource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-index-source"), **args)


def TableOfContent(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-of-content"), **args)


def TableOfContentEntryTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-of-content-entry-template"), **args)


def TableOfContentSource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "table-of-content-source"), **args)


def TemplateName(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "template-name"), **args)


def TextInput(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "text-input"), **args)


def Time(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "time"), **args)


def Title(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "title"), **args)


def TocMark(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "toc-mark"), **args)


def TocMarkEnd(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "toc-mark-end"), **args)


def TocMarkStart(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "toc-mark-start"), **args)


def TrackedChanges(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "tracked-changes"), **args)


def UserDefined(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-defined"), **args)


def UserFieldDecl(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-field-decl"), **args)


def UserFieldDecls(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-field-decls"), **args)


def UserFieldGet(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-field-get"), **args)


def UserFieldInput(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-field-input"), **args)


def UserIndex(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-index"), **args)


def UserIndexEntryTemplate(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-index-entry-template"), **args)


def UserIndexMark(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-index-mark"), **args)


def UserIndexMarkEnd(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-index-mark-end"), **args)


def UserIndexMarkStart(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-index-mark-start"), **args)


def UserIndexSource(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "user-index-source"), **args)


def VariableDecl(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "variable-decl"), **args)


def VariableDecls(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "variable-decls"), **args)


def VariableGet(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "variable-get"), **args)


def VariableInput(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "variable-input"), **args)


def VariableSet(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "variable-set"), **args)


def WordCount(**args: _typing.Any) -> _typing.Any:
    return Element(qname=(TEXTNS, "word-count"), **args)
