class CommonDBProperties(object):
    """
    These properties should be true for EVERY test database. Unless there is very good reason that they be different.
    """

    # ------------------------------------------------------------------
    # Alpha-normalized live-schema subset
    # ------------------------------------------------------------------

    alpha_focus_tables = (
        "database_version",
        "works",
        "series",
        "expressions",
        "manifestations",
        "items",
        "files",
        "agents",
        "labels",
    )

    alpha_focus_table_columns = {
        "database_version": [
            "database_version_id",
            "database_version_version",
            "database_version_created_timestamp_ep_k",
            "database_version_modified_timestamp_ep_k",
            "database_version_source_created_datestamp_ep_k",
            "database_version_source_modified_datestamp_ep_k",
        ],
        "works": [
            "work_id",
            "work_type",
            "work_medium",
            "work_title",
            "work_canonical_title",
            "work_sort_title",
            "work_creator_sort",
            "work_flags",
            "work_original_language_id",
            "work_original_year",
            "work_original_date",
            "work_original_copyright_date",
            "work_wikipedia_link",
            "work_is_fiction",
            "work_audience",
            "work_completion_status",
            "work_discovery_note",
            "work_created_timestamp_ep_k",
            "work_modified_timestamp_ep_k",
            "work_source_created_datestamp_ep_k",
            "work_source_modified_datestamp_ep_k",
            "work_scratch",
        ],
        "series": [
            "series_id",
            "series",
            "series_name_norm",
            "series_sort",
            "series_phash",
            "series_over_author",
            "series_parent_id",
            "series_parent_position",
            "series_tree_id",
            "series_full",
            "series_created_timestamp_ep_k",
            "series_modified_timestamp_ep_k",
            "series_source_created_datestamp_ep_k",
            "series_source_modified_datestamp_ep_k",
            "series_scratch",
        ],
        "expressions": [
            "expression_id",
            "expression_type",
            "expression_label",
            "expression_year",
            "expression_is_preferred",
            "expression_original_date",
            "expression_original_copyright_date",
            "expression_flags",
            "expression_language_id",
            "expression_mode",
            "expression_title_override",
            "expression_subtitle",
            "expression_wordcount",
            "expression_fiction_length_category",
            "expression_cut_type",
            "expression_nominal_duration_seconds",
            "expression_status",
            "expression_origin_note",
            "expression_created_timestamp_ep_k",
            "expression_modified_timestamp_ep_k",
            "expression_source_created_datestamp_ep_k",
            "expression_source_modified_datestamp_ep_k",
            "expression_scratch",
        ],
        "manifestations": [
            "manifestation_id",
            "manifestation_subtitle",
            "manifestation_carrier_type",
            "manifestation_format_detail",
            "manifestation_edition_statement",
            "manifestation_pub_year",
            "manifestation_pub_date",
            "manifestation_flags",
            "manifestation_page_count",
            "manifestation_runtime_minutes",
            "manifestation_region_code",
            "manifestation_status",
            "manifestation_note",
            "manifestation_created_timestamp_ep_k",
            "manifestation_modified_timestamp_ep_k",
            "manifestation_source_created_datestamp_ep_k",
            "manifestation_source_modified_datestamp_ep_k",
            "manifestation_scratch",
        ],
        "items": [
            "item_id",
            "item_manifestation_id",
            "item_flags",
            "item_type",
            "item_location",
            "item_inventory_code",
            "item_original_date",
            "item_original_copyright_date",
            "item_source",
            "item_source_detail",
            "item_source_path",
            "item_source_name",
            "item_acquired_date",
            "item_acquired_price_minor",
            "item_lifecycle_status",
            "item_condition",
            "item_created_timestamp_ep_k",
            "item_modified_timestamp_ep_k",
            "item_source_created_datestamp_ep_k",
            "item_source_modified_datestamp_ep_k",
            "item_scratch",
        ],
        "files": [
            "file_id",
            "file_item_id",
            "file_store_id",
            "file_folder_id",
            "file_storage_key",
            "file_name",
            "file_base_name",
            "file_extension",
            "file_tag",
            "file_auto_name",
            "file_use_auto_name",
            "file_mime_type",
            "file_role",
            "file_media_category",
            "file_class_mask",
            "file_visibility_mask",
            "file_critical",
            "file_size_bytes",
            "file_hash_sha256",
            "file_hash_blake3",
            "file_phash",
            "file_corrupt",
            "file_integrity_status",
            "file_last_seen_timestamp_ep_k",
            "file_last_integrity_check_timestamp_ep_k",
            "file_acquired_timestamp_ep_k",
            "file_source",
            "file_original_name",
            "file_original_path",
            "file_anthology",
            "file_parent",
            "file_conversion_settings",
            "file_processed",
            "file_created_timestamp_ep_k",
            "file_modified_timestamp_ep_k",
            "file_source_created_datestamp_ep_k",
            "file_source_modified_datestamp_ep_k",
            "file_scratch",
        ],
        "agents": [
            "agent_id",
            "agent_type",
            "agent_canonical_name",
            "agent_sort_name",
            "agent_aliases",
            "agent_note",
            "agent_created_timestamp_ep_k",
            "agent_modified_timestamp_ep_k",
            "agent_source_created_datestamp_ep_k",
            "agent_source_modified_datestamp_ep_k",
            "agent_scratch",
        ],
        "labels": [
            "label_id",
            "label_text",
            "label_text_norm",
            "label_description",
            "label_scratch",
            "label_created_timestamp_ep_k",
            "label_modified_timestamp_ep_k",
            "label_source_created_datestamp_ep_k",
            "label_source_modified_datestamp_ep_k",
        ],
    }

    alpha_database_version_required_substrings = (
        "driver_version_",
        "database_version_",
        "md_tools_version_",
        "md_constants_",
        "lx_constants",
    )

    # ------------------------------------------------------------------------------------------------------------------
    #
    # - MAIN TABLE COLUMN HEADINGS

    theo_title_columns = [
        "title_id",
        "title",
        "title_sort",
        "title_phash",
        "title_creator_sort",
        "title_pub_date",
        "title_copyright_date",
        "title_wikipedia",
        "title_fiction_length_category",
        "title_type",
        "title_wordcount",
        "title_source",
        "title_source_path",
        "title_source_name",
        "title_created_datestamp",
        "title_datestamp",
        "title_last_modified",
        "title_scratch",
    ]

    theo_book_columns = [
        "book_id",
        "book_sort",
        "book_flags",
        "book_pubdate",
        "book_copyright_date",
        "book_uuid",
        "book_has_cover",
        "book_has_local_cover",
        "book_last_modified",
        "book_fingerprint",
        "book_paths",
        "book_size",
        "book_rating",
        "book_created_datestamp",
        "book_datestamp",
        "book_scratch",
    ]

    theo_language_columns = [
        "language_id",
        "language",
        "language_code",
        "language_datestamp",
        "language_scratch",
    ]

    theo_series_columns = [
        "series_id",
        "series",
        "series_sort",
        "series_phash",
        "series_over_author",
        "series_parent",
        "series_parent_position",
        "series_tree_id",
        "series_full",
        "series_datestamp",
        "series_scratch",
    ]

    theo_creator_columns = [
        "creator_id",
        "creator",
        "creator_sort",
        "creator_short_name",
        "creator_last_name",
        "creator_phash",
        "creator_legal_name",
        "creator_birth_date",
        "creator_death_date",
        "creator_type",
        "creator_seminal_work",
        "creator_one_person",
        "creator_wikipedia",
        "creator_imdb",
        "creator_link",
        "creator_created_datestamp",
        "creator_datestamp",
        "creator_scratch",
    ]

    theo_languages_columns = [
        "language_id",
        "language",
        "language_code",
        "language_datestamp",
        "language_scratch",
    ]

    theo_publisher_columns = [
        "publisher_id",
        "publisher",
        "publisher_sort",
        "publisher_phash",
        "publisher_wikipedia",
        "publisher_website",
        "publisher_parent",
        "publisher_position",
        "publisher_tree_id",
        "publisher_full",
        "publisher_created_datestamp",
        "publisher_datestamp",
        "publisher_scratch",
    ]

    theo_subject_columns = [
        "subject_id",
        "subject",
        "subject_phash",
        "subject_sort",
        "subject_parent",
        "subject_parent_position",
        "subject_tree_id",
        "subject_full",
        "subject_datestamp",
        "subject_scratch",
    ]

    theo_tag_columns = ["tag_id", "tag", "tag_phash", "tag_datestamp", "tag_scratch"]

    #
    # ------------------------------------------------------------------------------------------------------------------
    # ------------------------------------------------------------------------------------------------------------------
    #
    # - STABLE COLUMNS - columns which do not change when the test databases are regenerated

    theo_stable_titles_columns = [
        "title_id",
        "title",
        "title_sort",
        "title_phash",
        "title_creator_sort",
        "title_pub_date",
        "title_copyright_date",
        "title_wikipedia",
        "title_fiction_length_category",
        "title_type",
        "title_wordcount",
        "title_source",
        "title_source_path",
        "title_source_name",
    ]

    theo_stable_books_columns = [
        "book_id",
        "book_sort",
        "book_flags",
        "book_pubdate",
        "book_copyright_date",
        "book_uuid",
        "book_has_cover",
        "book_has_local_cover",
        "book_fingerprint",
        "book_paths",
        "book_size",
        "book_rating",
    ]

    theo_stable_languages_columns = [
        "language_id",
        "language",
        "language_code",
    ]

    theo_stable_series_columns = [
        "series_id",
        "series",
        "series_sort",
        "series_phash",
        "series_over_author",
        "series_parent",
        "series_parent_position",
        "series_tree_id",
        "series_full",
    ]

    theo_stable_creator_columns = [
        "creator_id",
        "creator",
        "creator_sort",
        "creator_short_name",
        "creator_last_name",
        "creator_phash",
        "creator_legal_name",
        "creator_birth_date",
        "creator_death_date",
        "creator_type",
        "creator_seminal_work",
        "creator_one_person",
        "creator_wikipedia",
        "creator_imdb",
        "creator_link",
    ]

    theo_stable_publisher_columns = [
        "publisher_id",
        "publisher",
        "publisher_sort",
        "publisher_phash",
        "publisher_wikipedia",
        "publisher_website",
        "publisher_parent",
        "publisher_position",
        "publisher_tree_id",
        "publisher_full",
    ]

    # Todo: THe proper way to test trhese is to test that they are stabler after a regen of the test db
    theo_stable_title_title_columns = [
        "title_title_intralink_id",
        "title_title_intralink_primary_id",
        "title_title_intralink_secondary_id",
        "title_title_intralink_type",
    ]

    theo_stable_identifier_columns = [
        "identifier_id",
        "identifier",
        "identifier_type",
    ]

    theo_stable_tag_columns = ["tag_id", "tag", "tag_phash"]

    theo_stable_rating_columns = [
        "rating_id",
        "rating",
        "rating_source",
    ]

    theo_stable_last_read_position_columns = [
        "id",
        "book",
        "format",
        "user",
        "device",
        "cfi",
        "epoch",
        "pos_frac",
    ]

    theo_stable_series_title_link_columns = [
        "series_title_link_id",
        "series_title_link_series_id",
        "series_title_link_title_id",
        "series_title_link_priority",
        "series_title_link_index",
    ]

    theo_stable_comment_title_link_columns = [
        "comment_title_link_id",
        "comment_title_link_comment_id",
        "comment_title_link_title_id",
        "comment_title_link_priority",
        "comment_title_link_type",
    ]

    theo_stable_publisher_title_link_columns = [
        "publisher_title_link_id",
        "publisher_title_link_publisher_id",
        "publisher_title_link_title_id",
        "publisher_title_link_priority",
    ]

    theo_stable_tag_title_link_columns = [
        "tag_title_link_id",
        "tag_title_link_tag_id",
        "tag_title_link_title_id",
    ]

    theo_stable_comments_columns = [
        "comment_id",
        "comment",
    ]

    #
    # ------------------------------------------------------------------------------------------------------------------

    theo_meta_row_keys = {
        "id",
        "title",
        "title_tags",
        "rating",
        "isbn",
        "uuid",
        "pubdate",
        "synopsis_id",
        "series",
        "series_tags",
        "creator_tags",
        "main_tags",
        "size",
        "wikipedia",
        "comments",
        "note",
        "max_size",
        "has_cover",
        "publisher_id",
        "sort",
        "publishers",
        "note_id",
        "tags",
        "timestamp",
        "comment_id",
        "series_id",
        "last_modified",
        "authors",
        "genre",
        "path",
        "min_rating",
        "author_ids",
        "publisher",
        "series_index",
        "max_rating",
        "language",
        "lccn",
        "type",
        "author_sort",
        "synopsis",
        "flags",
        "formats",
        "genre_id",
    }

    theo_title_column_headings = {
        "title_scratch",
        "title_phash",
        "title_datestamp",
        "title_pub_date",
        "title_fiction_length_category",
        "title_id",
        "title_sort",
        "title_created_datestamp",
        "title_copyright_date",
        "title_wikipedia",
        "title_wordcount",
        "title_source",
        "title_source_name",
        "title",
        "title_last_modified",
        "title_type",
        "title_creator_sort",
        "title_source_path",
    }

    theo_db_main_tables = {
        "folders",
        "files",
        "genres",
        "custom_columns",
        "folder_stores",
        "devices",
        "publishers",
        "series",
        "notes",
        "tags",
        "comments",
        "languages",
        "last_read_positions",
        "books",
        "covers",
        "synopses",
        "titles",
        "feeds",
        "creators",
        "subjects",
        "identifiers",
    }

    theo_db_intralinks_table = {
        "publisher_publisher_intralinks",
        "title_title_intralinks",
        "file_file_intralinks",
        "tag_tag_intralinks",
        "creator_creator_intralinks",
        "identifier_identifier_intralinks",
        "cover_cover_intralinks",
        "folder_store_folder_store_intralinks",
    }

    theo_db_interlink_tables = {
        "creator_title_links",
        "rating_title_links",
        "comment_title_links",
        "language_title_links",
        "book_file_links",
        "file_identifier_links",
        "cover_creator_links",
        "synopsis_title_links",
        "note_series_links",
        "publisher_title_links",
        "creator_series_links",
        "device_note_links",
        "folder_store_note_links",
        "genre_title_links",
        "series_tag_links",
        "book_folder_links",
        "creator_folder_links",
        "note_title_links",
        "folder_series_links",
        "tag_title_links",
        "identifier_title_links",
        "series_title_links",
        "comment_creator_links",
        "genre_series_links",
        "subject_title_links",
        "cover_series_links",
        "creator_tag_links",
        "file_folder_links",
        "note_publisher_links",
        "file_publisher_links",
        "file_language_links",
        "comment_series_links",
        "device_file_links",
        "creator_language_links",
        "creator_note_links",
        "series_synopsis_links",
        "book_cover_links",
        "creator_synopsis_links",
    }

    # Todo: ratings is ABSOLUTELY NOT a helper table!
    theo_db_helper_tables = {
        "books_plugin_data",
        "compressed_files",
        "conversion_options",
        "database_metadata",
        "hashes",
        "library_id",
        "metadata_dirtied_books",
        "new_books",
        "preferences",
        "ratings",
        "database_version",
    }

    theo_tables_and_columns = {
        "creator_title_links": [
            "creator_title_link_id",
            "creator_title_link_creator_id",
            "creator_title_link_title_id",
            "creator_title_link_priority",
            "creator_title_link_type",
            "creator_title_link_datestamp",
            "creator_title_link_scratch",
        ],
        "tag_tag_intralinks": [
            "tag_tag_intralink_id",
            "tag_tag_intralink_primary_id",
            "tag_tag_intralink_secondary_id",
            "tag_tag_intralink_type",
            "tag_tag_intralink_datestamp",
            "tag_tag_intralink_scratch",
        ],
        "language_title_links": [
            "language_title_link_id",
            "language_title_link_language_id",
            "language_title_link_title_id",
            "language_title_link_priority",
            "language_title_link_type",
            "language_title_link_datestamp",
            "language_title_link_scratch",
        ],
        "creator_creator_intralinks": [
            "creator_creator_intralink_id",
            "creator_creator_intralink_primary_id",
            "creator_creator_intralink_secondary_id",
            "creator_creator_intralink_type",
            "creator_creator_intralink_datestamp",
            "creator_creator_intralink_scratch",
        ],
        "new_books": [
            "new_book_id",
            "new_book_name",
            "new_book_extension",
            "new_book_path",
            "new_book_hash_1",
            "new_book_hash_2",
            "new_book_size",
            "new_book_group_id",
            "new_book_cached",
            "new_book_cache_attempted",
            "new_book_datestamp",
            "new_book_scratch",
        ],
        "identifier_title_links": [
            "identifier_title_link_id",
            "identifier_title_link_identifier_id",
            "identifier_title_link_title_id",
            "identifier_title_link_priority",
            "identifier_title_link_type",
            "identifier_title_link_datestamp",
            "identifier_title_link_scratch",
        ],
        "allowed_types__publishers_publishers_intralinks": [
            "allowed_types__publishers_publishers_intralink_id",
            "allowed_types__publishers_publishers_intralink_type",
            "allowed_types__publishers_publishers_intralink_datestamp",
            "allowed_types__publishers_publishers_intralink_scratch",
        ],
        "allowed_types__creators_creators_intralinks": [
            "allowed_types__creators_creators_intralink_id",
            "allowed_types__creators_creators_intralink_type",
            "allowed_types__creators_creators_intralink_datestamp",
            "allowed_types__creators_creators_intralink_scratch",
        ],
        "allowed_types__note_title_links": [
            "allowed_types__note_title_link_id",
            "allowed_types__note_title_link_type",
            "allowed_types__note_title_link_datestamp",
            "allowed_types__note_title_link_scratch",
        ],
        "compressed_files": [
            "compressed_file_id",
            "compressed_file_name",
            "compressed_file_extension",
            "compressed_file_path",
            "compressed_file_hash_1",
            "compressed_file_hash_2",
            "compressed_file_size",
            "compressed_file_group_id",
            "compressed_file_folder",
            "compressed_file_cached",
            "compressed_file_cache_attempted",
            "compressed_file_datestamp",
            "compressed_file_scratch",
        ],
        "note_series_links": [
            "note_series_link_id",
            "note_series_link_note_id",
            "note_series_link_series_id",
            "note_series_link_priority",
            "note_series_link_datestamp",
            "note_series_link_scratch",
        ],
        "languages": [
            "language_id",
            "language",
            "language_code",
            "language_datestamp",
            "language_scratch",
        ],
        "database_version": [
            "database_version_id",
            "database_version_version",
            "database_version_datestamp",
        ],
        "allowed_types__identifier_title_links": [
            "allowed_types__identifier_title_link_id",
            "allowed_types__identifier_title_link_type",
            "allowed_types__identifier_title_link_datestamp",
            "allowed_types__identifier_title_link_scratch",
        ],
        "file_file_intralinks": [
            "file_file_intralink_id",
            "file_file_intralink_primary_id",
            "file_file_intralink_secondary_id",
            "file_file_intralink_type",
            "file_file_intralink_datestamp",
            "file_file_intralink_scratch",
        ],
        "file_folder_links": [
            "file_folder_link_id",
            "file_folder_link_file_id",
            "file_folder_link_folder_id",
            "file_folder_link_datestamp",
            "file_folder_link_scratch",
        ],
        "title_title_intralinks": [
            "title_title_intralink_id",
            "title_title_intralink_primary_id",
            "title_title_intralink_secondary_id",
            "title_title_intralink_type",
            "title_title_intralink_datestamp",
            "title_title_intralink_scratch",
        ],
        "notes": ["note_id", "note", "note_datestamp", "note_scratch"],
        "metadata_dirtied_books": [
            "metadata_dirtied_book_id",
            "metadata_dirtied_book",
        ],
        "conversion_options": [
            "conversion_option_id",
            "conversion_option_format",
            "conversion_option_book",
            "conversion_option_data",
            "conversion_option_datestamp",
        ],
        "allowed_types__files_files_intralinks": [
            "allowed_types__files_files_intralink_id",
            "allowed_types__files_files_intralink_type",
            "allowed_types__files_files_intralink_datestamp",
            "allowed_types__files_files_intralink_scratch",
        ],
        "feeds": [
            "feed_id",
            "feed_title",
            "feed_script",
            "feed_created_datestamp",
            "feed_datestamp",
            "feed_scratch",
        ],
        "library_id": ["library_id", "library_id_uuid", "library_id_datestamp"],
        "publishers": [
            "publisher_id",
            "publisher",
            "publisher_sort",
            "publisher_phash",
            "publisher_wikipedia",
            "publisher_website",
            "publisher_parent",
            "publisher_position",
            "publisher_tree_id",
            "publisher_full",
            "publisher_created_datestamp",
            "publisher_datestamp",
            "publisher_scratch",
        ],
        "series": [
            "series_id",
            "series",
            "series_sort",
            "series_phash",
            "series_over_author",
            "series_parent",
            "series_parent_position",
            "series_tree_id",
            "series_full",
            "series_datestamp",
            "series_scratch",
        ],
        "allowed_types__folder_stores_folder_stores_intralinks": [
            "allowed_types__folder_stores_folder_stores_intralink_id",
            "allowed_types__folder_stores_folder_stores_intralink_type",
            "allowed_types__folder_stores_folder_stores_intralink_datestamp",
            "allowed_types__folder_stores_folder_stores_intralink_scratch",
        ],
        "books": [
            "book_id",
            "book_sort",
            "book_flags",
            "book_pubdate",
            "book_copyright_date",
            "book_uuid",
            "book_has_cover",
            "book_has_local_cover",
            "book_last_modified",
            "book_fingerprint",
            "book_paths",
            "book_size",
            "book_rating",
            "book_created_datestamp",
            "book_datestamp",
            "book_scratch",
        ],
        "devices": [
            "device_id",
            "device_type",
            "device_created_datestamp",
            "device_datestamp",
            "device_scratch",
        ],
        "preferences": [
            "preference_id",
            "preference_key",
            "preference_value",
            "preference_value_type",
            "preference_parent_LiuXin_instance",
            "preference_datestamp",
            "preference_scratch",
        ],
        "publisher_title_links": [
            "publisher_title_link_id",
            "publisher_title_link_publisher_id",
            "publisher_title_link_title_id",
            "publisher_title_link_priority",
            "publisher_title_link_datestamp",
            "publisher_title_link_scratch",
        ],
        "comments": [
            "comment_id",
            "comment",
            "comment_datestamp",
            "comment_scratch",
        ],
        "book_folder_links": [
            "book_folder_link_id",
            "book_folder_link_book_id",
            "book_folder_link_folder_id",
            "book_folder_link_priority",
            "book_folder_link_datestamp",
            "book_folder_link_scratch",
        ],
        "series_synopsis_links": [
            "series_synopsis_link_id",
            "series_synopsis_link_series_id",
            "series_synopsis_link_synopsis_id",
            "series_synopsis_link_priority",
            "series_synopsis_link_datestamp",
            "series_synopsis_link_scratch",
        ],
        "allowed_types__creator_series_links": [
            "allowed_types__creator_series_link_id",
            "allowed_types__creator_series_link_type",
            "allowed_types__creator_series_link_datestamp",
            "allowed_types__creator_series_link_scratch",
        ],
        "books_plugin_data": [
            "book_plugin_data_id",
            "book_plugin_data_book",
            "book_plugin_data_name",
            "book_plugin_data_val",
            "book_plugin_created_datestamp",
            "book_plugin_datestamp",
            "book_plugin_scratch",
        ],
        "tags": ["tag_id", "tag", "tag_phash", "tag_datestamp", "tag_scratch"],
        "synopsis_title_links": [
            "synopsis_title_link_id",
            "synopsis_title_link_synopsis_id",
            "synopsis_title_link_title_id",
            "synopsis_title_link_priority",
            "synopsis_title_link_datestamp",
            "synopsis_title_link_scratch",
        ],
        "comment_creator_links": [
            "comment_creator_link_id",
            "comment_creator_link_comment_id",
            "comment_creator_link_creator_id",
            "comment_creator_link_priority",
            "comment_creator_link_type",
            "comment_creator_link_datestamp",
            "comment_creator_link_scratch",
        ],
        "synopses": [
            "synopsis_id",
            "synopsis",
            "synopsis_datestamp",
            "synopsis_scratch",
        ],
        "database_metadata": [
            "database_metadata_id",
            "database_metadata_unique_id",
            "database_metadata_parent_LiuXin_instance",
            "database_metadata_db_name",
            "database_metadata_datestamp",
            "database_metadata_scratch",
        ],
        "allowed_types__comment_series_links": [
            "allowed_types__comment_series_link_id",
            "allowed_types__comment_series_link_type",
            "allowed_types__comment_series_link_datestamp",
            "allowed_types__comment_series_link_scratch",
        ],
        "folder_stores": [
            "folder_store_id",
            "folder_store",
            "folder_store_identifier",
            "folder_store_path",
            "folder_store_path_os_type",
            "folder_store_created",
            "folder_store_media_types",
            "folder_store_forbidden_print",
            "folder_store_preferred_print",
            "folder_store_cache",
            "folder_store_storage",
            "folder_store_cf_expansion",
            "folder_store_cache_priority",
            "folder_store_max_path_length",
            "folder_store_user_name",
            "folder_store_password",
            "folder_store_type",
            "folder_store_marker_name",
            "folder_store_marker_text",
            "folder_store_marker_path",
            "folder_store_marker_path_os_type",
            "folder_store_dedicated_drive",
            "folder_store_max_size",
            "folder_store_found",
            "folder_store_readable",
            "folder_store_writeable",
            "folder_store_size",
            "folder_store_free_size",
            "folder_store_creation_date",
            "folder_store_created_datestamp",
            "folder_store_datestamp",
            "folder_store_scratch",
        ],
        "creator_language_links": [
            "creator_language_link_id",
            "creator_language_link_creator_id",
            "creator_language_link_language_id",
            "creator_language_link_datestamp",
            "creator_language_link_scratch",
        ],
        "identifier_identifier_intralinks": [
            "identifier_identifier_intralink_id",
            "identifier_identifier_intralink_primary_id",
            "identifier_identifier_intralink_secondary_id",
            "identifier_identifier_intralink_type",
            "identifier_identifier_intralink_datestamp",
            "identifier_identifier_intralink_scratch",
        ],
        "creator_note_links": [
            "creator_note_link_id",
            "creator_note_link_creator_id",
            "creator_note_link_note_id",
            "creator_note_link_priority",
            "creator_note_link_type",
            "creator_note_link_datestamp",
            "creator_note_link_scratch",
        ],
        "allowed_types__language_title_links": [
            "allowed_types__language_title_link_id",
            "allowed_types__language_title_link_type",
            "allowed_types__language_title_link_datestamp",
            "allowed_types__language_title_link_scratch",
        ],
        "publisher_publisher_intralinks": [
            "publisher_publisher_intralink_id",
            "publisher_publisher_intralink_primary_id",
            "publisher_publisher_intralink_secondary_id",
            "publisher_publisher_intralink_type",
            "publisher_publisher_intralink_datestamp",
            "publisher_publisher_intralink_scratch",
        ],
        "hashes": ["hash_id", "hash"],
        "custom_columns": [
            "custom_column_id",
            "custom_column_mark_for_delete",
            "custom_column_in_table",
            "custom_column_label",
            "custom_column_name",
            "custom_column_datatype",
            "custom_column_db_datatype",
            "custom_column_editable",
            "custom_column_display",
            "custom_column_normalized",
            "custom_column_is_multiple",
            "custom_column_ordered",
            "custom_column_datestamp",
            "custom_column_scratch",
        ],
        "folder_store_note_links": [
            "folder_store_note_link_id",
            "folder_store_note_link_folder_store_id",
            "folder_store_note_link_note_id",
            "folder_store_note_link_priority",
            "folder_store_note_link_datestamp",
            "folder_store_note_link_scratch",
        ],
        "genre_title_links": [
            "genre_title_link_id",
            "genre_title_link_genre_id",
            "genre_title_link_title_id",
            "genre_title_link_priority",
            "genre_title_link_datestamp",
            "genre_title_link_scratch",
        ],
        "comment_title_links": [
            "comment_title_link_id",
            "comment_title_link_comment_id",
            "comment_title_link_title_id",
            "comment_title_link_priority",
            "comment_title_link_type",
            "comment_title_link_datestamp",
            "comment_title_link_scratch",
        ],
        "series_tag_links": [
            "series_tag_link_id",
            "series_tag_link_series_id",
            "series_tag_link_tag_id",
            "series_tag_link_datestamp",
            "series_tag_link_scratch",
        ],
        "allowed_types__file_identifier_links": [
            "allowed_types__file_identifier_link_id",
            "allowed_types__file_identifier_link_type",
            "allowed_types__file_identifier_link_datestamp",
            "allowed_types__file_identifier_link_scratch",
        ],
        "folder_store_folder_store_intralinks": [
            "folder_store_folder_store_intralink_id",
            "folder_store_folder_store_intralink_primary_id",
            "folder_store_folder_store_intralink_secondary_id",
            "folder_store_folder_store_intralink_type",
            "folder_store_folder_store_intralink_datestamp",
            "folder_store_folder_store_intralink_scratch",
        ],
        "files": [
            "file_id",
            "file_name",
            "file_base_name",
            "file_tag",
            "file_extension",
            "file_path",
            "file_auto_name",
            "file_use_auto_name",
            "file_size",
            "file_hash",
            "file_new_hash",
            "file_corrupt",
            "file_base_folder",
            "file_acquired_timestamp",
            "file_source",
            "file_original_name",
            "file_original_path",
            "file_phash",
            "file_anthology",
            "file_critical",
            "file_parent",
            "file_conversion_settings",
            "file_processed",
            "file_created_datestamp",
            "file_datestamp",
            "file_scratch",
        ],
        "creator_folder_links": [
            "creator_folder_link_id",
            "creator_folder_link_creator_id",
            "creator_folder_link_folder_id",
            "creator_folder_link_priority",
            "creator_folder_link_datestamp",
            "creator_folder_link_scratch",
        ],
        "allowed_types__rating_title_links": [
            "allowed_types__rating_title_link_id",
            "allowed_types__rating_title_link_type",
            "allowed_types__rating_title_link_datestamp",
            "allowed_types__rating_title_link_scratch",
        ],
        "note_title_links": [
            "note_title_link_id",
            "note_title_link_note_id",
            "note_title_link_title_id",
            "note_title_link_priority",
            "note_title_link_type",
            "note_title_link_datestamp",
            "note_title_link_scratch",
        ],
        "allowed_types__comment_creator_links": [
            "allowed_types__comment_creator_link_id",
            "allowed_types__comment_creator_link_type",
            "allowed_types__comment_creator_link_datestamp",
            "allowed_types__comment_creator_link_scratch",
        ],
        "tag_title_links": [
            "tag_title_link_id",
            "tag_title_link_tag_id",
            "tag_title_link_title_id",
            "tag_title_link_datestamp",
            "tag_title_link_scratch",
        ],
        "creator_tag_links": [
            "creator_tag_link_id",
            "creator_tag_link_creator_id",
            "creator_tag_link_tag_id",
            "creator_tag_link_datestamp",
            "creator_tag_link_scratch",
        ],
        "note_publisher_links": [
            "note_publisher_link_id",
            "note_publisher_link_note_id",
            "note_publisher_link_publisher_id",
            "note_publisher_link_priority",
            "note_publisher_link_datestamp",
            "note_publisher_link_scratch",
        ],
        "file_publisher_links": [
            "file_publisher_link_id",
            "file_publisher_link_file_id",
            "file_publisher_link_publisher_id",
            "file_publisher_link_datestamp",
            "file_publisher_link_scratch",
        ],
        "file_language_links": [
            "file_language_link_id",
            "file_language_link_file_id",
            "file_language_link_language_id",
            "file_language_link_datestamp",
            "file_language_link_scratch",
        ],
        "titles": [
            "title_id",
            "title",
            "title_sort",
            "title_phash",
            "title_creator_sort",
            "title_pub_date",
            "title_copyright_date",
            "title_wikipedia",
            "title_fiction_length_category",
            "title_type",
            "title_wordcount",
            "title_source",
            "title_source_path",
            "title_source_name",
            "title_created_datestamp",
            "title_datestamp",
            "title_last_modified",
            "title_scratch",
        ],
        "allowed_types__titles_titles_intralinks": [
            "allowed_types__titles_titles_intralink_id",
            "allowed_types__titles_titles_intralink_type",
            "allowed_types__titles_titles_intralink_datestamp",
            "allowed_types__titles_titles_intralink_scratch",
        ],
        "allowed_types__creator_note_links": [
            "allowed_types__creator_note_link_id",
            "allowed_types__creator_note_link_type",
            "allowed_types__creator_note_link_datestamp",
            "allowed_types__creator_note_link_scratch",
        ],
        "creator_synopsis_links": [
            "creator_synopsis_link_id",
            "creator_synopsis_link_creator_id",
            "creator_synopsis_link_synopsis_id",
            "creator_synopsis_link_datestamp",
            "creator_synopsis_link_scratch",
        ],
        "allowed_types__tags_tags_intralinks": [
            "allowed_types__tags_tags_intralink_id",
            "allowed_types__tags_tags_intralink_type",
            "allowed_types__tags_tags_intralink_datestamp",
            "allowed_types__tags_tags_intralink_scratch",
        ],
        "rating_title_links": [
            "rating_title_link_id",
            "rating_title_link_rating_id",
            "rating_title_link_title_id",
            "rating_title_link_type",
            "rating_title_link_datestamp",
            "rating_title_link_scratch",
        ],
        "allowed_types__covers_covers_intralinks": [
            "allowed_types__covers_covers_intralink_id",
            "allowed_types__covers_covers_intralink_type",
            "allowed_types__covers_covers_intralink_datestamp",
            "allowed_types__covers_covers_intralink_scratch",
        ],
        "covers": [
            "cover_id",
            "cover_name",
            "cover_extension",
            "cover_path",
            "cover_use_auto_name",
            "cover_hash",
            "cover_new_hash",
            "cover_corrupt",
            "cover_original_path",
            "cover_local",
            "cover_base_folder",
            "cover_created_datestamp",
            "cover_datestamp",
            "cover_scratch",
        ],
        "book_file_links": [
            "book_file_link_id",
            "book_file_link_book_id",
            "book_file_link_file_id",
            "book_file_link_priority",
            "book_file_link_datestamp",
            "book_file_link_scratch",
        ],
        "file_identifier_links": [
            "file_identifier_link_id",
            "file_identifier_link_file_id",
            "file_identifier_link_identifier_id",
            "file_identifier_link_priority",
            "file_identifier_link_type",
            "file_identifier_link_datestamp",
            "file_identifier_link_scratch",
        ],
        "cover_creator_links": [
            "cover_creator_link_id",
            "cover_creator_link_cover_id",
            "cover_creator_link_creator_id",
            "cover_creator_link_priority",
            "cover_creator_link_datestamp",
            "cover_creator_link_scratch",
        ],
        "ratings": [
            "rating_id",
            "rating",
            "rating_source",
            "rating_datestamp",
            "rating_scratch",
        ],
        "genres": [
            "genre_id",
            "genre",
            "genre_sort",
            "genre_phash",
            "genre_parent",
            "genre_position",
            "genre_tree_id",
            "genre_full",
            "genre_datestamp",
            "genre_scratch",
        ],
        "creator_series_links": [
            "creator_series_link_id",
            "creator_series_link_creator_id",
            "creator_series_link_series_id",
            "creator_series_link_type",
            "creator_series_link_datestamp",
            "creator_series_link_scratch",
        ],
        "last_read_positions": [
            "id",
            "book",
            "format",
            "user",
            "device",
            "cfi",
            "epoch",
            "pos_frac",
        ],
        "device_note_links": [
            "device_note_link_id",
            "device_note_link_device_id",
            "device_note_link_note_id",
            "device_note_link_priority",
            "device_note_link_datestamp",
            "device_note_link_scratch",
        ],
        "subjects": [
            "subject_id",
            "subject",
            "subject_phash",
            "subject_sort",
            "subject_parent",
            "subject_parent_position",
            "subject_tree_id",
            "subject_full",
            "subject_datestamp",
            "subject_scratch",
        ],
        "allowed_types__creator_title_links": [
            "allowed_types__creator_title_link_id",
            "allowed_types__creator_title_link_type",
            "allowed_types__creator_title_link_datestamp",
            "allowed_types__creator_title_link_scratch",
        ],
        "folders": [
            "folder_id",
            "folder_name",
            "folder_tag",
            "folder_original_name",
            "folder_auto_name",
            "folder_use_auto_name",
            "folder_path",
            "folder_auto_position",
            "folder_found",
            "folder_folder_store_id",
            "folder_parent",
            "folder_depth",
            "folder_size",
            "folder_hash",
            "folder_types",
            "folder_created_datestamp",
            "folder_datestamp",
            "folder_scratch",
        ],
        "allowed_types__device_file_links": [
            "allowed_types__device_file_link_id",
            "allowed_types__device_file_link_type",
            "allowed_types__device_file_link_datestamp",
            "allowed_types__device_file_link_scratch",
        ],
        "allowed_types__book_cover_links": [
            "allowed_types__book_cover_link_id",
            "allowed_types__book_cover_link_type",
            "allowed_types__book_cover_link_datestamp",
            "allowed_types__book_cover_link_scratch",
        ],
        "folder_series_links": [
            "folder_series_link_id",
            "folder_series_link_folder_id",
            "folder_series_link_series_id",
            "folder_series_link_priority",
            "folder_series_link_datestamp",
            "folder_series_link_scratch",
        ],
        "series_title_links": [
            "series_title_link_id",
            "series_title_link_series_id",
            "series_title_link_title_id",
            "series_title_link_priority",
            "series_title_link_index",
            "series_title_link_datestamp",
            "series_title_link_scratch",
        ],
        "cover_cover_intralinks": [
            "cover_cover_intralink_id",
            "cover_cover_intralink_primary_id",
            "cover_cover_intralink_secondary_id",
            "cover_cover_intralink_type",
            "cover_cover_intralink_datestamp",
            "cover_cover_intralink_scratch",
        ],
        "genre_series_links": [
            "genre_series_link_id",
            "genre_series_link_genre_id",
            "genre_series_link_series_id",
            "genre_series_link_priority",
            "genre_series_link_datestamp",
            "genre_series_link_scratch",
        ],
        "subject_title_links": [
            "subject_title_link_id",
            "subject_title_link_subject_id",
            "subject_title_link_title_id",
            "subject_title_link_priority",
            "subject_title_link_datestamp",
            "subject_title_link_scratch",
        ],
        "cover_series_links": [
            "cover_series_link_id",
            "cover_series_link_cover_id",
            "cover_series_link_series_id",
            "cover_series_link_priority",
            "cover_series_link_datestamp",
            "cover_series_link_scratch",
        ],
        "identifiers": [
            "identifier_id",
            "identifier",
            "identifier_type",
            "identifier_datestamp",
            "identifier_scratch",
        ],
        "comment_series_links": [
            "comment_series_link_id",
            "comment_series_link_comment_id",
            "comment_series_link_series_id",
            "comment_series_link_priority",
            "comment_series_link_type",
            "comment_series_link_datestamp",
            "comment_series_link_scratch",
        ],
        "allowed_types__comment_title_links": [
            "allowed_types__comment_title_link_id",
            "allowed_types__comment_title_link_type",
            "allowed_types__comment_title_link_datestamp",
            "allowed_types__comment_title_link_scratch",
        ],
        "allowed_types__identifiers_identifiers_intralinks": [
            "allowed_types__identifiers_identifiers_intralink_id",
            "allowed_types__identifiers_identifiers_intralink_type",
            "allowed_types__identifiers_identifiers_intralink_datestamp",
            "allowed_types__identifiers_identifiers_intralink_scratch",
        ],
        "device_file_links": [
            "device_file_link_id",
            "device_file_link_device_id",
            "device_file_link_file_id",
            "device_file_link_type",
            "device_file_link_datestamp",
            "device_file_link_scratch",
        ],
        "creators": [
            "creator_id",
            "creator",
            "creator_sort",
            "creator_short_name",
            "creator_last_name",
            "creator_phash",
            "creator_legal_name",
            "creator_birth_date",
            "creator_death_date",
            "creator_type",
            "creator_seminal_work",
            "creator_one_person",
            "creator_wikipedia",
            "creator_imdb",
            "creator_link",
            "creator_created_datestamp",
            "creator_datestamp",
            "creator_scratch",
        ],
        "book_cover_links": [
            "book_cover_link_id",
            "book_cover_link_book_id",
            "book_cover_link_cover_id",
            "book_cover_link_priority",
            "book_cover_link_type",
            "book_cover_link_datestamp",
            "book_cover_link_scratch",
        ],
    }
    all_tables_and_column_headings = theo_tables_and_columns

    all_known_tables = sorted(theo_tables_and_columns.keys())

    db_tables = all_known_tables
    db_tables_set = set([_ for _ in db_tables])

    all_sorted_tables = sorted(all_known_tables)

    existing_triggers = [
        "update_callback_on_titles",
        "block_insert_on_database_version_table",
        "block_update_on_database_version_table",
        "block_delete_on_database_version_table",
    ]
