from .common_db_properties import (
    CommonDBProperties,
)


class TestDB6Properties(CommonDBProperties):

    alpha_focus_row_counts = {
        "database_version": 1,
        "works": 20,
        "series": 1,
        "expressions": 20,
        "manifestations": 20,
        "items": 20,
        "files": 0,
        "agents": 1,
        "labels": 0,
    }

    theo_tables_and_columns = {
        "creator_title_links": [
            "creator_title_link_id",
            "creator_title_link_creator_id",
            "creator_title_link_title_id",
            "creator_title_link_priority",
            "creator_title_link_type",
            "creator_title_link_datestamp",
            "creator_title_link_scratch",
        ],
        "tag_tag_intralinks": [
            "tag_tag_intralink_id",
            "tag_tag_intralink_primary_id",
            "tag_tag_intralink_secondary_id",
            "tag_tag_intralink_type",
            "tag_tag_intralink_datestamp",
            "tag_tag_intralink_scratch",
        ],
        "language_title_links": [
            "language_title_link_id",
            "language_title_link_language_id",
            "language_title_link_title_id",
            "language_title_link_priority",
            "language_title_link_type",
            "language_title_link_datestamp",
            "language_title_link_scratch",
        ],
        "creator_creator_intralinks": [
            "creator_creator_intralink_id",
            "creator_creator_intralink_primary_id",
            "creator_creator_intralink_secondary_id",
            "creator_creator_intralink_type",
            "creator_creator_intralink_datestamp",
            "creator_creator_intralink_scratch",
        ],
        "new_books": [
            "new_book_id",
            "new_book_name",
            "new_book_extension",
            "new_book_path",
            "new_book_hash_1",
            "new_book_hash_2",
            "new_book_size",
            "new_book_group_id",
            "new_book_cached",
            "new_book_cache_attempted",
            "new_book_datestamp",
            "new_book_scratch",
        ],
        "identifier_title_links": [
            "identifier_title_link_id",
            "identifier_title_link_identifier_id",
            "identifier_title_link_title_id",
            "identifier_title_link_priority",
            "identifier_title_link_type",
            "identifier_title_link_datestamp",
            "identifier_title_link_scratch",
        ],
        "allowed_types__publishers_publishers_intralinks": [
            "allowed_types__publishers_publishers_intralink_id",
            "allowed_types__publishers_publishers_intralink_type",
            "allowed_types__publishers_publishers_intralink_datestamp",
            "allowed_types__publishers_publishers_intralink_scratch",
        ],
        "allowed_types__creators_creators_intralinks": [
            "allowed_types__creators_creators_intralink_id",
            "allowed_types__creators_creators_intralink_type",
            "allowed_types__creators_creators_intralink_datestamp",
            "allowed_types__creators_creators_intralink_scratch",
        ],
        "allowed_types__note_title_links": [
            "allowed_types__note_title_link_id",
            "allowed_types__note_title_link_type",
            "allowed_types__note_title_link_datestamp",
            "allowed_types__note_title_link_scratch",
        ],
        "compressed_files": [
            "compressed_file_id",
            "compressed_file_name",
            "compressed_file_extension",
            "compressed_file_path",
            "compressed_file_hash_1",
            "compressed_file_hash_2",
            "compressed_file_size",
            "compressed_file_group_id",
            "compressed_file_folder",
            "compressed_file_cached",
            "compressed_file_cache_attempted",
            "compressed_file_datestamp",
            "compressed_file_scratch",
        ],
        "note_series_links": [
            "note_series_link_id",
            "note_series_link_note_id",
            "note_series_link_series_id",
            "note_series_link_priority",
            "note_series_link_datestamp",
            "note_series_link_scratch",
        ],
        "languages": [
            "language_id",
            "language",
            "language_code",
            "language_datestamp",
            "language_scratch",
        ],
        "database_version": [
            "database_version_id",
            "database_version_version",
            "database_version_datestamp",
        ],
        "books_custom_column_1_link": [
            "books_custom_column_1_link_id",
            "books_custom_column_1_link_book",
            "books_custom_column_1_link_value",
        ],
        "allowed_types__identifier_title_links": [
            "allowed_types__identifier_title_link_id",
            "allowed_types__identifier_title_link_type",
            "allowed_types__identifier_title_link_datestamp",
            "allowed_types__identifier_title_link_scratch",
        ],
        "file_file_intralinks": [
            "file_file_intralink_id",
            "file_file_intralink_primary_id",
            "file_file_intralink_secondary_id",
            "file_file_intralink_type",
            "file_file_intralink_datestamp",
            "file_file_intralink_scratch",
        ],
        "books_custom_column_4_link": [
            "books_custom_column_4_link_id",
            "books_custom_column_4_link_book",
            "books_custom_column_4_link_value",
        ],
        "file_folder_links": [
            "file_folder_link_id",
            "file_folder_link_file_id",
            "file_folder_link_folder_id",
            "file_folder_link_datestamp",
            "file_folder_link_scratch",
        ],
        "title_title_intralinks": [
            "title_title_intralink_id",
            "title_title_intralink_primary_id",
            "title_title_intralink_secondary_id",
            "title_title_intralink_type",
            "title_title_intralink_datestamp",
            "title_title_intralink_scratch",
        ],
        "notes": ["note_id", "note", "note_datestamp", "note_scratch"],
        "metadata_dirtied_books": [
            "metadata_dirtied_book_id",
            "metadata_dirtied_book",
        ],
        "conversion_options": [
            "conversion_option_id",
            "conversion_option_format",
            "conversion_option_book",
            "conversion_option_data",
            "conversion_option_datestamp",
        ],
        "allowed_types__files_files_intralinks": [
            "allowed_types__files_files_intralink_id",
            "allowed_types__files_files_intralink_type",
            "allowed_types__files_files_intralink_datestamp",
            "allowed_types__files_files_intralink_scratch",
        ],
        "feeds": [
            "feed_id",
            "feed_title",
            "feed_script",
            "feed_created_datestamp",
            "feed_datestamp",
            "feed_scratch",
        ],
        "library_id": ["library_id", "library_id_uuid", "library_id_datestamp"],
        "sqlite_sequence": ["name", "seq"],
        "publishers": [
            "publisher_id",
            "publisher",
            "publisher_sort",
            "publisher_phash",
            "publisher_wikipedia",
            "publisher_website",
            "publisher_parent",
            "publisher_position",
            "publisher_tree_id",
            "publisher_full",
            "publisher_created_datestamp",
            "publisher_datestamp",
            "publisher_scratch",
        ],
        "series": [
            "series_id",
            "series",
            "series_sort",
            "series_phash",
            "series_over_author",
            "series_parent",
            "series_parent_position",
            "series_tree_id",
            "series_full",
            "series_datestamp",
            "series_scratch",
        ],
        "allowed_types__folder_stores_folder_stores_intralinks": [
            "allowed_types__folder_stores_folder_stores_intralink_id",
            "allowed_types__folder_stores_folder_stores_intralink_type",
            "allowed_types__folder_stores_folder_stores_intralink_datestamp",
            "allowed_types__folder_stores_folder_stores_intralink_scratch",
        ],
        "books": [
            "book_id",
            "book_sort",
            "book_flags",
            "book_pubdate",
            "book_copyright_date",
            "book_uuid",
            "book_has_cover",
            "book_has_local_cover",
            "book_last_modified",
            "book_fingerprint",
            "book_paths",
            "book_size",
            "book_rating",
            "book_created_datestamp",
            "book_datestamp",
            "book_scratch",
        ],
        "devices": [
            "device_id",
            "device_type",
            "device_created_datestamp",
            "device_datestamp",
            "device_scratch",
        ],
        "preferences": [
            "preference_id",
            "preference_key",
            "preference_value",
            "preference_value_type",
            "preference_parent_LiuXin_instance",
            "preference_datestamp",
            "preference_scratch",
        ],
        "publisher_title_links": [
            "publisher_title_link_id",
            "publisher_title_link_publisher_id",
            "publisher_title_link_title_id",
            "publisher_title_link_priority",
            "publisher_title_link_datestamp",
            "publisher_title_link_scratch",
        ],
        "comments": [
            "comment_id",
            "comment",
            "comment_datestamp",
            "comment_scratch",
        ],
        "book_folder_links": [
            "book_folder_link_id",
            "book_folder_link_book_id",
            "book_folder_link_folder_id",
            "book_folder_link_priority",
            "book_folder_link_datestamp",
            "book_folder_link_scratch",
        ],
        "series_synopsis_links": [
            "series_synopsis_link_id",
            "series_synopsis_link_series_id",
            "series_synopsis_link_synopsis_id",
            "series_synopsis_link_priority",
            "series_synopsis_link_datestamp",
            "series_synopsis_link_scratch",
        ],
        "allowed_types__creator_series_links": [
            "allowed_types__creator_series_link_id",
            "allowed_types__creator_series_link_type",
            "allowed_types__creator_series_link_datestamp",
            "allowed_types__creator_series_link_scratch",
        ],
        "books_plugin_data": [
            "book_plugin_data_id",
            "book_plugin_data_book",
            "book_plugin_data_name",
            "book_plugin_data_val",
            "book_plugin_created_datestamp",
            "book_plugin_datestamp",
            "book_plugin_scratch",
        ],
        "tags": ["tag_id", "tag", "tag_phash", "tag_datestamp", "tag_scratch"],
        "synopsis_title_links": [
            "synopsis_title_link_id",
            "synopsis_title_link_synopsis_id",
            "synopsis_title_link_title_id",
            "synopsis_title_link_priority",
            "synopsis_title_link_datestamp",
            "synopsis_title_link_scratch",
        ],
        "comment_creator_links": [
            "comment_creator_link_id",
            "comment_creator_link_comment_id",
            "comment_creator_link_creator_id",
            "comment_creator_link_priority",
            "comment_creator_link_type",
            "comment_creator_link_datestamp",
            "comment_creator_link_scratch",
        ],
        "synopses": [
            "synopsis_id",
            "synopsis",
            "synopsis_datestamp",
            "synopsis_scratch",
        ],
        "database_metadata": [
            "database_metadata_id",
            "database_metadata_unique_id",
            "database_metadata_parent_LiuXin_instance",
            "database_metadata_db_name",
            "database_metadata_datestamp",
            "database_metadata_scratch",
        ],
        "allowed_types__comment_series_links": [
            "allowed_types__comment_series_link_id",
            "allowed_types__comment_series_link_type",
            "allowed_types__comment_series_link_datestamp",
            "allowed_types__comment_series_link_scratch",
        ],
        "folder_stores": [
            "folder_store_id",
            "folder_store",
            "folder_store_identifier",
            "folder_store_path",
            "folder_store_path_os_type",
            "folder_store_created",
            "folder_store_media_types",
            "folder_store_forbidden_print",
            "folder_store_preferred_print",
            "folder_store_cache",
            "folder_store_storage",
            "folder_store_cf_expansion",
            "folder_store_cache_priority",
            "folder_store_max_path_length",
            "folder_store_user_name",
            "folder_store_password",
            "folder_store_type",
            "folder_store_marker_name",
            "folder_store_marker_text",
            "folder_store_marker_path",
            "folder_store_marker_path_os_type",
            "folder_store_dedicated_drive",
            "folder_store_max_size",
            "folder_store_found",
            "folder_store_readable",
            "folder_store_writeable",
            "folder_store_size",
            "folder_store_free_size",
            "folder_store_creation_date",
            "folder_store_created_datestamp",
            "folder_store_datestamp",
            "folder_store_scratch",
        ],
        "creator_language_links": [
            "creator_language_link_id",
            "creator_language_link_creator_id",
            "creator_language_link_language_id",
            "creator_language_link_datestamp",
            "creator_language_link_scratch",
        ],
        "identifier_identifier_intralinks": [
            "identifier_identifier_intralink_id",
            "identifier_identifier_intralink_primary_id",
            "identifier_identifier_intralink_secondary_id",
            "identifier_identifier_intralink_type",
            "identifier_identifier_intralink_datestamp",
            "identifier_identifier_intralink_scratch",
        ],
        "creator_note_links": [
            "creator_note_link_id",
            "creator_note_link_creator_id",
            "creator_note_link_note_id",
            "creator_note_link_priority",
            "creator_note_link_type",
            "creator_note_link_datestamp",
            "creator_note_link_scratch",
        ],
        "custom_column_3": [
            "custom_column_3_id",
            "custom_column_3_book",
            "custom_column_3_value",
        ],
        "allowed_types__language_title_links": [
            "allowed_types__language_title_link_id",
            "allowed_types__language_title_link_type",
            "allowed_types__language_title_link_datestamp",
            "allowed_types__language_title_link_scratch",
        ],
        "publisher_publisher_intralinks": [
            "publisher_publisher_intralink_id",
            "publisher_publisher_intralink_primary_id",
            "publisher_publisher_intralink_secondary_id",
            "publisher_publisher_intralink_type",
            "publisher_publisher_intralink_datestamp",
            "publisher_publisher_intralink_scratch",
        ],
        "hashes": ["hash_id", "hash"],
        "custom_columns": [
            "custom_column_id",
            "custom_column_mark_for_delete",
            "custom_column_in_table",
            "custom_column_label",
            "custom_column_name",
            "custom_column_datatype",
            "custom_column_db_datatype",
            "custom_column_editable",
            "custom_column_display",
            "custom_column_normalized",
            "custom_column_is_multiple",
            "custom_column_ordered",
            "custom_column_datestamp",
            "custom_column_scratch",
        ],
        "folder_store_note_links": [
            "folder_store_note_link_id",
            "folder_store_note_link_folder_store_id",
            "folder_store_note_link_note_id",
            "folder_store_note_link_priority",
            "folder_store_note_link_datestamp",
            "folder_store_note_link_scratch",
        ],
        "genre_title_links": [
            "genre_title_link_id",
            "genre_title_link_genre_id",
            "genre_title_link_title_id",
            "genre_title_link_priority",
            "genre_title_link_datestamp",
            "genre_title_link_scratch",
        ],
        "comment_title_links": [
            "comment_title_link_id",
            "comment_title_link_comment_id",
            "comment_title_link_title_id",
            "comment_title_link_priority",
            "comment_title_link_type",
            "comment_title_link_datestamp",
            "comment_title_link_scratch",
        ],
        "series_tag_links": [
            "series_tag_link_id",
            "series_tag_link_series_id",
            "series_tag_link_tag_id",
            "series_tag_link_datestamp",
            "series_tag_link_scratch",
        ],
        "allowed_types__file_identifier_links": [
            "allowed_types__file_identifier_link_id",
            "allowed_types__file_identifier_link_type",
            "allowed_types__file_identifier_link_datestamp",
            "allowed_types__file_identifier_link_scratch",
        ],
        "folder_store_folder_store_intralinks": [
            "folder_store_folder_store_intralink_id",
            "folder_store_folder_store_intralink_primary_id",
            "folder_store_folder_store_intralink_secondary_id",
            "folder_store_folder_store_intralink_type",
            "folder_store_folder_store_intralink_datestamp",
            "folder_store_folder_store_intralink_scratch",
        ],
        "files": [
            "file_id",
            "file_name",
            "file_base_name",
            "file_tag",
            "file_extension",
            "file_path",
            "file_auto_name",
            "file_use_auto_name",
            "file_size",
            "file_hash",
            "file_new_hash",
            "file_corrupt",
            "file_base_folder",
            "file_acquired_timestamp",
            "file_source",
            "file_original_name",
            "file_original_path",
            "file_phash",
            "file_anthology",
            "file_critical",
            "file_parent",
            "file_conversion_settings",
            "file_processed",
            "file_created_datestamp",
            "file_datestamp",
            "file_scratch",
        ],
        "creator_folder_links": [
            "creator_folder_link_id",
            "creator_folder_link_creator_id",
            "creator_folder_link_folder_id",
            "creator_folder_link_priority",
            "creator_folder_link_datestamp",
            "creator_folder_link_scratch",
        ],
        "allowed_types__rating_title_links": [
            "allowed_types__rating_title_link_id",
            "allowed_types__rating_title_link_type",
            "allowed_types__rating_title_link_datestamp",
            "allowed_types__rating_title_link_scratch",
        ],
        "note_title_links": [
            "note_title_link_id",
            "note_title_link_note_id",
            "note_title_link_title_id",
            "note_title_link_priority",
            "note_title_link_type",
            "note_title_link_datestamp",
            "note_title_link_scratch",
        ],
        "allowed_types__comment_creator_links": [
            "allowed_types__comment_creator_link_id",
            "allowed_types__comment_creator_link_type",
            "allowed_types__comment_creator_link_datestamp",
            "allowed_types__comment_creator_link_scratch",
        ],
        "tag_title_links": [
            "tag_title_link_id",
            "tag_title_link_tag_id",
            "tag_title_link_title_id",
            "tag_title_link_datestamp",
            "tag_title_link_scratch",
        ],
        "creator_tag_links": [
            "creator_tag_link_id",
            "creator_tag_link_creator_id",
            "creator_tag_link_tag_id",
            "creator_tag_link_datestamp",
            "creator_tag_link_scratch",
        ],
        "note_publisher_links": [
            "note_publisher_link_id",
            "note_publisher_link_note_id",
            "note_publisher_link_publisher_id",
            "note_publisher_link_priority",
            "note_publisher_link_datestamp",
            "note_publisher_link_scratch",
        ],
        "file_publisher_links": [
            "file_publisher_link_id",
            "file_publisher_link_file_id",
            "file_publisher_link_publisher_id",
            "file_publisher_link_datestamp",
            "file_publisher_link_scratch",
        ],
        "file_language_links": [
            "file_language_link_id",
            "file_language_link_file_id",
            "file_language_link_language_id",
            "file_language_link_datestamp",
            "file_language_link_scratch",
        ],
        "titles": [
            "title_id",
            "title",
            "title_sort",
            "title_phash",
            "title_creator_sort",
            "title_pub_date",
            "title_copyright_date",
            "title_wikipedia",
            "title_fiction_length_category",
            "title_type",
            "title_wordcount",
            "title_source",
            "title_source_path",
            "title_source_name",
            "title_created_datestamp",
            "title_datestamp",
            "title_last_modified",
            "title_scratch",
        ],
        "allowed_types__titles_titles_intralinks": [
            "allowed_types__titles_titles_intralink_id",
            "allowed_types__titles_titles_intralink_type",
            "allowed_types__titles_titles_intralink_datestamp",
            "allowed_types__titles_titles_intralink_scratch",
        ],
        "books_custom_column_5_link": [
            "books_custom_column_5_link_id",
            "books_custom_column_5_link_book",
            "books_custom_column_5_link_value",
            "books_custom_column_5_link_extra",
        ],
        "custom_column_4": ["custom_column_4_id", "custom_column_4_value"],
        "custom_column_5": ["custom_column_5_id", "custom_column_5_value"],
        "allowed_types__creator_note_links": [
            "allowed_types__creator_note_link_id",
            "allowed_types__creator_note_link_type",
            "allowed_types__creator_note_link_datestamp",
            "allowed_types__creator_note_link_scratch",
        ],
        "custom_column_1": ["custom_column_1_id", "custom_column_1_value"],
        "custom_column_2": [
            "custom_column_2_id",
            "custom_column_2_book",
            "custom_column_2_value",
        ],
        "creator_synopsis_links": [
            "creator_synopsis_link_id",
            "creator_synopsis_link_creator_id",
            "creator_synopsis_link_synopsis_id",
            "creator_synopsis_link_datestamp",
            "creator_synopsis_link_scratch",
        ],
        "allowed_types__tags_tags_intralinks": [
            "allowed_types__tags_tags_intralink_id",
            "allowed_types__tags_tags_intralink_type",
            "allowed_types__tags_tags_intralink_datestamp",
            "allowed_types__tags_tags_intralink_scratch",
        ],
        "rating_title_links": [
            "rating_title_link_id",
            "rating_title_link_rating_id",
            "rating_title_link_title_id",
            "rating_title_link_type",
            "rating_title_link_datestamp",
            "rating_title_link_scratch",
        ],
        "allowed_types__covers_covers_intralinks": [
            "allowed_types__covers_covers_intralink_id",
            "allowed_types__covers_covers_intralink_type",
            "allowed_types__covers_covers_intralink_datestamp",
            "allowed_types__covers_covers_intralink_scratch",
        ],
        "covers": [
            "cover_id",
            "cover_name",
            "cover_extension",
            "cover_path",
            "cover_use_auto_name",
            "cover_hash",
            "cover_new_hash",
            "cover_corrupt",
            "cover_original_path",
            "cover_local",
            "cover_base_folder",
            "cover_created_datestamp",
            "cover_datestamp",
            "cover_scratch",
        ],
        "book_file_links": [
            "book_file_link_id",
            "book_file_link_book_id",
            "book_file_link_file_id",
            "book_file_link_priority",
            "book_file_link_datestamp",
            "book_file_link_scratch",
        ],
        "file_identifier_links": [
            "file_identifier_link_id",
            "file_identifier_link_file_id",
            "file_identifier_link_identifier_id",
            "file_identifier_link_priority",
            "file_identifier_link_type",
            "file_identifier_link_datestamp",
            "file_identifier_link_scratch",
        ],
        "cover_creator_links": [
            "cover_creator_link_id",
            "cover_creator_link_cover_id",
            "cover_creator_link_creator_id",
            "cover_creator_link_priority",
            "cover_creator_link_datestamp",
            "cover_creator_link_scratch",
        ],
        "ratings": [
            "rating_id",
            "rating",
            "rating_source",
            "rating_datestamp",
            "rating_scratch",
        ],
        "genres": [
            "genre_id",
            "genre",
            "genre_sort",
            "genre_phash",
            "genre_parent",
            "genre_position",
            "genre_tree_id",
            "genre_full",
            "genre_datestamp",
            "genre_scratch",
        ],
        "creator_series_links": [
            "creator_series_link_id",
            "creator_series_link_creator_id",
            "creator_series_link_series_id",
            "creator_series_link_type",
            "creator_series_link_datestamp",
            "creator_series_link_scratch",
        ],
        "last_read_positions": [
            "id",
            "book",
            "format",
            "user",
            "device",
            "cfi",
            "epoch",
            "pos_frac",
        ],
        "device_note_links": [
            "device_note_link_id",
            "device_note_link_device_id",
            "device_note_link_note_id",
            "device_note_link_priority",
            "device_note_link_datestamp",
            "device_note_link_scratch",
        ],
        "subjects": [
            "subject_id",
            "subject",
            "subject_phash",
            "subject_sort",
            "subject_parent",
            "subject_parent_position",
            "subject_tree_id",
            "subject_full",
            "subject_datestamp",
            "subject_scratch",
        ],
        "allowed_types__creator_title_links": [
            "allowed_types__creator_title_link_id",
            "allowed_types__creator_title_link_type",
            "allowed_types__creator_title_link_datestamp",
            "allowed_types__creator_title_link_scratch",
        ],
        "folders": [
            "folder_id",
            "folder_name",
            "folder_tag",
            "folder_original_name",
            "folder_auto_name",
            "folder_use_auto_name",
            "folder_path",
            "folder_auto_position",
            "folder_found",
            "folder_folder_store_id",
            "folder_parent",
            "folder_depth",
            "folder_size",
            "folder_hash",
            "folder_types",
            "folder_created_datestamp",
            "folder_datestamp",
            "folder_scratch",
        ],
        "allowed_types__device_file_links": [
            "allowed_types__device_file_link_id",
            "allowed_types__device_file_link_type",
            "allowed_types__device_file_link_datestamp",
            "allowed_types__device_file_link_scratch",
        ],
        "allowed_types__book_cover_links": [
            "allowed_types__book_cover_link_id",
            "allowed_types__book_cover_link_type",
            "allowed_types__book_cover_link_datestamp",
            "allowed_types__book_cover_link_scratch",
        ],
        "folder_series_links": [
            "folder_series_link_id",
            "folder_series_link_folder_id",
            "folder_series_link_series_id",
            "folder_series_link_priority",
            "folder_series_link_datestamp",
            "folder_series_link_scratch",
        ],
        "series_title_links": [
            "series_title_link_id",
            "series_title_link_series_id",
            "series_title_link_title_id",
            "series_title_link_priority",
            "series_title_link_index",
            "series_title_link_datestamp",
            "series_title_link_scratch",
        ],
        "cover_cover_intralinks": [
            "cover_cover_intralink_id",
            "cover_cover_intralink_primary_id",
            "cover_cover_intralink_secondary_id",
            "cover_cover_intralink_type",
            "cover_cover_intralink_datestamp",
            "cover_cover_intralink_scratch",
        ],
        "genre_series_links": [
            "genre_series_link_id",
            "genre_series_link_genre_id",
            "genre_series_link_series_id",
            "genre_series_link_priority",
            "genre_series_link_datestamp",
            "genre_series_link_scratch",
        ],
        "subject_title_links": [
            "subject_title_link_id",
            "subject_title_link_subject_id",
            "subject_title_link_title_id",
            "subject_title_link_priority",
            "subject_title_link_datestamp",
            "subject_title_link_scratch",
        ],
        "cover_series_links": [
            "cover_series_link_id",
            "cover_series_link_cover_id",
            "cover_series_link_series_id",
            "cover_series_link_priority",
            "cover_series_link_datestamp",
            "cover_series_link_scratch",
        ],
        "identifiers": [
            "identifier_id",
            "identifier",
            "identifier_type",
            "identifier_datestamp",
            "identifier_scratch",
        ],
        "comment_series_links": [
            "comment_series_link_id",
            "comment_series_link_comment_id",
            "comment_series_link_series_id",
            "comment_series_link_priority",
            "comment_series_link_type",
            "comment_series_link_datestamp",
            "comment_series_link_scratch",
        ],
        "allowed_types__comment_title_links": [
            "allowed_types__comment_title_link_id",
            "allowed_types__comment_title_link_type",
            "allowed_types__comment_title_link_datestamp",
            "allowed_types__comment_title_link_scratch",
        ],
        "allowed_types__identifiers_identifiers_intralinks": [
            "allowed_types__identifiers_identifiers_intralink_id",
            "allowed_types__identifiers_identifiers_intralink_type",
            "allowed_types__identifiers_identifiers_intralink_datestamp",
            "allowed_types__identifiers_identifiers_intralink_scratch",
        ],
        "device_file_links": [
            "device_file_link_id",
            "device_file_link_device_id",
            "device_file_link_file_id",
            "device_file_link_type",
            "device_file_link_datestamp",
            "device_file_link_scratch",
        ],
        "creators": [
            "creator_id",
            "creator",
            "creator_sort",
            "creator_short_name",
            "creator_last_name",
            "creator_phash",
            "creator_legal_name",
            "creator_birth_date",
            "creator_death_date",
            "creator_type",
            "creator_seminal_work",
            "creator_one_person",
            "creator_wikipedia",
            "creator_imdb",
            "creator_link",
            "creator_created_datestamp",
            "creator_datestamp",
            "creator_scratch",
        ],
        "book_cover_links": [
            "book_cover_link_id",
            "book_cover_link_book_id",
            "book_cover_link_cover_id",
            "book_cover_link_priority",
            "book_cover_link_type",
            "book_cover_link_datestamp",
            "book_cover_link_scratch",
        ],
    }

    all_tables_and_column_headings = theo_tables_and_columns

    all_known_tables = sorted(theo_tables_and_columns.keys())

    db_tables = all_known_tables
    db_tables_set = set([_ for _ in db_tables])

    all_sorted_tables = sorted(all_known_tables)

    existing_triggers = [
        "update_callback_on_titles",
        "block_insert_on_database_version_table",
        "block_update_on_database_version_table",
        "block_delete_on_database_version_table",
        "fkc_update_books_custom_column_1_link_a",
        "fkc_update_books_custom_column_1_link_b",
        "fkc_insert_books_custom_column_1_link",
        "fkc_delete_books_custom_column_1_link",
        "fkc_insert_custom_column_2",
        "fkc_update_custom_column_2",
        "fkc_insert_custom_column_3",
        "fkc_update_custom_column_3",
        "fkc_update_books_custom_column_4_link_a",
        "fkc_update_books_custom_column_4_link_b",
        "fkc_insert_books_custom_column_4_link",
        "fkc_delete_books_custom_column_4_link",
        "fkc_update_books_custom_column_5_link_a",
        "fkc_update_books_custom_column_5_link_b",
        "fkc_insert_books_custom_column_5_link",
        "fkc_delete_books_custom_column_5_link",
    ]

    # ------------------------------------------------------------------------------------------------------------------
    #
    # - MAIN TABLES

    theo_title_count = 97
    theo_series_count = 34
    publisher_record_count = 20
    theo_tag_title_link_count = 169

    all_tables_set = set(tn for tn in theo_tables_and_columns.keys())

    theo_main_tables = set(
        [
            "folders",
            "series",
            "covers",
            "books",
            "genres",
            "custom_columns",
            "comments",
            "languages",
            "last_read_positions",
            "subjects",
            "files",
            "publishers",
            "tags",
            "synopses",
            "folder_stores",
            "notes",
            "identifiers",
            "devices",
            "titles",
            "feeds",
            "creators",
        ]
    )

    #
    # ------------------------------------------------------------------------------------------------------------------
    # ------------------------------------------------------------------------------------------------------------------
    #
    # - CUSTOM COLUMNS

    theo_db_custom_tables = {
        "custom_column_1",
        "books_custom_column_1_link",
        "custom_column_2",
        "custom_column_3",
        "custom_column_4",
        "books_custom_column_4_link",
        "custom_column_5",
        "books_custom_column_5_link",
    }

    #
    # ------------------------------------------------------------------------------------------------------------------
