from LiuXin_tests.test_databases.test_db_properties.common_db_properties import (
    CommonDBProperties,
)


class TestDB22Properties(CommonDBProperties):

    theo_tables_and_columns = {
        "secondary_uuids": [
            "secondary_uuid_id",
            "secondary_uuid",
            "secondary_uuid_datestamp",
            "secondary_uuid_scratch",
        ],
        "creator_title_links": [
            "creator_title_link_id",
            "creator_title_link_creator_id",
            "creator_title_link_title_id",
            "creator_title_link_priority",
            "creator_title_link_type",
            "creator_title_link_datestamp",
            "creator_title_link_scratch",
        ],
        "tag_tag_intralinks": [
            "tag_tag_intralink_id",
            "tag_tag_intralink_primary_id",
            "tag_tag_intralink_secondary_id",
            "tag_tag_intralink_type",
            "tag_tag_intralink_datestamp",
            "tag_tag_intralink_scratch",
        ],
        "language_title_links": [
            "language_title_link_id",
            "language_title_link_language_id",
            "language_title_link_title_id",
            "language_title_link_priority",
            "language_title_link_type",
            "language_title_link_datestamp",
            "language_title_link_scratch",
        ],
        "creator_creator_intralinks": [
            "creator_creator_intralink_id",
            "creator_creator_intralink_primary_id",
            "creator_creator_intralink_secondary_id",
            "creator_creator_intralink_type",
            "creator_creator_intralink_datestamp",
            "creator_creator_intralink_scratch",
        ],
        "new_books": [
            "new_book_id",
            "new_book_name",
            "new_book_extension",
            "new_book_path",
            "new_book_hash_1",
            "new_book_hash_2",
            "new_book_size",
            "new_book_group_id",
            "new_book_cached",
            "new_book_cache_attempted",
            "new_book_datestamp",
            "new_book_scratch",
        ],
        "identifier_title_links": [
            "identifier_title_link_id",
            "identifier_title_link_identifier_id",
            "identifier_title_link_title_id",
            "identifier_title_link_priority",
            "identifier_title_link_type",
            "identifier_title_link_datestamp",
            "identifier_title_link_scratch",
        ],
        "custom_column_9": [
            "custom_column_9_id",
            "custom_column_9_book",
            "custom_column_9_value",
        ],
        "allowed_types__publishers_publishers_intralinks": [
            "allowed_types__publishers_publishers_intralink_id",
            "allowed_types__publishers_publishers_intralink_type",
            "allowed_types__publishers_publishers_intralink_datestamp",
            "allowed_types__publishers_publishers_intralink_scratch",
        ],
        "books_custom_column_8_link": [
            "books_custom_column_8_link_id",
            "books_custom_column_8_link_book",
            "books_custom_column_8_link_value",
        ],
        "allowed_types__creators_creators_intralinks": [
            "allowed_types__creators_creators_intralink_id",
            "allowed_types__creators_creators_intralink_type",
            "allowed_types__creators_creators_intralink_datestamp",
            "allowed_types__creators_creators_intralink_scratch",
        ],
        "allowed_types__note_title_links": [
            "allowed_types__note_title_link_id",
            "allowed_types__note_title_link_type",
            "allowed_types__note_title_link_datestamp",
            "allowed_types__note_title_link_scratch",
        ],
        "compressed_files": [
            "compressed_file_id",
            "compressed_file_name",
            "compressed_file_extension",
            "compressed_file_path",
            "compressed_file_hash_1",
            "compressed_file_hash_2",
            "compressed_file_size",
            "compressed_file_group_id",
            "compressed_file_folder",
            "compressed_file_cached",
            "compressed_file_cache_attempted",
            "compressed_file_datestamp",
            "compressed_file_scratch",
        ],
        "custom_column_22": ["custom_column_22_id", "custom_column_22_value"],
        "note_series_links": [
            "note_series_link_id",
            "note_series_link_note_id",
            "note_series_link_series_id",
            "note_series_link_priority",
            "note_series_link_datestamp",
            "note_series_link_scratch",
        ],
        "languages": [
            "language_id",
            "language",
            "language_code",
            "language_datestamp",
            "language_scratch",
        ],
        "content_levels": [
            "content_level_id",
            "content_level",
            "content_level_datestamp",
            "content_level_scratch",
        ],
        "database_version": [
            "database_version_id",
            "database_version_version",
            "database_version_datestamp",
        ],
        "allowed_types__identifier_title_links": [
            "allowed_types__identifier_title_link_id",
            "allowed_types__identifier_title_link_type",
            "allowed_types__identifier_title_link_datestamp",
            "allowed_types__identifier_title_link_scratch",
        ],
        "books_custom_column_6_link": [
            "books_custom_column_6_link_id",
            "books_custom_column_6_link_book",
            "books_custom_column_6_link_value",
            "books_custom_column_6_link_extra",
        ],
        "file_file_intralinks": [
            "file_file_intralink_id",
            "file_file_intralink_primary_id",
            "file_file_intralink_secondary_id",
            "file_file_intralink_type",
            "file_file_intralink_datestamp",
            "file_file_intralink_scratch",
        ],
        "words": ["word_id", "word", "word_datestamp", "word_scratch"],
        "books_custom_column_4_link": [
            "books_custom_column_4_link_id",
            "books_custom_column_4_link_book",
            "books_custom_column_4_link_value",
        ],
        "file_folder_links": [
            "file_folder_link_id",
            "file_folder_link_file_id",
            "file_folder_link_folder_id",
            "file_folder_link_datestamp",
            "file_folder_link_scratch",
        ],
        "loc_shelf_number_title_links": [
            "loc_shelf_number_title_link_id",
            "loc_shelf_number_title_link_loc_shelf_number_id",
            "loc_shelf_number_title_link_title_id",
            "loc_shelf_number_title_link_priority",
            "loc_shelf_number_title_link_primary",
            "loc_shelf_number_title_link_type",
            "loc_shelf_number_title_link_index",
            "loc_shelf_number_title_link_datestamp",
            "loc_shelf_number_title_link_scratch",
        ],
        "title_title_intralinks": [
            "title_title_intralink_id",
            "title_title_intralink_primary_id",
            "title_title_intralink_secondary_id",
            "title_title_intralink_type",
            "title_title_intralink_datestamp",
            "title_title_intralink_scratch",
        ],
        "notes": ["note_id", "note", "note_datestamp", "note_scratch"],
        "metadata_dirtied_books": [
            "metadata_dirtied_book_id",
            "metadata_dirtied_book",
        ],
        "conversion_options": [
            "conversion_option_id",
            "conversion_option_format",
            "conversion_option_book",
            "conversion_option_data",
            "conversion_option_datestamp",
        ],
        "allowed_types__files_files_intralinks": [
            "allowed_types__files_files_intralink_id",
            "allowed_types__files_files_intralink_type",
            "allowed_types__files_files_intralink_datestamp",
            "allowed_types__files_files_intralink_scratch",
        ],
        "publisher_publisher_owner_links": [
            "publisher_publisher_owner_link_id",
            "publisher_publisher_owner_link_publisher_id",
            "publisher_publisher_owner_link_publisher_owner_id",
            "publisher_publisher_owner_link_priority",
            "publisher_publisher_owner_link_primary",
            "publisher_publisher_owner_link_type",
            "publisher_publisher_owner_link_index",
            "publisher_publisher_owner_link_datestamp",
            "publisher_publisher_owner_link_scratch",
        ],
        "feeds": [
            "feed_id",
            "feed_title",
            "feed_script",
            "feed_created_datestamp",
            "feed_datestamp",
            "feed_scratch",
        ],
        "library_id": ["library_id", "library_id_uuid", "library_id_datestamp"],
        "sqlite_sequence": ["name", "seq"],
        "publishers": [
            "publisher_id",
            "publisher",
            "publisher_sort",
            "publisher_phash",
            "publisher_wikipedia",
            "publisher_website",
            "publisher_parent",
            "publisher_position",
            "publisher_tree_id",
            "publisher_full",
            "publisher_created_datestamp",
            "publisher_datestamp",
            "publisher_scratch",
        ],
        "series": [
            "series_id",
            "series",
            "series_sort",
            "series_phash",
            "series_over_author",
            "series_parent",
            "series_parent_position",
            "series_tree_id",
            "series_full",
            "series_datestamp",
            "series_scratch",
        ],
        "allowed_types__folder_stores_folder_stores_intralinks": [
            "allowed_types__folder_stores_folder_stores_intralink_id",
            "allowed_types__folder_stores_folder_stores_intralink_type",
            "allowed_types__folder_stores_folder_stores_intralink_datestamp",
            "allowed_types__folder_stores_folder_stores_intralink_scratch",
        ],
        "books": [
            "book_id",
            "book_sort",
            "book_flags",
            "book_pubdate",
            "book_copyright_date",
            "book_uuid",
            "book_has_cover",
            "book_has_local_cover",
            "book_last_modified",
            "book_fingerprint",
            "book_paths",
            "book_size",
            "book_rating",
            "book_created_datestamp",
            "book_datestamp",
            "book_scratch",
        ],
        "devices": [
            "device_id",
            "device_type",
            "device_created_datestamp",
            "device_datestamp",
            "device_scratch",
        ],
        "preferences": [
            "preference_id",
            "preference_key",
            "preference_value",
            "preference_value_type",
            "preference_parent_LiuXin_instance",
            "preference_datestamp",
            "preference_scratch",
        ],
        "publisher_title_links": [
            "publisher_title_link_id",
            "publisher_title_link_publisher_id",
            "publisher_title_link_title_id",
            "publisher_title_link_priority",
            "publisher_title_link_datestamp",
            "publisher_title_link_scratch",
        ],
        "comments": [
            "comment_id",
            "comment",
            "comment_datestamp",
            "comment_scratch",
        ],
        "loc_shelf_numbers": [
            "loc_shelf_number_id",
            "loc_shelf_number",
            "loc_shelf_number_datestamp",
            "loc_shelf_number_scratch",
        ],
        "custom_column_21": [
            "custom_column_21_id",
            "custom_column_21_book",
            "custom_column_21_value",
        ],
        "custom_column_20": [
            "custom_column_20_id",
            "custom_column_20_book",
            "custom_column_20_value",
        ],
        "book_folder_links": [
            "book_folder_link_id",
            "book_folder_link_book_id",
            "book_folder_link_folder_id",
            "book_folder_link_priority",
            "book_folder_link_datestamp",
            "book_folder_link_scratch",
        ],
        "custom_column_8": ["custom_column_8_id", "custom_column_8_value"],
        "series_synopsis_links": [
            "series_synopsis_link_id",
            "series_synopsis_link_series_id",
            "series_synopsis_link_synopsis_id",
            "series_synopsis_link_priority",
            "series_synopsis_link_datestamp",
            "series_synopsis_link_scratch",
        ],
        "allowed_types__creator_series_links": [
            "allowed_types__creator_series_link_id",
            "allowed_types__creator_series_link_type",
            "allowed_types__creator_series_link_datestamp",
            "allowed_types__creator_series_link_scratch",
        ],
        "books_plugin_data": [
            "book_plugin_data_id",
            "book_plugin_data_book",
            "book_plugin_data_name",
            "book_plugin_data_val",
            "book_plugin_created_datestamp",
            "book_plugin_datestamp",
            "book_plugin_scratch",
        ],
        "series_series_character_introduction_links": [
            "series_series_character_introduction_link_id",
            "series_series_character_introduction_link_series_id",
            "series_series_character_introduction_link_series_character_introduction_id",
            "series_series_character_introduction_link_priority",
            "series_series_character_introduction_link_primary",
            "series_series_character_introduction_link_type",
            "series_series_character_introduction_link_index",
            "series_series_character_introduction_link_datestamp",
            "series_series_character_introduction_link_scratch",
        ],
        "tags": ["tag_id", "tag", "tag_phash", "tag_datestamp", "tag_scratch"],
        "synopsis_title_links": [
            "synopsis_title_link_id",
            "synopsis_title_link_synopsis_id",
            "synopsis_title_link_title_id",
            "synopsis_title_link_priority",
            "synopsis_title_link_datestamp",
            "synopsis_title_link_scratch",
        ],
        "comment_creator_links": [
            "comment_creator_link_id",
            "comment_creator_link_comment_id",
            "comment_creator_link_creator_id",
            "comment_creator_link_priority",
            "comment_creator_link_type",
            "comment_creator_link_datestamp",
            "comment_creator_link_scratch",
        ],
        "synopses": [
            "synopsis_id",
            "synopsis",
            "synopsis_datestamp",
            "synopsis_scratch",
        ],
        "books_custom_column_2_link": [
            "books_custom_column_2_link_id",
            "books_custom_column_2_link_book",
            "books_custom_column_2_link_value",
        ],
        "content_level_title_links": [
            "content_level_title_link_id",
            "content_level_title_link_content_level_id",
            "content_level_title_link_title_id",
            "content_level_title_link_priority",
            "content_level_title_link_primary",
            "content_level_title_link_type",
            "content_level_title_link_index",
            "content_level_title_link_datestamp",
            "content_level_title_link_scratch",
        ],
        "database_metadata": [
            "database_metadata_id",
            "database_metadata_unique_id",
            "database_metadata_parent_LiuXin_instance",
            "database_metadata_db_name",
            "database_metadata_datestamp",
            "database_metadata_scratch",
        ],
        "allowed_types__comment_series_links": [
            "allowed_types__comment_series_link_id",
            "allowed_types__comment_series_link_type",
            "allowed_types__comment_series_link_datestamp",
            "allowed_types__comment_series_link_scratch",
        ],
        "folder_stores": [
            "folder_store_id",
            "folder_store",
            "folder_store_identifier",
            "folder_store_path",
            "folder_store_path_os_type",
            "folder_store_created",
            "folder_store_media_types",
            "folder_store_forbidden_print",
            "folder_store_preferred_print",
            "folder_store_cache",
            "folder_store_storage",
            "folder_store_cf_expansion",
            "folder_store_cache_priority",
            "folder_store_max_path_length",
            "folder_store_user_name",
            "folder_store_password",
            "folder_store_type",
            "folder_store_marker_name",
            "folder_store_marker_text",
            "folder_store_marker_path",
            "folder_store_marker_path_os_type",
            "folder_store_dedicated_drive",
            "folder_store_max_size",
            "folder_store_found",
            "folder_store_readable",
            "folder_store_writeable",
            "folder_store_size",
            "folder_store_free_size",
            "folder_store_creation_date",
            "folder_store_created_datestamp",
            "folder_store_datestamp",
            "folder_store_scratch",
        ],
        "custom_column_16": ["custom_column_16_id", "custom_column_16_value"],
        "creator_language_links": [
            "creator_language_link_id",
            "creator_language_link_creator_id",
            "creator_language_link_language_id",
            "creator_language_link_datestamp",
            "creator_language_link_scratch",
        ],
        "custom_column_14": ["custom_column_14_id", "custom_column_14_value"],
        "identifier_identifier_intralinks": [
            "identifier_identifier_intralink_id",
            "identifier_identifier_intralink_primary_id",
            "identifier_identifier_intralink_secondary_id",
            "identifier_identifier_intralink_type",
            "identifier_identifier_intralink_datestamp",
            "identifier_identifier_intralink_scratch",
        ],
        "custom_column_12": ["custom_column_12_id", "custom_column_12_value"],
        "custom_column_13": [
            "custom_column_13_id",
            "custom_column_13_book",
            "custom_column_13_value",
        ],
        "custom_column_10": [
            "custom_column_10_id",
            "custom_column_10_book",
            "custom_column_10_value",
        ],
        "creator_note_links": [
            "creator_note_link_id",
            "creator_note_link_creator_id",
            "creator_note_link_note_id",
            "creator_note_link_priority",
            "creator_note_link_type",
            "creator_note_link_datestamp",
            "creator_note_link_scratch",
        ],
        "custom_column_3": [
            "custom_column_3_id",
            "custom_column_3_book",
            "custom_column_3_value",
        ],
        "custom_column_15": [
            "custom_column_15_id",
            "custom_column_15_book",
            "custom_column_15_value",
        ],
        "custom_column_18": ["custom_column_18_id", "custom_column_18_value"],
        "custom_column_19": [
            "custom_column_19_id",
            "custom_column_19_book",
            "custom_column_19_value",
        ],
        "allowed_types__language_title_links": [
            "allowed_types__language_title_link_id",
            "allowed_types__language_title_link_type",
            "allowed_types__language_title_link_datestamp",
            "allowed_types__language_title_link_scratch",
        ],
        "book_books_secondary_uuid_links": [
            "book_books_secondary_uuid_link_id",
            "book_books_secondary_uuid_link_book_id",
            "book_books_secondary_uuid_link_books_secondary_uuid_id",
            "book_books_secondary_uuid_link_priority",
            "book_books_secondary_uuid_link_primary",
            "book_books_secondary_uuid_link_type",
            "book_books_secondary_uuid_link_index",
            "book_books_secondary_uuid_link_datestamp",
            "book_books_secondary_uuid_link_scratch",
        ],
        "book_year_first_published_links": [
            "book_year_first_published_link_id",
            "book_year_first_published_link_book_id",
            "book_year_first_published_link_year_first_published_id",
            "book_year_first_published_link_priority",
            "book_year_first_published_link_primary",
            "book_year_first_published_link_type",
            "book_year_first_published_link_index",
            "book_year_first_published_link_datestamp",
            "book_year_first_published_link_scratch",
        ],
        "publisher_publisher_intralinks": [
            "publisher_publisher_intralink_id",
            "publisher_publisher_intralink_primary_id",
            "publisher_publisher_intralink_secondary_id",
            "publisher_publisher_intralink_type",
            "publisher_publisher_intralink_datestamp",
            "publisher_publisher_intralink_scratch",
        ],
        "tags_custom_column_22_link": [
            "tags_custom_column_22_link_id",
            "tags_custom_column_22_link_book",
            "tags_custom_column_22_link_value",
        ],
        "hashes": ["hash_id", "hash"],
        "book_year_reprinted_links": [
            "book_year_reprinted_link_id",
            "book_year_reprinted_link_book_id",
            "book_year_reprinted_link_year_reprinted_id",
            "book_year_reprinted_link_priority",
            "book_year_reprinted_link_primary",
            "book_year_reprinted_link_type",
            "book_year_reprinted_link_index",
            "book_year_reprinted_link_datestamp",
            "book_year_reprinted_link_scratch",
        ],
        "custom_columns": [
            "custom_column_id",
            "custom_column_mark_for_delete",
            "custom_column_in_table",
            "custom_column_label",
            "custom_column_name",
            "custom_column_datatype",
            "custom_column_db_datatype",
            "custom_column_editable",
            "custom_column_display",
            "custom_column_normalized",
            "custom_column_is_multiple",
            "custom_column_ordered",
            "custom_column_datestamp",
            "custom_column_scratch",
        ],
        "series_character_introductions": [
            "series_character_introduction_id",
            "series_character_introduction",
            "series_character_introduction_datestamp",
            "series_character_introduction_scratch",
        ],
        "folder_store_note_links": [
            "folder_store_note_link_id",
            "folder_store_note_link_folder_store_id",
            "folder_store_note_link_note_id",
            "folder_store_note_link_priority",
            "folder_store_note_link_datestamp",
            "folder_store_note_link_scratch",
        ],
        "genre_title_links": [
            "genre_title_link_id",
            "genre_title_link_genre_id",
            "genre_title_link_title_id",
            "genre_title_link_priority",
            "genre_title_link_datestamp",
            "genre_title_link_scratch",
        ],
        "comment_title_links": [
            "comment_title_link_id",
            "comment_title_link_comment_id",
            "comment_title_link_title_id",
            "comment_title_link_priority",
            "comment_title_link_type",
            "comment_title_link_datestamp",
            "comment_title_link_scratch",
        ],
        "title_word_links": [
            "title_word_link_id",
            "title_word_link_title_id",
            "title_word_link_word_id",
            "title_word_link_priority",
            "title_word_link_primary",
            "title_word_link_type",
            "title_word_link_index",
            "title_word_link_datestamp",
            "title_word_link_scratch",
        ],
        "series_tag_links": [
            "series_tag_link_id",
            "series_tag_link_series_id",
            "series_tag_link_tag_id",
            "series_tag_link_datestamp",
            "series_tag_link_scratch",
        ],
        "allowed_types__file_identifier_links": [
            "allowed_types__file_identifier_link_id",
            "allowed_types__file_identifier_link_type",
            "allowed_types__file_identifier_link_datestamp",
            "allowed_types__file_identifier_link_scratch",
        ],
        "folder_store_folder_store_intralinks": [
            "folder_store_folder_store_intralink_id",
            "folder_store_folder_store_intralink_primary_id",
            "folder_store_folder_store_intralink_secondary_id",
            "folder_store_folder_store_intralink_type",
            "folder_store_folder_store_intralink_datestamp",
            "folder_store_folder_store_intralink_scratch",
        ],
        "files": [
            "file_id",
            "file_name",
            "file_base_name",
            "file_tag",
            "file_extension",
            "file_path",
            "file_auto_name",
            "file_use_auto_name",
            "file_size",
            "file_hash",
            "file_new_hash",
            "file_corrupt",
            "file_base_folder",
            "file_acquired_timestamp",
            "file_source",
            "file_original_name",
            "file_original_path",
            "file_phash",
            "file_anthology",
            "file_critical",
            "file_parent",
            "file_conversion_settings",
            "file_processed",
            "file_created_datestamp",
            "file_datestamp",
            "file_scratch",
        ],
        "creator_folder_links": [
            "creator_folder_link_id",
            "creator_folder_link_creator_id",
            "creator_folder_link_folder_id",
            "creator_folder_link_priority",
            "creator_folder_link_datestamp",
            "creator_folder_link_scratch",
        ],
        "allowed_types__rating_title_links": [
            "allowed_types__rating_title_link_id",
            "allowed_types__rating_title_link_type",
            "allowed_types__rating_title_link_datestamp",
            "allowed_types__rating_title_link_scratch",
        ],
        "note_title_links": [
            "note_title_link_id",
            "note_title_link_note_id",
            "note_title_link_title_id",
            "note_title_link_priority",
            "note_title_link_type",
            "note_title_link_datestamp",
            "note_title_link_scratch",
        ],
        "allowed_types__comment_creator_links": [
            "allowed_types__comment_creator_link_id",
            "allowed_types__comment_creator_link_type",
            "allowed_types__comment_creator_link_datestamp",
            "allowed_types__comment_creator_link_scratch",
        ],
        "tag_title_links": [
            "tag_title_link_id",
            "tag_title_link_tag_id",
            "tag_title_link_title_id",
            "tag_title_link_datestamp",
            "tag_title_link_scratch",
        ],
        "titles_custom_column_1_link": [
            "titles_custom_column_1_link_id",
            "titles_custom_column_1_link_book",
            "titles_custom_column_1_link_value",
        ],
        "character_introduction_title_links": [
            "character_introduction_title_link_id",
            "character_introduction_title_link_character_introduction_id",
            "character_introduction_title_link_title_id",
            "character_introduction_title_link_priority",
            "character_introduction_title_link_primary",
            "character_introduction_title_link_type",
            "character_introduction_title_link_index",
            "character_introduction_title_link_datestamp",
            "character_introduction_title_link_scratch",
        ],
        "custom_column_17": [
            "custom_column_17_id",
            "custom_column_17_book",
            "custom_column_17_value",
        ],
        "creator_tag_links": [
            "creator_tag_link_id",
            "creator_tag_link_creator_id",
            "creator_tag_link_tag_id",
            "creator_tag_link_datestamp",
            "creator_tag_link_scratch",
        ],
        "note_publisher_links": [
            "note_publisher_link_id",
            "note_publisher_link_note_id",
            "note_publisher_link_publisher_id",
            "note_publisher_link_priority",
            "note_publisher_link_datestamp",
            "note_publisher_link_scratch",
        ],
        "books_custom_column_14_link": [
            "books_custom_column_14_link_id",
            "books_custom_column_14_link_book",
            "books_custom_column_14_link_value",
        ],
        "file_publisher_links": [
            "file_publisher_link_id",
            "file_publisher_link_file_id",
            "file_publisher_link_publisher_id",
            "file_publisher_link_datestamp",
            "file_publisher_link_scratch",
        ],
        "file_language_links": [
            "file_language_link_id",
            "file_language_link_file_id",
            "file_language_link_language_id",
            "file_language_link_datestamp",
            "file_language_link_scratch",
        ],
        "titles": [
            "title_id",
            "title",
            "title_sort",
            "title_phash",
            "title_creator_sort",
            "title_pub_date",
            "title_copyright_date",
            "title_wikipedia",
            "title_fiction_length_category",
            "title_type",
            "title_wordcount",
            "title_source",
            "title_source_path",
            "title_source_name",
            "title_created_datestamp",
            "title_datestamp",
            "title_last_modified",
            "title_scratch",
        ],
        "allowed_types__titles_titles_intralinks": [
            "allowed_types__titles_titles_intralink_id",
            "allowed_types__titles_titles_intralink_type",
            "allowed_types__titles_titles_intralink_datestamp",
            "allowed_types__titles_titles_intralink_scratch",
        ],
        "not_series_title_links": [
            "not_series_title_link_id",
            "not_series_title_link_not_series_id",
            "not_series_title_link_title_id",
            "not_series_title_link_priority",
            "not_series_title_link_index",
            "not_series_title_link_datestamp",
            "not_series_title_link_scratch",
        ],
        "custom_column_4": ["custom_column_4_id", "custom_column_4_value"],
        "custom_column_5": [
            "custom_column_5_id",
            "custom_column_5_book",
            "custom_column_5_value",
        ],
        "custom_column_6": ["custom_column_6_id", "custom_column_6_value"],
        "custom_column_7": [
            "custom_column_7_id",
            "custom_column_7_book",
            "custom_column_7_value",
        ],
        "allowed_types__creator_note_links": [
            "allowed_types__creator_note_link_id",
            "allowed_types__creator_note_link_type",
            "allowed_types__creator_note_link_datestamp",
            "allowed_types__creator_note_link_scratch",
        ],
        "custom_column_1": ["custom_column_1_id", "custom_column_1_value"],
        "custom_column_2": ["custom_column_2_id", "custom_column_2_value"],
        "creator_synopsis_links": [
            "creator_synopsis_link_id",
            "creator_synopsis_link_creator_id",
            "creator_synopsis_link_synopsis_id",
            "creator_synopsis_link_datestamp",
            "creator_synopsis_link_scratch",
        ],
        "allowed_types__tags_tags_intralinks": [
            "allowed_types__tags_tags_intralink_id",
            "allowed_types__tags_tags_intralink_type",
            "allowed_types__tags_tags_intralink_datestamp",
            "allowed_types__tags_tags_intralink_scratch",
        ],
        "rating_title_links": [
            "rating_title_link_id",
            "rating_title_link_rating_id",
            "rating_title_link_title_id",
            "rating_title_link_type",
            "rating_title_link_datestamp",
            "rating_title_link_scratch",
        ],
        "allowed_types__covers_covers_intralinks": [
            "allowed_types__covers_covers_intralink_id",
            "allowed_types__covers_covers_intralink_type",
            "allowed_types__covers_covers_intralink_datestamp",
            "allowed_types__covers_covers_intralink_scratch",
        ],
        "not_series": [
            "not_series_id",
            "not_series",
            "not_series_datestamp",
            "not_series_scratch",
        ],
        "covers": [
            "cover_id",
            "cover_name",
            "cover_extension",
            "cover_path",
            "cover_use_auto_name",
            "cover_hash",
            "cover_new_hash",
            "cover_corrupt",
            "cover_original_path",
            "cover_local",
            "cover_base_folder",
            "cover_created_datestamp",
            "cover_datestamp",
            "cover_scratch",
        ],
        "book_file_links": [
            "book_file_link_id",
            "book_file_link_book_id",
            "book_file_link_file_id",
            "book_file_link_priority",
            "book_file_link_datestamp",
            "book_file_link_scratch",
        ],
        "file_identifier_links": [
            "file_identifier_link_id",
            "file_identifier_link_file_id",
            "file_identifier_link_identifier_id",
            "file_identifier_link_priority",
            "file_identifier_link_type",
            "file_identifier_link_datestamp",
            "file_identifier_link_scratch",
        ],
        "character_introductions": [
            "character_introduction_id",
            "character_introduction",
            "character_introduction_datestamp",
            "character_introduction_scratch",
        ],
        "secondary_uuid_title_links": [
            "secondary_uuid_title_link_id",
            "secondary_uuid_title_link_secondary_uuid_id",
            "secondary_uuid_title_link_title_id",
            "secondary_uuid_title_link_priority",
            "secondary_uuid_title_link_primary",
            "secondary_uuid_title_link_type",
            "secondary_uuid_title_link_index",
            "secondary_uuid_title_link_datestamp",
            "secondary_uuid_title_link_scratch",
        ],
        "cover_creator_links": [
            "cover_creator_link_id",
            "cover_creator_link_cover_id",
            "cover_creator_link_creator_id",
            "cover_creator_link_priority",
            "cover_creator_link_datestamp",
            "cover_creator_link_scratch",
        ],
        "ratings": [
            "rating_id",
            "rating",
            "rating_source",
            "rating_datestamp",
            "rating_scratch",
        ],
        "genres": [
            "genre_id",
            "genre",
            "genre_sort",
            "genre_phash",
            "genre_parent",
            "genre_position",
            "genre_tree_id",
            "genre_full",
            "genre_datestamp",
            "genre_scratch",
        ],
        "books_secondary_uuid": [
            "books_secondary_uuid_id",
            "books_secondary_uuid",
            "books_secondary_uuid_datestamp",
            "books_secondary_uuid_scratch",
        ],
        "creator_series_links": [
            "creator_series_link_id",
            "creator_series_link_creator_id",
            "creator_series_link_series_id",
            "creator_series_link_type",
            "creator_series_link_datestamp",
            "creator_series_link_scratch",
        ],
        "last_read_positions": [
            "id",
            "book",
            "format",
            "user",
            "device",
            "cfi",
            "epoch",
            "pos_frac",
        ],
        "device_note_links": [
            "device_note_link_id",
            "device_note_link_device_id",
            "device_note_link_note_id",
            "device_note_link_priority",
            "device_note_link_datestamp",
            "device_note_link_scratch",
        ],
        "subjects": [
            "subject_id",
            "subject",
            "subject_phash",
            "subject_sort",
            "subject_parent",
            "subject_parent_position",
            "subject_tree_id",
            "subject_full",
            "subject_datestamp",
            "subject_scratch",
        ],
        "books_custom_column_16_link": [
            "books_custom_column_16_link_id",
            "books_custom_column_16_link_book",
            "books_custom_column_16_link_value",
            "books_custom_column_16_link_extra",
        ],
        "allowed_types__creator_title_links": [
            "allowed_types__creator_title_link_id",
            "allowed_types__creator_title_link_type",
            "allowed_types__creator_title_link_datestamp",
            "allowed_types__creator_title_link_scratch",
        ],
        "folders": [
            "folder_id",
            "folder_name",
            "folder_tag",
            "folder_original_name",
            "folder_auto_name",
            "folder_use_auto_name",
            "folder_path",
            "folder_auto_position",
            "folder_found",
            "folder_folder_store_id",
            "folder_parent",
            "folder_depth",
            "folder_size",
            "folder_hash",
            "folder_types",
            "folder_created_datestamp",
            "folder_datestamp",
            "folder_scratch",
        ],
        "books_custom_column_18_link": [
            "books_custom_column_18_link_id",
            "books_custom_column_18_link_book",
            "books_custom_column_18_link_value",
        ],
        "publisher_owners": [
            "publisher_owner_id",
            "publisher_owner",
            "publisher_owner_datestamp",
            "publisher_owner_scratch",
        ],
        "allowed_types__device_file_links": [
            "allowed_types__device_file_link_id",
            "allowed_types__device_file_link_type",
            "allowed_types__device_file_link_datestamp",
            "allowed_types__device_file_link_scratch",
        ],
        "allowed_types__book_cover_links": [
            "allowed_types__book_cover_link_id",
            "allowed_types__book_cover_link_type",
            "allowed_types__book_cover_link_datestamp",
            "allowed_types__book_cover_link_scratch",
        ],
        "custom_column_11": [
            "custom_column_11_id",
            "custom_column_11_book",
            "custom_column_11_value",
        ],
        "folder_series_links": [
            "folder_series_link_id",
            "folder_series_link_folder_id",
            "folder_series_link_series_id",
            "folder_series_link_priority",
            "folder_series_link_datestamp",
            "folder_series_link_scratch",
        ],
        "series_title_links": [
            "series_title_link_id",
            "series_title_link_series_id",
            "series_title_link_title_id",
            "series_title_link_priority",
            "series_title_link_index",
            "series_title_link_datestamp",
            "series_title_link_scratch",
        ],
        "cover_cover_intralinks": [
            "cover_cover_intralink_id",
            "cover_cover_intralink_primary_id",
            "cover_cover_intralink_secondary_id",
            "cover_cover_intralink_type",
            "cover_cover_intralink_datestamp",
            "cover_cover_intralink_scratch",
        ],
        "genre_series_links": [
            "genre_series_link_id",
            "genre_series_link_genre_id",
            "genre_series_link_series_id",
            "genre_series_link_priority",
            "genre_series_link_datestamp",
            "genre_series_link_scratch",
        ],
        "subject_title_links": [
            "subject_title_link_id",
            "subject_title_link_subject_id",
            "subject_title_link_title_id",
            "subject_title_link_priority",
            "subject_title_link_datestamp",
            "subject_title_link_scratch",
        ],
        "cover_series_links": [
            "cover_series_link_id",
            "cover_series_link_cover_id",
            "cover_series_link_series_id",
            "cover_series_link_priority",
            "cover_series_link_datestamp",
            "cover_series_link_scratch",
        ],
        "books_custom_column_12_link": [
            "books_custom_column_12_link_id",
            "books_custom_column_12_link_book",
            "books_custom_column_12_link_value",
        ],
        "year_first_published": [
            "year_first_published_id",
            "year_first_published",
            "year_first_published_datestamp",
            "year_first_published_scratch",
        ],
        "identifiers": [
            "identifier_id",
            "identifier",
            "identifier_type",
            "identifier_datestamp",
            "identifier_scratch",
        ],
        "comment_series_links": [
            "comment_series_link_id",
            "comment_series_link_comment_id",
            "comment_series_link_series_id",
            "comment_series_link_priority",
            "comment_series_link_type",
            "comment_series_link_datestamp",
            "comment_series_link_scratch",
        ],
        "allowed_types__comment_title_links": [
            "allowed_types__comment_title_link_id",
            "allowed_types__comment_title_link_type",
            "allowed_types__comment_title_link_datestamp",
            "allowed_types__comment_title_link_scratch",
        ],
        "allowed_types__identifiers_identifiers_intralinks": [
            "allowed_types__identifiers_identifiers_intralink_id",
            "allowed_types__identifiers_identifiers_intralink_type",
            "allowed_types__identifiers_identifiers_intralink_datestamp",
            "allowed_types__identifiers_identifiers_intralink_scratch",
        ],
        "device_file_links": [
            "device_file_link_id",
            "device_file_link_device_id",
            "device_file_link_file_id",
            "device_file_link_type",
            "device_file_link_datestamp",
            "device_file_link_scratch",
        ],
        "year_reprinted": [
            "year_reprinted_id",
            "year_reprinted",
            "year_reprinted_datestamp",
            "year_reprinted_scratch",
        ],
        "creators": [
            "creator_id",
            "creator",
            "creator_sort",
            "creator_short_name",
            "creator_last_name",
            "creator_phash",
            "creator_legal_name",
            "creator_birth_date",
            "creator_death_date",
            "creator_type",
            "creator_seminal_work",
            "creator_one_person",
            "creator_wikipedia",
            "creator_imdb",
            "creator_link",
            "creator_created_datestamp",
            "creator_datestamp",
            "creator_scratch",
        ],
        "book_cover_links": [
            "book_cover_link_id",
            "book_cover_link_book_id",
            "book_cover_link_cover_id",
            "book_cover_link_priority",
            "book_cover_link_type",
            "book_cover_link_datestamp",
            "book_cover_link_scratch",
        ],
    }

    all_tables_and_column_headings = theo_tables_and_columns

    all_known_tables = sorted(theo_tables_and_columns.keys())

    db_tables = all_known_tables
    db_tables_set = set([_ for _ in db_tables])

    all_sorted_tables = sorted(all_known_tables)

    from collections import OrderedDict

    existing_triggers = [
        "update_callback_on_titles",
        "block_insert_on_database_version_table",
        "block_update_on_database_version_table",
        "block_delete_on_database_version_table",
        "fkc_update_titles_custom_column_1_link_a",
        "fkc_update_titles_custom_column_1_link_b",
        "fkc_insert_titles_custom_column_1_link",
        "fkc_delete_titles_custom_column_1_link",
        "fkc_update_books_custom_column_2_link_a",
        "fkc_update_books_custom_column_2_link_b",
        "fkc_insert_books_custom_column_2_link",
        "fkc_delete_books_custom_column_2_link",
        "fkc_insert_custom_column_3",
        "fkc_update_custom_column_3",
        "fkc_update_books_custom_column_4_link_a",
        "fkc_update_books_custom_column_4_link_b",
        "fkc_insert_books_custom_column_4_link",
        "fkc_delete_books_custom_column_4_link",
        "fkc_insert_custom_column_5",
        "fkc_update_custom_column_5",
        "fkc_update_books_custom_column_6_link_a",
        "fkc_update_books_custom_column_6_link_b",
        "fkc_insert_books_custom_column_6_link",
        "fkc_delete_books_custom_column_6_link",
        "fkc_insert_custom_column_7",
        "fkc_update_custom_column_7",
        "fkc_update_books_custom_column_8_link_a",
        "fkc_update_books_custom_column_8_link_b",
        "fkc_insert_books_custom_column_8_link",
        "fkc_delete_books_custom_column_8_link",
        "fkc_insert_custom_column_9",
        "fkc_update_custom_column_9",
        "fkc_insert_custom_column_10",
        "fkc_update_custom_column_10",
        "fkc_insert_custom_column_11",
        "fkc_update_custom_column_11",
        "fkc_update_books_custom_column_12_link_a",
        "fkc_update_books_custom_column_12_link_b",
        "fkc_insert_books_custom_column_12_link",
        "fkc_delete_books_custom_column_12_link",
        "fkc_insert_custom_column_13",
        "fkc_update_custom_column_13",
        "fkc_update_books_custom_column_14_link_a",
        "fkc_update_books_custom_column_14_link_b",
        "fkc_insert_books_custom_column_14_link",
        "fkc_delete_books_custom_column_14_link",
        "fkc_insert_custom_column_15",
        "fkc_update_custom_column_15",
        "fkc_update_books_custom_column_16_link_a",
        "fkc_update_books_custom_column_16_link_b",
        "fkc_insert_books_custom_column_16_link",
        "fkc_delete_books_custom_column_16_link",
        "fkc_insert_custom_column_17",
        "fkc_update_custom_column_17",
        "fkc_update_books_custom_column_18_link_a",
        "fkc_update_books_custom_column_18_link_b",
        "fkc_insert_books_custom_column_18_link",
        "fkc_delete_books_custom_column_18_link",
        "fkc_insert_custom_column_19",
        "fkc_update_custom_column_19",
        "fkc_insert_custom_column_20",
        "fkc_update_custom_column_20",
        "fkc_insert_custom_column_21",
        "fkc_update_custom_column_21",
        "fkc_update_tags_custom_column_22_link_a",
        "fkc_update_tags_custom_column_22_link_b",
        "fkc_insert_tags_custom_column_22_link",
        "fkc_delete_tags_custom_column_22_link",
    ]

    theo_db_main_tables = set(
        [
            "secondary_uuids",
            "folders",
            "words",
            "series",
            "not_series",
            "covers",
            "books",
            "character_introductions",
            "genres",
            "custom_columns",
            "content_levels",
            "series_character_introductions",
            "comments",
            "languages",
            "loc_shelf_numbers",
            "subjects",
            "files",
            "publishers",
            "tags",
            "last_read_positions",
            "synopses",
            "folder_stores",
            "year_first_published",
            "notes",
            "identifiers",
            "devices",
            "books_secondary_uuid",
            "titles",
            "publisher_owners",
            "year_reprinted",
            "feeds",
            "creators",
        ]
    )
    theo_db_interlink_tables = set(
        [
            "creator_title_links",
            "book_year_first_published_links",
            "rating_title_links",
            "comment_title_links",
            "genre_series_links",
            "book_books_secondary_uuid_links",
            "language_title_links",
            "publisher_publisher_owner_links",
            "creator_synopsis_links",
            "file_identifier_links",
            "comment_series_links",
            "cover_creator_links",
            "book_year_reprinted_links",
            "synopsis_title_links",
            "note_series_links",
            "publisher_title_links",
            "identifier_title_links",
            "device_note_links",
            "folder_store_note_links",
            "genre_title_links",
            "creator_series_links",
            "title_word_links",
            "series_tag_links",
            "not_series_title_links",
            "book_folder_links",
            "creator_folder_links",
            "series_series_character_introduction_links",
            "note_title_links",
            "folder_series_links",
            "tag_title_links",
            "series_title_links",
            "comment_creator_links",
            "character_introduction_title_links",
            "subject_title_links",
            "cover_series_links",
            "content_level_title_links",
            "creator_tag_links",
            "file_folder_links",
            "note_publisher_links",
            "loc_shelf_number_title_links",
            "file_publisher_links",
            "file_language_links",
            "secondary_uuid_title_links",
            "device_file_links",
            "creator_language_links",
            "creator_note_links",
            "series_synopsis_links",
            "book_cover_links",
            "book_file_links",
        ]
    )

    theo_custom_columns = {
        "books_custom_column_12_link",
        "books_custom_column_14_link",
        "books_custom_column_16_link",
        "books_custom_column_18_link",
        "books_custom_column_2_link",
        "books_custom_column_4_link",
        "books_custom_column_6_link",
        "books_custom_column_8_link",
        "custom_column_1",
        "custom_column_10",
        "custom_column_11",
        "custom_column_12",
        "custom_column_13",
        "custom_column_14",
        "custom_column_15",
        "custom_column_16",
        "custom_column_17",
        "custom_column_18",
        "custom_column_19",
        "custom_column_2",
        "custom_column_20",
        "custom_column_21",
        "custom_column_22",
        "custom_column_3",
        "custom_column_4",
        "custom_column_5",
        "custom_column_6",
        "custom_column_7",
        "custom_column_8",
        "custom_column_9",
        "tags_custom_column_22_link",
        "titles_custom_column_1_link",
    }

    # Todo: This does not, but needs to, include tags_custom_column_22_link and titles_custom_column_1_link
    theo_cc_columns_map = OrderedDict(
        [
            (
                "books_custom_column_12_link",
                [
                    "books_custom_column_12_link_id",
                    "books_custom_column_12_link_book",
                    "books_custom_column_12_link_value",
                ],
            ),
            (
                "books_custom_column_14_link",
                [
                    "books_custom_column_14_link_id",
                    "books_custom_column_14_link_book",
                    "books_custom_column_14_link_value",
                ],
            ),
            (
                "books_custom_column_16_link",
                [
                    "books_custom_column_16_link_id",
                    "books_custom_column_16_link_book",
                    "books_custom_column_16_link_value",
                    "books_custom_column_16_link_extra",
                ],
            ),
            (
                "books_custom_column_18_link",
                [
                    "books_custom_column_18_link_id",
                    "books_custom_column_18_link_book",
                    "books_custom_column_18_link_value",
                ],
            ),
            (
                "books_custom_column_2_link",
                [
                    "books_custom_column_2_link_id",
                    "books_custom_column_2_link_book",
                    "books_custom_column_2_link_value",
                ],
            ),
            (
                "books_custom_column_4_link",
                [
                    "books_custom_column_4_link_id",
                    "books_custom_column_4_link_book",
                    "books_custom_column_4_link_value",
                ],
            ),
            (
                "books_custom_column_6_link",
                [
                    "books_custom_column_6_link_id",
                    "books_custom_column_6_link_book",
                    "books_custom_column_6_link_value",
                    "books_custom_column_6_link_extra",
                ],
            ),
            (
                "books_custom_column_8_link",
                [
                    "books_custom_column_8_link_id",
                    "books_custom_column_8_link_book",
                    "books_custom_column_8_link_value",
                ],
            ),
            ("custom_column_1", ["custom_column_1_id", "custom_column_1_value"]),
            (
                "custom_column_10",
                [
                    "custom_column_10_id",
                    "custom_column_10_book",
                    "custom_column_10_value",
                ],
            ),
            (
                "custom_column_11",
                [
                    "custom_column_11_id",
                    "custom_column_11_book",
                    "custom_column_11_value",
                ],
            ),
            ("custom_column_12", ["custom_column_12_id", "custom_column_12_value"]),
            (
                "custom_column_13",
                [
                    "custom_column_13_id",
                    "custom_column_13_book",
                    "custom_column_13_value",
                ],
            ),
            ("custom_column_14", ["custom_column_14_id", "custom_column_14_value"]),
            (
                "custom_column_15",
                [
                    "custom_column_15_id",
                    "custom_column_15_book",
                    "custom_column_15_value",
                ],
            ),
            ("custom_column_16", ["custom_column_16_id", "custom_column_16_value"]),
            (
                "custom_column_17",
                [
                    "custom_column_17_id",
                    "custom_column_17_book",
                    "custom_column_17_value",
                ],
            ),
            ("custom_column_18", ["custom_column_18_id", "custom_column_18_value"]),
            (
                "custom_column_19",
                [
                    "custom_column_19_id",
                    "custom_column_19_book",
                    "custom_column_19_value",
                ],
            ),
            ("custom_column_2", ["custom_column_2_id", "custom_column_2_value"]),
            (
                "custom_column_20",
                [
                    "custom_column_20_id",
                    "custom_column_20_book",
                    "custom_column_20_value",
                ],
            ),
            (
                "custom_column_21",
                [
                    "custom_column_21_id",
                    "custom_column_21_book",
                    "custom_column_21_value",
                ],
            ),
            ("custom_column_22", ["custom_column_22_id", "custom_column_22_value"]),
            (
                "custom_column_3",
                [
                    "custom_column_3_id",
                    "custom_column_3_book",
                    "custom_column_3_value",
                ],
            ),
            ("custom_column_4", ["custom_column_4_id", "custom_column_4_value"]),
            (
                "custom_column_5",
                [
                    "custom_column_5_id",
                    "custom_column_5_book",
                    "custom_column_5_value",
                ],
            ),
            ("custom_column_6", ["custom_column_6_id", "custom_column_6_value"]),
            (
                "custom_column_7",
                [
                    "custom_column_7_id",
                    "custom_column_7_book",
                    "custom_column_7_value",
                ],
            ),
            ("custom_column_8", ["custom_column_8_id", "custom_column_8_value"]),
            (
                "custom_column_9",
                [
                    "custom_column_9_id",
                    "custom_column_9_book",
                    "custom_column_9_value",
                ],
            ),
            (
                "tags_custom_column_22_link",
                [
                    "tags_custom_column_22_link_id",
                    "tags_custom_column_22_link_book",
                    "tags_custom_column_22_link_value",
                ],
            ),
            (
                "titles_custom_column_1_link",
                [
                    "titles_custom_column_1_link_id",
                    "titles_custom_column_1_link_book",
                    "titles_custom_column_1_link_value",
                ],
            ),
        ]
    )

    # Todo: Scrub the datestamp column from this
    # Cannot add the same values multiple times to a text based custom column - text appears to be basically tag like
    # Todo: Would really like the bool values to be integers - or bools on the database
    # Todo: display seems to be fundamentally broken
    # From cc 12 on, all values should be multiple - unless it cannot be - due to the datatype
    cc_data_dict = OrderedDict(
        [
            (
                1,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "do_not_read",
                    "custom_column_id": 1,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "titles__do_not_read",
                    "custom_column_in_table": "titles",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                2,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "rating",
                    "custom_column_name": "books_cc_2_do_not_read_rating_not_multiple",
                    "custom_column_id": 2,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_2_do_not_read_rating_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                3,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "int",
                    "custom_column_name": "books_cc_3_do_not_read_int_not_multiple",
                    "custom_column_id": 3,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_3_do_not_read_int_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                4,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "books_cc_4_do_not_read_text_not_multiple",
                    "custom_column_id": 4,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_4_do_not_read_text_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                5,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "comments",
                    "custom_column_name": "books_cc_5_do_not_read_comments_not_multiple",
                    "custom_column_id": 5,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_5_do_not_read_comments_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                6,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "series",
                    "custom_column_name": "books_cc_6_do_not_read_series_not_multiple",
                    "custom_column_id": 6,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_6_do_not_read_series_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                7,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "composite",
                    "custom_column_name": "books_cc_7_do_not_read_composite_not_multiple",
                    "custom_column_id": 7,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_7_do_not_read_composite_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                8,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "enumeration",
                    "custom_column_name": "books_cc_8_do_not_read_enumeration_not_multiple",
                    "custom_column_id": 8,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_8_do_not_read_enumeration_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                9,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "float",
                    "custom_column_name": "books_cc_9_do_not_read_float_not_multiple",
                    "custom_column_id": 9,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_9_do_not_read_float_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                10,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "datetime",
                    "custom_column_name": "books_cc_10_do_not_read_datetime_not_multiple",
                    "custom_column_id": 10,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_10_do_not_read_datetime_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                11,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "bool",
                    "custom_column_name": "books_cc_11_do_not_read_bool_not_multiple",
                    "custom_column_id": 11,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_11_do_not_read_bool_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                12,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "rating",
                    "custom_column_name": "books_cc_12_do_not_read_rating_multiple",
                    "custom_column_id": 12,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_12_do_not_read_rating_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                13,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "int",
                    "custom_column_name": "books_cc_13_do_not_read_int_multiple",
                    "custom_column_id": 13,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_13_do_not_read_int_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                14,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "books_cc_14_do_not_read_text_multiple",
                    "custom_column_id": 14,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_14_do_not_read_text_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            # Todo: There should probably be a link table so that there can be multiple comments to a title?
            (
                15,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "comments",
                    "custom_column_name": "books_cc_15_do_not_read_comments_multiple",
                    "custom_column_id": 15,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_15_do_not_read_comments_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                16,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "series",
                    "custom_column_name": "books_cc_16_do_not_read_series_multiple",
                    "custom_column_id": 16,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_16_do_not_read_series_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                17,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "composite",
                    "custom_column_name": "books_cc_17_do_not_read_composite_multiple",
                    "custom_column_id": 17,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_17_do_not_read_composite_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                18,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "enumeration",
                    "custom_column_name": "books_cc_18_do_not_read_enumeration_multiple",
                    "custom_column_id": 18,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_18_do_not_read_enumeration_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                19,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "float",
                    "custom_column_name": "books_cc_19_do_not_read_float_multiple",
                    "custom_column_id": 19,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_19_do_not_read_float_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                20,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "datetime",
                    "custom_column_name": "books_cc_20_do_not_read_datetime_multiple",
                    "custom_column_id": 20,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_20_do_not_read_datetime_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                21,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "bool",
                    "custom_column_name": "books_cc_21_do_not_read_bool_multiple",
                    "custom_column_id": 21,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_21_do_not_read_bool_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                22,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "really_do_not_read",
                    "custom_column_id": 22,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "tags__really_do_not_read",
                    "custom_column_in_table": "tags",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
        ]
    )
