from .common_db_properties import (
    CommonDBProperties,
)


class TestDB25Properties(CommonDBProperties):

    alpha_focus_row_counts = {
        "database_version": 1,
        "works": 30,
        "series": 1,
        "expressions": 30,
        "manifestations": 30,
        "items": 30,
        "files": 0,
        "agents": 1,
        "labels": 0,
    }

    theo_tables_and_columns = {
        "creator_title_links": [
            "creator_title_link_id",
            "creator_title_link_creator_id",
            "creator_title_link_title_id",
            "creator_title_link_priority",
            "creator_title_link_type",
            "creator_title_link_datestamp",
            "creator_title_link_scratch",
        ],
        "tag_tag_intralinks": [
            "tag_tag_intralink_id",
            "tag_tag_intralink_primary_id",
            "tag_tag_intralink_secondary_id",
            "tag_tag_intralink_type",
            "tag_tag_intralink_datestamp",
            "tag_tag_intralink_scratch",
        ],
        "language_title_links": [
            "language_title_link_id",
            "language_title_link_language_id",
            "language_title_link_title_id",
            "language_title_link_priority",
            "language_title_link_type",
            "language_title_link_datestamp",
            "language_title_link_scratch",
        ],
        "creator_creator_intralinks": [
            "creator_creator_intralink_id",
            "creator_creator_intralink_primary_id",
            "creator_creator_intralink_secondary_id",
            "creator_creator_intralink_type",
            "creator_creator_intralink_datestamp",
            "creator_creator_intralink_scratch",
        ],
        "new_books": [
            "new_book_id",
            "new_book_name",
            "new_book_extension",
            "new_book_path",
            "new_book_hash_1",
            "new_book_hash_2",
            "new_book_size",
            "new_book_group_id",
            "new_book_cached",
            "new_book_cache_attempted",
            "new_book_datestamp",
            "new_book_scratch",
        ],
        "identifier_title_links": [
            "identifier_title_link_id",
            "identifier_title_link_identifier_id",
            "identifier_title_link_title_id",
            "identifier_title_link_priority",
            "identifier_title_link_type",
            "identifier_title_link_datestamp",
            "identifier_title_link_scratch",
        ],
        "allowed_types__publishers_publishers_intralinks": [
            "allowed_types__publishers_publishers_intralink_id",
            "allowed_types__publishers_publishers_intralink_type",
            "allowed_types__publishers_publishers_intralink_datestamp",
            "allowed_types__publishers_publishers_intralink_scratch",
        ],
        "books_custom_column_8_link": [
            "books_custom_column_8_link_id",
            "books_custom_column_8_link_book",
            "books_custom_column_8_link_value",
        ],
        "allowed_types__creators_creators_intralinks": [
            "allowed_types__creators_creators_intralink_id",
            "allowed_types__creators_creators_intralink_type",
            "allowed_types__creators_creators_intralink_datestamp",
            "allowed_types__creators_creators_intralink_scratch",
        ],
        "allowed_types__note_title_links": [
            "allowed_types__note_title_link_id",
            "allowed_types__note_title_link_type",
            "allowed_types__note_title_link_datestamp",
            "allowed_types__note_title_link_scratch",
        ],
        "compressed_files": [
            "compressed_file_id",
            "compressed_file_name",
            "compressed_file_extension",
            "compressed_file_path",
            "compressed_file_hash_1",
            "compressed_file_hash_2",
            "compressed_file_size",
            "compressed_file_group_id",
            "compressed_file_folder",
            "compressed_file_cached",
            "compressed_file_cache_attempted",
            "compressed_file_datestamp",
            "compressed_file_scratch",
        ],
        "note_series_links": [
            "note_series_link_id",
            "note_series_link_note_id",
            "note_series_link_series_id",
            "note_series_link_priority",
            "note_series_link_datestamp",
            "note_series_link_scratch",
        ],
        "languages": [
            "language_id",
            "language",
            "language_code",
            "language_datestamp",
            "language_scratch",
        ],
        "database_version": [
            "database_version_id",
            "database_version_version",
            "database_version_datestamp",
        ],
        "allowed_types__identifier_title_links": [
            "allowed_types__identifier_title_link_id",
            "allowed_types__identifier_title_link_type",
            "allowed_types__identifier_title_link_datestamp",
            "allowed_types__identifier_title_link_scratch",
        ],
        "books_custom_column_6_link": [
            "books_custom_column_6_link_id",
            "books_custom_column_6_link_book",
            "books_custom_column_6_link_value",
            "books_custom_column_6_link_extra",
        ],
        "file_file_intralinks": [
            "file_file_intralink_id",
            "file_file_intralink_primary_id",
            "file_file_intralink_secondary_id",
            "file_file_intralink_type",
            "file_file_intralink_datestamp",
            "file_file_intralink_scratch",
        ],
        "books_custom_column_4_link": [
            "books_custom_column_4_link_id",
            "books_custom_column_4_link_book",
            "books_custom_column_4_link_value",
        ],
        "file_folder_links": [
            "file_folder_link_id",
            "file_folder_link_file_id",
            "file_folder_link_folder_id",
            "file_folder_link_datestamp",
            "file_folder_link_scratch",
        ],
        "title_title_intralinks": [
            "title_title_intralink_id",
            "title_title_intralink_primary_id",
            "title_title_intralink_secondary_id",
            "title_title_intralink_type",
            "title_title_intralink_datestamp",
            "title_title_intralink_scratch",
        ],
        "notes": ["note_id", "note", "note_datestamp", "note_scratch"],
        "metadata_dirtied_books": [
            "metadata_dirtied_book_id",
            "metadata_dirtied_book",
        ],
        "conversion_options": [
            "conversion_option_id",
            "conversion_option_format",
            "conversion_option_book",
            "conversion_option_data",
            "conversion_option_datestamp",
        ],
        "allowed_types__files_files_intralinks": [
            "allowed_types__files_files_intralink_id",
            "allowed_types__files_files_intralink_type",
            "allowed_types__files_files_intralink_datestamp",
            "allowed_types__files_files_intralink_scratch",
        ],
        "feeds": [
            "feed_id",
            "feed_title",
            "feed_script",
            "feed_created_datestamp",
            "feed_datestamp",
            "feed_scratch",
        ],
        "library_id": ["library_id", "library_id_uuid", "library_id_datestamp"],
        "sqlite_sequence": ["name", "seq"],
        "publishers": [
            "publisher_id",
            "publisher",
            "publisher_sort",
            "publisher_phash",
            "publisher_wikipedia",
            "publisher_website",
            "publisher_parent",
            "publisher_position",
            "publisher_tree_id",
            "publisher_full",
            "publisher_created_datestamp",
            "publisher_datestamp",
            "publisher_scratch",
        ],
        "series": [
            "series_id",
            "series",
            "series_sort",
            "series_phash",
            "series_over_author",
            "series_parent",
            "series_parent_position",
            "series_tree_id",
            "series_full",
            "series_datestamp",
            "series_scratch",
        ],
        "allowed_types__folder_stores_folder_stores_intralinks": [
            "allowed_types__folder_stores_folder_stores_intralink_id",
            "allowed_types__folder_stores_folder_stores_intralink_type",
            "allowed_types__folder_stores_folder_stores_intralink_datestamp",
            "allowed_types__folder_stores_folder_stores_intralink_scratch",
        ],
        "books": [
            "book_id",
            "book_sort",
            "book_flags",
            "book_pubdate",
            "book_copyright_date",
            "book_uuid",
            "book_has_cover",
            "book_has_local_cover",
            "book_last_modified",
            "book_fingerprint",
            "book_paths",
            "book_size",
            "book_rating",
            "book_created_datestamp",
            "book_datestamp",
            "book_scratch",
        ],
        "devices": [
            "device_id",
            "device_type",
            "device_created_datestamp",
            "device_datestamp",
            "device_scratch",
        ],
        "preferences": [
            "preference_id",
            "preference_key",
            "preference_value",
            "preference_value_type",
            "preference_parent_LiuXin_instance",
            "preference_datestamp",
            "preference_scratch",
        ],
        "publisher_title_links": [
            "publisher_title_link_id",
            "publisher_title_link_publisher_id",
            "publisher_title_link_title_id",
            "publisher_title_link_priority",
            "publisher_title_link_datestamp",
            "publisher_title_link_scratch",
        ],
        "comments": [
            "comment_id",
            "comment",
            "comment_datestamp",
            "comment_scratch",
        ],
        "custom_column_22": ["custom_column_22_id", "custom_column_22_value"],
        "custom_column_21": [
            "custom_column_21_id",
            "custom_column_21_book",
            "custom_column_21_value",
        ],
        "custom_column_20": [
            "custom_column_20_id",
            "custom_column_20_book",
            "custom_column_20_value",
        ],
        "book_folder_links": [
            "book_folder_link_id",
            "book_folder_link_book_id",
            "book_folder_link_folder_id",
            "book_folder_link_priority",
            "book_folder_link_datestamp",
            "book_folder_link_scratch",
        ],
        "custom_column_8": ["custom_column_8_id", "custom_column_8_value"],
        "series_synopsis_links": [
            "series_synopsis_link_id",
            "series_synopsis_link_series_id",
            "series_synopsis_link_synopsis_id",
            "series_synopsis_link_priority",
            "series_synopsis_link_datestamp",
            "series_synopsis_link_scratch",
        ],
        "allowed_types__creator_series_links": [
            "allowed_types__creator_series_link_id",
            "allowed_types__creator_series_link_type",
            "allowed_types__creator_series_link_datestamp",
            "allowed_types__creator_series_link_scratch",
        ],
        "books_plugin_data": [
            "book_plugin_data_id",
            "book_plugin_data_book",
            "book_plugin_data_name",
            "book_plugin_data_val",
            "book_plugin_created_datestamp",
            "book_plugin_datestamp",
            "book_plugin_scratch",
        ],
        "tags": ["tag_id", "tag", "tag_phash", "tag_datestamp", "tag_scratch"],
        "synopsis_title_links": [
            "synopsis_title_link_id",
            "synopsis_title_link_synopsis_id",
            "synopsis_title_link_title_id",
            "synopsis_title_link_priority",
            "synopsis_title_link_datestamp",
            "synopsis_title_link_scratch",
        ],
        "comment_creator_links": [
            "comment_creator_link_id",
            "comment_creator_link_comment_id",
            "comment_creator_link_creator_id",
            "comment_creator_link_priority",
            "comment_creator_link_type",
            "comment_creator_link_datestamp",
            "comment_creator_link_scratch",
        ],
        "synopses": [
            "synopsis_id",
            "synopsis",
            "synopsis_datestamp",
            "synopsis_scratch",
        ],
        "books_custom_column_2_link": [
            "books_custom_column_2_link_id",
            "books_custom_column_2_link_book",
            "books_custom_column_2_link_value",
        ],
        "database_metadata": [
            "database_metadata_id",
            "database_metadata_unique_id",
            "database_metadata_parent_LiuXin_instance",
            "database_metadata_db_name",
            "database_metadata_datestamp",
            "database_metadata_scratch",
        ],
        "allowed_types__comment_series_links": [
            "allowed_types__comment_series_link_id",
            "allowed_types__comment_series_link_type",
            "allowed_types__comment_series_link_datestamp",
            "allowed_types__comment_series_link_scratch",
        ],
        "folder_stores": [
            "folder_store_id",
            "folder_store",
            "folder_store_identifier",
            "folder_store_path",
            "folder_store_path_os_type",
            "folder_store_created",
            "folder_store_media_types",
            "folder_store_forbidden_print",
            "folder_store_preferred_print",
            "folder_store_cache",
            "folder_store_storage",
            "folder_store_cf_expansion",
            "folder_store_cache_priority",
            "folder_store_max_path_length",
            "folder_store_user_name",
            "folder_store_password",
            "folder_store_type",
            "folder_store_marker_name",
            "folder_store_marker_text",
            "folder_store_marker_path",
            "folder_store_marker_path_os_type",
            "folder_store_dedicated_drive",
            "folder_store_max_size",
            "folder_store_found",
            "folder_store_readable",
            "folder_store_writeable",
            "folder_store_size",
            "folder_store_free_size",
            "folder_store_creation_date",
            "folder_store_created_datestamp",
            "folder_store_datestamp",
            "folder_store_scratch",
        ],
        "custom_column_16": ["custom_column_16_id", "custom_column_16_value"],
        "creator_language_links": [
            "creator_language_link_id",
            "creator_language_link_creator_id",
            "creator_language_link_language_id",
            "creator_language_link_datestamp",
            "creator_language_link_scratch",
        ],
        "custom_column_14": ["custom_column_14_id", "custom_column_14_value"],
        "identifier_identifier_intralinks": [
            "identifier_identifier_intralink_id",
            "identifier_identifier_intralink_primary_id",
            "identifier_identifier_intralink_secondary_id",
            "identifier_identifier_intralink_type",
            "identifier_identifier_intralink_datestamp",
            "identifier_identifier_intralink_scratch",
        ],
        "custom_column_12": ["custom_column_12_id", "custom_column_12_value"],
        "custom_column_13": [
            "custom_column_13_id",
            "custom_column_13_book",
            "custom_column_13_value",
        ],
        "custom_column_10": [
            "custom_column_10_id",
            "custom_column_10_book",
            "custom_column_10_value",
        ],
        "creator_note_links": [
            "creator_note_link_id",
            "creator_note_link_creator_id",
            "creator_note_link_note_id",
            "creator_note_link_priority",
            "creator_note_link_type",
            "creator_note_link_datestamp",
            "creator_note_link_scratch",
        ],
        "custom_column_3": [
            "custom_column_3_id",
            "custom_column_3_book",
            "custom_column_3_value",
        ],
        "custom_column_15": [
            "custom_column_15_id",
            "custom_column_15_book",
            "custom_column_15_value",
        ],
        "custom_column_18": ["custom_column_18_id", "custom_column_18_value"],
        "custom_column_19": [
            "custom_column_19_id",
            "custom_column_19_book",
            "custom_column_19_value",
        ],
        "allowed_types__language_title_links": [
            "allowed_types__language_title_link_id",
            "allowed_types__language_title_link_type",
            "allowed_types__language_title_link_datestamp",
            "allowed_types__language_title_link_scratch",
        ],
        "publisher_publisher_intralinks": [
            "publisher_publisher_intralink_id",
            "publisher_publisher_intralink_primary_id",
            "publisher_publisher_intralink_secondary_id",
            "publisher_publisher_intralink_type",
            "publisher_publisher_intralink_datestamp",
            "publisher_publisher_intralink_scratch",
        ],
        "tags_custom_column_22_link": [
            "tags_custom_column_22_link_id",
            "tags_custom_column_22_link_book",
            "tags_custom_column_22_link_value",
        ],
        "hashes": ["hash_id", "hash"],
        "custom_columns": [
            "custom_column_id",
            "custom_column_mark_for_delete",
            "custom_column_in_table",
            "custom_column_label",
            "custom_column_name",
            "custom_column_datatype",
            "custom_column_db_datatype",
            "custom_column_editable",
            "custom_column_display",
            "custom_column_normalized",
            "custom_column_is_multiple",
            "custom_column_ordered",
            "custom_column_datestamp",
            "custom_column_scratch",
        ],
        "folder_store_note_links": [
            "folder_store_note_link_id",
            "folder_store_note_link_folder_store_id",
            "folder_store_note_link_note_id",
            "folder_store_note_link_priority",
            "folder_store_note_link_datestamp",
            "folder_store_note_link_scratch",
        ],
        "genre_title_links": [
            "genre_title_link_id",
            "genre_title_link_genre_id",
            "genre_title_link_title_id",
            "genre_title_link_priority",
            "genre_title_link_datestamp",
            "genre_title_link_scratch",
        ],
        "comment_title_links": [
            "comment_title_link_id",
            "comment_title_link_comment_id",
            "comment_title_link_title_id",
            "comment_title_link_priority",
            "comment_title_link_type",
            "comment_title_link_datestamp",
            "comment_title_link_scratch",
        ],
        "series_tag_links": [
            "series_tag_link_id",
            "series_tag_link_series_id",
            "series_tag_link_tag_id",
            "series_tag_link_datestamp",
            "series_tag_link_scratch",
        ],
        "allowed_types__file_identifier_links": [
            "allowed_types__file_identifier_link_id",
            "allowed_types__file_identifier_link_type",
            "allowed_types__file_identifier_link_datestamp",
            "allowed_types__file_identifier_link_scratch",
        ],
        "folder_store_folder_store_intralinks": [
            "folder_store_folder_store_intralink_id",
            "folder_store_folder_store_intralink_primary_id",
            "folder_store_folder_store_intralink_secondary_id",
            "folder_store_folder_store_intralink_type",
            "folder_store_folder_store_intralink_datestamp",
            "folder_store_folder_store_intralink_scratch",
        ],
        "files": [
            "file_id",
            "file_name",
            "file_base_name",
            "file_tag",
            "file_extension",
            "file_path",
            "file_auto_name",
            "file_use_auto_name",
            "file_size",
            "file_hash",
            "file_new_hash",
            "file_corrupt",
            "file_base_folder",
            "file_acquired_timestamp",
            "file_source",
            "file_original_name",
            "file_original_path",
            "file_phash",
            "file_anthology",
            "file_critical",
            "file_parent",
            "file_conversion_settings",
            "file_processed",
            "file_created_datestamp",
            "file_datestamp",
            "file_scratch",
        ],
        "creator_folder_links": [
            "creator_folder_link_id",
            "creator_folder_link_creator_id",
            "creator_folder_link_folder_id",
            "creator_folder_link_priority",
            "creator_folder_link_datestamp",
            "creator_folder_link_scratch",
        ],
        "allowed_types__rating_title_links": [
            "allowed_types__rating_title_link_id",
            "allowed_types__rating_title_link_type",
            "allowed_types__rating_title_link_datestamp",
            "allowed_types__rating_title_link_scratch",
        ],
        "note_title_links": [
            "note_title_link_id",
            "note_title_link_note_id",
            "note_title_link_title_id",
            "note_title_link_priority",
            "note_title_link_type",
            "note_title_link_datestamp",
            "note_title_link_scratch",
        ],
        "allowed_types__comment_creator_links": [
            "allowed_types__comment_creator_link_id",
            "allowed_types__comment_creator_link_type",
            "allowed_types__comment_creator_link_datestamp",
            "allowed_types__comment_creator_link_scratch",
        ],
        "tag_title_links": [
            "tag_title_link_id",
            "tag_title_link_tag_id",
            "tag_title_link_title_id",
            "tag_title_link_datestamp",
            "tag_title_link_scratch",
        ],
        "titles_custom_column_1_link": [
            "titles_custom_column_1_link_id",
            "titles_custom_column_1_link_book",
            "titles_custom_column_1_link_value",
        ],
        "creator_tag_links": [
            "creator_tag_link_id",
            "creator_tag_link_creator_id",
            "creator_tag_link_tag_id",
            "creator_tag_link_datestamp",
            "creator_tag_link_scratch",
        ],
        "note_publisher_links": [
            "note_publisher_link_id",
            "note_publisher_link_note_id",
            "note_publisher_link_publisher_id",
            "note_publisher_link_priority",
            "note_publisher_link_datestamp",
            "note_publisher_link_scratch",
        ],
        "books_custom_column_14_link": [
            "books_custom_column_14_link_id",
            "books_custom_column_14_link_book",
            "books_custom_column_14_link_value",
        ],
        "file_publisher_links": [
            "file_publisher_link_id",
            "file_publisher_link_file_id",
            "file_publisher_link_publisher_id",
            "file_publisher_link_datestamp",
            "file_publisher_link_scratch",
        ],
        "file_language_links": [
            "file_language_link_id",
            "file_language_link_file_id",
            "file_language_link_language_id",
            "file_language_link_datestamp",
            "file_language_link_scratch",
        ],
        "titles": [
            "title_id",
            "title",
            "title_sort",
            "title_phash",
            "title_creator_sort",
            "title_pub_date",
            "title_copyright_date",
            "title_wikipedia",
            "title_fiction_length_category",
            "title_type",
            "title_wordcount",
            "title_source",
            "title_source_path",
            "title_source_name",
            "title_created_datestamp",
            "title_datestamp",
            "title_last_modified",
            "title_scratch",
        ],
        "allowed_types__titles_titles_intralinks": [
            "allowed_types__titles_titles_intralink_id",
            "allowed_types__titles_titles_intralink_type",
            "allowed_types__titles_titles_intralink_datestamp",
            "allowed_types__titles_titles_intralink_scratch",
        ],
        "custom_column_9": [
            "custom_column_9_id",
            "custom_column_9_book",
            "custom_column_9_value",
        ],
        "custom_column_4": ["custom_column_4_id", "custom_column_4_value"],
        "custom_column_5": [
            "custom_column_5_id",
            "custom_column_5_book",
            "custom_column_5_value",
        ],
        "custom_column_6": ["custom_column_6_id", "custom_column_6_value"],
        "custom_column_7": [
            "custom_column_7_id",
            "custom_column_7_book",
            "custom_column_7_value",
        ],
        "allowed_types__creator_note_links": [
            "allowed_types__creator_note_link_id",
            "allowed_types__creator_note_link_type",
            "allowed_types__creator_note_link_datestamp",
            "allowed_types__creator_note_link_scratch",
        ],
        "custom_column_1": ["custom_column_1_id", "custom_column_1_value"],
        "custom_column_2": ["custom_column_2_id", "custom_column_2_value"],
        "creator_synopsis_links": [
            "creator_synopsis_link_id",
            "creator_synopsis_link_creator_id",
            "creator_synopsis_link_synopsis_id",
            "creator_synopsis_link_datestamp",
            "creator_synopsis_link_scratch",
        ],
        "allowed_types__tags_tags_intralinks": [
            "allowed_types__tags_tags_intralink_id",
            "allowed_types__tags_tags_intralink_type",
            "allowed_types__tags_tags_intralink_datestamp",
            "allowed_types__tags_tags_intralink_scratch",
        ],
        "rating_title_links": [
            "rating_title_link_id",
            "rating_title_link_rating_id",
            "rating_title_link_title_id",
            "rating_title_link_type",
            "rating_title_link_datestamp",
            "rating_title_link_scratch",
        ],
        "allowed_types__covers_covers_intralinks": [
            "allowed_types__covers_covers_intralink_id",
            "allowed_types__covers_covers_intralink_type",
            "allowed_types__covers_covers_intralink_datestamp",
            "allowed_types__covers_covers_intralink_scratch",
        ],
        "covers": [
            "cover_id",
            "cover_name",
            "cover_extension",
            "cover_path",
            "cover_use_auto_name",
            "cover_hash",
            "cover_new_hash",
            "cover_corrupt",
            "cover_original_path",
            "cover_local",
            "cover_base_folder",
            "cover_created_datestamp",
            "cover_datestamp",
            "cover_scratch",
        ],
        "book_file_links": [
            "book_file_link_id",
            "book_file_link_book_id",
            "book_file_link_file_id",
            "book_file_link_priority",
            "book_file_link_datestamp",
            "book_file_link_scratch",
        ],
        "file_identifier_links": [
            "file_identifier_link_id",
            "file_identifier_link_file_id",
            "file_identifier_link_identifier_id",
            "file_identifier_link_priority",
            "file_identifier_link_type",
            "file_identifier_link_datestamp",
            "file_identifier_link_scratch",
        ],
        "cover_creator_links": [
            "cover_creator_link_id",
            "cover_creator_link_cover_id",
            "cover_creator_link_creator_id",
            "cover_creator_link_priority",
            "cover_creator_link_datestamp",
            "cover_creator_link_scratch",
        ],
        "ratings": [
            "rating_id",
            "rating",
            "rating_source",
            "rating_datestamp",
            "rating_scratch",
        ],
        "genres": [
            "genre_id",
            "genre",
            "genre_sort",
            "genre_phash",
            "genre_parent",
            "genre_position",
            "genre_tree_id",
            "genre_full",
            "genre_datestamp",
            "genre_scratch",
        ],
        "custom_column_17": [
            "custom_column_17_id",
            "custom_column_17_book",
            "custom_column_17_value",
        ],
        "creator_series_links": [
            "creator_series_link_id",
            "creator_series_link_creator_id",
            "creator_series_link_series_id",
            "creator_series_link_type",
            "creator_series_link_datestamp",
            "creator_series_link_scratch",
        ],
        "last_read_positions": [
            "id",
            "book",
            "format",
            "user",
            "device",
            "cfi",
            "epoch",
            "pos_frac",
        ],
        "device_note_links": [
            "device_note_link_id",
            "device_note_link_device_id",
            "device_note_link_note_id",
            "device_note_link_priority",
            "device_note_link_datestamp",
            "device_note_link_scratch",
        ],
        "subjects": [
            "subject_id",
            "subject",
            "subject_phash",
            "subject_sort",
            "subject_parent",
            "subject_parent_position",
            "subject_tree_id",
            "subject_full",
            "subject_datestamp",
            "subject_scratch",
        ],
        "books_custom_column_16_link": [
            "books_custom_column_16_link_id",
            "books_custom_column_16_link_book",
            "books_custom_column_16_link_value",
            "books_custom_column_16_link_extra",
        ],
        "allowed_types__creator_title_links": [
            "allowed_types__creator_title_link_id",
            "allowed_types__creator_title_link_type",
            "allowed_types__creator_title_link_datestamp",
            "allowed_types__creator_title_link_scratch",
        ],
        "folders": [
            "folder_id",
            "folder_name",
            "folder_tag",
            "folder_original_name",
            "folder_auto_name",
            "folder_use_auto_name",
            "folder_path",
            "folder_auto_position",
            "folder_found",
            "folder_folder_store_id",
            "folder_parent",
            "folder_depth",
            "folder_size",
            "folder_hash",
            "folder_types",
            "folder_created_datestamp",
            "folder_datestamp",
            "folder_scratch",
        ],
        "books_custom_column_18_link": [
            "books_custom_column_18_link_id",
            "books_custom_column_18_link_book",
            "books_custom_column_18_link_value",
        ],
        "allowed_types__device_file_links": [
            "allowed_types__device_file_link_id",
            "allowed_types__device_file_link_type",
            "allowed_types__device_file_link_datestamp",
            "allowed_types__device_file_link_scratch",
        ],
        "allowed_types__book_cover_links": [
            "allowed_types__book_cover_link_id",
            "allowed_types__book_cover_link_type",
            "allowed_types__book_cover_link_datestamp",
            "allowed_types__book_cover_link_scratch",
        ],
        "custom_column_11": [
            "custom_column_11_id",
            "custom_column_11_book",
            "custom_column_11_value",
        ],
        "folder_series_links": [
            "folder_series_link_id",
            "folder_series_link_folder_id",
            "folder_series_link_series_id",
            "folder_series_link_priority",
            "folder_series_link_datestamp",
            "folder_series_link_scratch",
        ],
        "series_title_links": [
            "series_title_link_id",
            "series_title_link_series_id",
            "series_title_link_title_id",
            "series_title_link_priority",
            "series_title_link_index",
            "series_title_link_datestamp",
            "series_title_link_scratch",
        ],
        "cover_cover_intralinks": [
            "cover_cover_intralink_id",
            "cover_cover_intralink_primary_id",
            "cover_cover_intralink_secondary_id",
            "cover_cover_intralink_type",
            "cover_cover_intralink_datestamp",
            "cover_cover_intralink_scratch",
        ],
        "genre_series_links": [
            "genre_series_link_id",
            "genre_series_link_genre_id",
            "genre_series_link_series_id",
            "genre_series_link_priority",
            "genre_series_link_datestamp",
            "genre_series_link_scratch",
        ],
        "subject_title_links": [
            "subject_title_link_id",
            "subject_title_link_subject_id",
            "subject_title_link_title_id",
            "subject_title_link_priority",
            "subject_title_link_datestamp",
            "subject_title_link_scratch",
        ],
        "cover_series_links": [
            "cover_series_link_id",
            "cover_series_link_cover_id",
            "cover_series_link_series_id",
            "cover_series_link_priority",
            "cover_series_link_datestamp",
            "cover_series_link_scratch",
        ],
        "books_custom_column_12_link": [
            "books_custom_column_12_link_id",
            "books_custom_column_12_link_book",
            "books_custom_column_12_link_value",
        ],
        "identifiers": [
            "identifier_id",
            "identifier",
            "identifier_type",
            "identifier_datestamp",
            "identifier_scratch",
        ],
        "comment_series_links": [
            "comment_series_link_id",
            "comment_series_link_comment_id",
            "comment_series_link_series_id",
            "comment_series_link_priority",
            "comment_series_link_type",
            "comment_series_link_datestamp",
            "comment_series_link_scratch",
        ],
        "allowed_types__comment_title_links": [
            "allowed_types__comment_title_link_id",
            "allowed_types__comment_title_link_type",
            "allowed_types__comment_title_link_datestamp",
            "allowed_types__comment_title_link_scratch",
        ],
        "allowed_types__identifiers_identifiers_intralinks": [
            "allowed_types__identifiers_identifiers_intralink_id",
            "allowed_types__identifiers_identifiers_intralink_type",
            "allowed_types__identifiers_identifiers_intralink_datestamp",
            "allowed_types__identifiers_identifiers_intralink_scratch",
        ],
        "device_file_links": [
            "device_file_link_id",
            "device_file_link_device_id",
            "device_file_link_file_id",
            "device_file_link_type",
            "device_file_link_datestamp",
            "device_file_link_scratch",
        ],
        "creators": [
            "creator_id",
            "creator",
            "creator_sort",
            "creator_short_name",
            "creator_last_name",
            "creator_phash",
            "creator_legal_name",
            "creator_birth_date",
            "creator_death_date",
            "creator_type",
            "creator_seminal_work",
            "creator_one_person",
            "creator_wikipedia",
            "creator_imdb",
            "creator_link",
            "creator_created_datestamp",
            "creator_datestamp",
            "creator_scratch",
        ],
        "book_cover_links": [
            "book_cover_link_id",
            "book_cover_link_book_id",
            "book_cover_link_cover_id",
            "book_cover_link_priority",
            "book_cover_link_type",
            "book_cover_link_datestamp",
            "book_cover_link_scratch",
        ],
    }

    all_tables_and_column_headings = theo_tables_and_columns

    all_known_tables = sorted(theo_tables_and_columns.keys())

    db_tables = all_known_tables
    db_tables_set = set([_ for _ in db_tables])

    all_sorted_tables = sorted(all_known_tables)

    existing_triggers = [
        "update_callback_on_titles",
        "block_insert_on_database_version_table",
        "block_update_on_database_version_table",
        "block_delete_on_database_version_table",
        "fkc_update_titles_custom_column_1_link_a",
        "fkc_update_titles_custom_column_1_link_b",
        "fkc_insert_titles_custom_column_1_link",
        "fkc_delete_titles_custom_column_1_link",
        "fkc_update_books_custom_column_2_link_a",
        "fkc_update_books_custom_column_2_link_b",
        "fkc_insert_books_custom_column_2_link",
        "fkc_delete_books_custom_column_2_link",
        "fkc_insert_custom_column_3",
        "fkc_update_custom_column_3",
        "fkc_update_books_custom_column_4_link_a",
        "fkc_update_books_custom_column_4_link_b",
        "fkc_insert_books_custom_column_4_link",
        "fkc_delete_books_custom_column_4_link",
        "fkc_insert_custom_column_5",
        "fkc_update_custom_column_5",
        "fkc_update_books_custom_column_6_link_a",
        "fkc_update_books_custom_column_6_link_b",
        "fkc_insert_books_custom_column_6_link",
        "fkc_delete_books_custom_column_6_link",
        "fkc_insert_custom_column_7",
        "fkc_update_custom_column_7",
        "fkc_update_books_custom_column_8_link_a",
        "fkc_update_books_custom_column_8_link_b",
        "fkc_insert_books_custom_column_8_link",
        "fkc_delete_books_custom_column_8_link",
        "fkc_insert_custom_column_9",
        "fkc_update_custom_column_9",
        "fkc_insert_custom_column_10",
        "fkc_update_custom_column_10",
        "fkc_insert_custom_column_11",
        "fkc_update_custom_column_11",
        "fkc_update_books_custom_column_12_link_a",
        "fkc_update_books_custom_column_12_link_b",
        "fkc_insert_books_custom_column_12_link",
        "fkc_delete_books_custom_column_12_link",
        "fkc_insert_custom_column_13",
        "fkc_update_custom_column_13",
        "fkc_update_books_custom_column_14_link_a",
        "fkc_update_books_custom_column_14_link_b",
        "fkc_insert_books_custom_column_14_link",
        "fkc_delete_books_custom_column_14_link",
        "fkc_insert_custom_column_15",
        "fkc_update_custom_column_15",
        "fkc_update_books_custom_column_16_link_a",
        "fkc_update_books_custom_column_16_link_b",
        "fkc_insert_books_custom_column_16_link",
        "fkc_delete_books_custom_column_16_link",
        "fkc_insert_custom_column_17",
        "fkc_update_custom_column_17",
        "fkc_update_books_custom_column_18_link_a",
        "fkc_update_books_custom_column_18_link_b",
        "fkc_insert_books_custom_column_18_link",
        "fkc_delete_books_custom_column_18_link",
        "fkc_insert_custom_column_19",
        "fkc_update_custom_column_19",
        "fkc_insert_custom_column_20",
        "fkc_update_custom_column_20",
        "fkc_insert_custom_column_21",
        "fkc_update_custom_column_21",
        "fkc_update_tags_custom_column_22_link_a",
        "fkc_update_tags_custom_column_22_link_b",
        "fkc_insert_tags_custom_column_22_link",
        "fkc_delete_tags_custom_column_22_link",
    ]

    theo_db_main_tables = set(
        [
            "folders",
            "series",
            "covers",
            "books",
            "genres",
            "custom_columns",
            "comments",
            "languages",
            "last_read_positions",
            "subjects",
            "files",
            "publishers",
            "tags",
            "synopses",
            "folder_stores",
            "notes",
            "identifiers",
            "devices",
            "titles",
            "feeds",
            "creators",
        ]
    )

    theo_db_interlink_tables = set(
        [
            "creator_title_links",
            "rating_title_links",
            "comment_title_links",
            "language_title_links",
            "creator_synopsis_links",
            "file_identifier_links",
            "cover_creator_links",
            "synopsis_title_links",
            "note_series_links",
            "publisher_title_links",
            "identifier_title_links",
            "device_note_links",
            "folder_store_note_links",
            "genre_title_links",
            "creator_series_links",
            "series_tag_links",
            "book_folder_links",
            "creator_folder_links",
            "note_title_links",
            "folder_series_links",
            "tag_title_links",
            "series_title_links",
            "comment_creator_links",
            "genre_series_links",
            "subject_title_links",
            "cover_series_links",
            "creator_tag_links",
            "file_folder_links",
            "note_publisher_links",
            "file_publisher_links",
            "file_language_links",
            "comment_series_links",
            "device_file_links",
            "creator_language_links",
            "creator_note_links",
            "series_synopsis_links",
            "book_cover_links",
            "book_file_links",
        ]
    )

    theo_cc_6_values = {
        1: "test cc6 1 - 96ebca6d-fd03-4449-995b-210a0fccf6a3",
        2: "test cc6 2 - fdddde7e-5574-478c-9608-4640e45f3ec6",
        3: "test cc6 3 - 9b9e8537-31cf-4683-af4b-5e2a33b75e8a",
        4: "test cc6 4 - b0cd931d-5325-4331-8d08-c038682eb4c3",
        5: "test cc6 5 - fd5ae8b5-3833-4466-ac34-2efb7dc13bc4",
        6: "test cc6 6 - 68042e03-d2f2-41a0-b08e-645123c12597",
        7: "test cc6 7 - b0cd931d-5325-4331-8d08-c038682eb4c3",
        8: "test cc6 8 - 413455b4-d046-4da7-8761-36b8a88fe088",
        9: "test cc6 9 - f4b6557c-4278-4e02-9d5f-7b2c88daa7e0",
        10: "test cc6 10 - 1d30e9e6-3ed4-4897-93e9-0b2929ff27f7",
        11: "test cc6 11 - 01afd8a1-813e-4c2b-b8a2-b76b1c3067b1",
        12: "test cc6 12 - 55323a3a-bacf-4056-b5f5-e6f540b92d05",
        13: "test cc6 13 - 56f272d2-bd4e-447d-8a3d-171357a5f6e2",
        14: "test cc6 14 - 562c6380-4c1f-413a-8cfa-612c7d9119ab",
        15: "test cc6 15 - 6e2a8e93-b7ad-4673-bc9e-589294004c38",
        16: "test cc6 16 - 4f266348-dde4-486a-b3e0-bee0baed5b02",
        17: "test cc6 17 - 849b8e8d-95a4-4018-9510-45fed629ee65",
        18: "test cc6 18 - 184852b7-f79d-4cb3-acff-4a0597bd2f23",
        19: "test cc6 19 - 60c2ab8f-ced7-4f8d-a977-9f2fb4be941c",
        20: "test cc6 20 - 56f272d2-bd4e-447d-8a3d-171357a5f6e2",
        21: "test cc6 21 - 77211d71-f8a7-411b-ac58-19af6f4ae350",
        22: "test cc6 22 - 4324fdc0-8cb1-4aa7-bb25-1714dd39cdca",
        23: "test cc6 23 - 669ba846-6730-4fc8-9299-eb1a5c3c082c",
        24: "test cc6 24 - 3dd78a6f-ff02-4916-a795-f35b7b86e84c",
        25: "test cc6 25 - 4324fdc0-8cb1-4aa7-bb25-1714dd39cdca",
        26: "test cc6 26 - 4622c89f-0e05-4ef0-9b18-1319209ee674",
        27: "test cc6 27 - f4217e2f-2e03-455d-bfbf-ed5964ae7ac0",
        28: "test cc6 28 - 65851d79-e6d6-4a89-9780-55b118cf0858",
        29: "test cc6 29 - 9b67e869-0ab7-4267-a5d3-3841d8b7145d",
        30: "test cc6 30 - 7d465381-1f61-4501-98a5-b95db064e4dc",
        31: "test cc6 31 - c47407dd-bd9e-478b-adfa-0585e8dee677",
        32: "test cc6 32 - f576fc20-e058-4859-a027-3c586d8e43c2",
        33: "test cc6 33 - 96ebca6d-fd03-4449-995b-210a0fccf6a3",
        34: "test cc6 34 - add9e315-3502-4f4b-95f7-0ad22e5592e4",
        35: "test cc6 35 - d442da62-b938-41e1-a069-0fb8bb85f340",
        36: "test cc6 36 - 44e87e9e-d716-4e10-89ba-db03682f20ed",
        37: "test cc6 37 - 69b09912-0efb-4c72-8914-cbbd2e4a9bdd",
        38: "test cc6 38 - 8cf64bff-18a0-4795-b44a-8ac350c5afa5",
        39: "test cc6 39 - 7f93e2df-1c66-4d29-a36b-3878c650c447",
        40: "test cc6 40 - 94d9c81a-9f6a-4669-9e65-78db57bab3a6",
        41: "test cc6 41 - 8cf64bff-18a0-4795-b44a-8ac350c5afa5",
        42: "test cc6 42 - 55085fbd-0504-4f37-8fc3-3b6f75f03d41",
        43: "test cc6 43 - be054193-535b-4bb9-b6e2-897d7a494156",
        44: "test cc6 44 - 5e3c2ba7-f3f0-46fe-a2b6-9a3162506d70",
        45: "test cc6 45 - d2b9f985-b203-466b-97d2-bde0527d5763",
        46: "test cc6 46 - 96ebca6d-fd03-4449-995b-210a0fccf6a3",
        47: "test cc6 47 - 1c69f042-1254-4c69-b804-c9b03be73ef7",
        48: "test cc6 48 - 4622c89f-0e05-4ef0-9b18-1319209ee674",
        49: "test cc6 49 - 7b3e4793-3302-4af2-bd2d-9d903258d151",
        50: "test cc6 50 - 78affa14-a6cb-4f88-a57e-99cb308f99f1",
        51: "test cc6 51 - 4da1e0c5-813a-4a01-8ef6-721d35650ce7",
        52: "test cc6 52 - 546667c5-de19-4c85-9d79-14ee90d9188a",
        53: "test cc6 53 - 42d53491-dc6c-4e9b-b8c3-d303e16ba806",
        54: "test cc6 54 - 44e87e9e-d716-4e10-89ba-db03682f20ed",
        55: "test cc6 55 - 28ef047e-f466-4721-b71f-dfb858e0b34a",
        56: "test cc6 56 - 8cb78344-d95e-4166-aa5a-5029c68a1f40",
        57: "test cc6 57 - 6e61e176-d873-4bef-a3f5-0eb41e20328d",
        58: "test cc6 58 - 7b3e4793-3302-4af2-bd2d-9d903258d151",
        59: "test cc6 59 - 65851d79-e6d6-4a89-9780-55b118cf0858",
        60: "test cc6 60 - 146ab80f-261f-44b3-a25a-85379e76abe9",
        61: "test cc6 61 - 56f272d2-bd4e-447d-8a3d-171357a5f6e2",
        62: "test cc6 62 - 01627073-b7f5-4602-819a-b85ba07394ee",
        63: "test cc6 63 - 65851d79-e6d6-4a89-9780-55b118cf0858",
        64: "test cc6 64 - 9b67e869-0ab7-4267-a5d3-3841d8b7145d",
        65: "test cc6 65 - 3542b654-e2d8-48a2-aaa3-7882aa50e259",
        66: "test cc6 66 - 585a2004-1ec7-458d-84c6-e84807aba9b2",
        67: "test cc6 67 - e242db80-72b7-41d6-9fa4-d86b61e72318",
        68: "test cc6 68 - 83c6871c-1ac1-4cec-9519-d6c5ad761b3b",
        69: "test cc6 69 - 93acce3a-7b3c-4afb-b717-b63150537fa6",
        70: "test cc6 70 - c6bc06b8-530c-44d0-9acf-a5cc20b3a221",
        71: "test cc6 71 - 546667c5-de19-4c85-9d79-14ee90d9188a",
        72: "test cc6 72 - e58e43b6-1488-4e47-8107-32c37d8f45e9",
        73: "test cc6 73 - 4c16166c-7b4f-4b32-a7c9-f039a9876785",
        74: "test cc6 74 - c5c0e3b8-7f0a-4925-a326-cc5bf2c4ecd6",
        75: "test cc6 75 - 49b21b3f-83fa-4640-af1d-ec8aabf55331",
        76: "test cc6 76 - 60c2ab8f-ced7-4f8d-a977-9f2fb4be941c",
        77: "test cc6 77 - 49458593-07f1-48f6-834b-fbafdfab119d",
        78: "test cc6 78 - 5a232c19-64ad-4ecb-894c-d020cc352438",
        79: "test cc6 79 - 0862542f-22bc-417c-81a7-0053304412e2",
        80: "test cc6 80 - 43e08bcd-9ebc-4c58-b290-aa280c66e3df",
        81: "test cc6 81 - 42d53491-dc6c-4e9b-b8c3-d303e16ba806",
        82: "test cc6 82 - 3939f972-fa38-45e1-9f3f-be69a8618ee2",
        83: "test cc6 83 - aec6fe91-2a11-4608-af38-a01d0e7cab1d",
        84: "test cc6 84 - 849b8e8d-95a4-4018-9510-45fed629ee65",
        85: "test cc6 85 - cdf28d51-749d-4f0f-bff8-2668abd652a1",
        86: "test cc6 86 - 9b67e869-0ab7-4267-a5d3-3841d8b7145d",
        87: "test cc6 87 - 546667c5-de19-4c85-9d79-14ee90d9188a",
        88: "test cc6 88 - 03210848-24c6-42ac-b918-74aba63e40f3",
        89: "test cc6 89 - 090a79e4-b4cf-40fa-9163-36773b820b92",
        90: "test cc6 90 - 813440de-8da1-4b21-a687-407407d0daeb",
        91: "test cc6 91 - d4201a09-0787-459b-9d35-0b8339042264",
        92: "test cc6 92 - f8f24390-b627-423a-97a1-aa980159df44",
        93: "test cc6 93 - 3542b654-e2d8-48a2-aaa3-7882aa50e259",
        94: "test cc6 94 - afaa77d3-ce17-4bc8-806f-4b2f1b278473",
        95: "test cc6 95 - c9e23001-d802-4f9b-91e1-cda7bb685c62",
        96: "test cc6 96 - eda46b9e-b66e-49bd-9458-68e86cc0d3d1",
        97: "test cc6 97 - f4b6557c-4278-4e02-9d5f-7b2c88daa7e0",
        98: "test cc6 98 - 4f266348-dde4-486a-b3e0-bee0baed5b02",
        99: "test cc6 99 - 44e87e9e-d716-4e10-89ba-db03682f20ed",
        100: "test cc6 100 - 67013d5f-d85d-4308-a208-a5162afc51ab",
    }

    theo_cc_6_rows_count = len(theo_cc_6_values)

    theo_cc6_book_col_map = {
        1: 74,
        2: 6,
        4: 72,
        7: 17,
        9: 7,
        10: 21,
        15: 81,
        16: 11,
        17: 29,
        20: 93,
        21: 94,
        23: 27,
        25: 99,
        27: 31,
        29: 93,
        30: 53,
        32: 34,
        33: 17,
        34: 5,
        39: 58,
        40: 11,
        43: 42,
        44: 40,
        51: 31,
        53: 82,
        55: 3,
        56: 95,
        58: 56,
        59: 73,
        60: 73,
        63: 44,
        68: 73,
        69: 40,
        70: 65,
        71: 93,
        74: 68,
        75: 73,
        76: 69,
        77: 62,
        81: 77,
        87: 31,
        88: 28,
        96: 4,
        97: 5,
        98: 69,
        99: 95,
        102: 48,
        107: 47,
        109: 52,
        112: 30,
        113: 95,
        114: 13,
        119: 55,
        120: 6,
        122: 8,
        124: 7,
        125: 84,
        126: 79,
        127: 73,
        128: 1,
        129: 45,
        130: 76,
        131: 10,
        132: 95,
        136: 10,
        137: 57,
        140: 8,
        142: 69,
        143: 76,
        144: 9,
        147: 57,
        149: 79,
        150: 44,
        152: 81,
        153: 85,
        157: 69,
        159: 97,
        160: 72,
        161: 87,
        164: 35,
        168: 39,
        170: 42,
        172: 75,
        175: 91,
        179: 98,
        181: 33,
        184: 53,
        185: 47,
        186: 74,
        187: 19,
        188: 95,
        189: 52,
        190: 21,
        192: 2,
        193: 70,
        194: 21,
        197: 19,
        203: 39,
        205: 53,
        206: 39,
        207: 13,
        208: 78,
        209: 53,
        210: 5,
        211: 8,
        212: 62,
        213: 80,
        214: 48,
        217: 55,
        230: 63,
        232: 63,
        235: 90,
        237: 29,
        240: 65,
        242: 22,
        243: 18,
        244: 80,
        245: 23,
        248: 86,
        250: 68,
        252: 78,
        253: 94,
        254: 37,
        255: 27,
        260: 90,
        264: 75,
        266: 7,
        268: 19,
        270: 62,
        271: 85,
        272: 80,
        273: 4,
        276: 70,
        277: 28,
        278: 59,
        282: 94,
        283: 15,
        293: 20,
        294: 12,
        297: 92,
        298: 54,
        299: 47,
        300: 87,
    }

    test_cc_6_val_1 = theo_cc_6_values[1]
    test_cc_6_val_7 = theo_cc_6_values[7]
    test_cc_6_val_10 = theo_cc_6_values[10]
    test_cc_6_val_12 = theo_cc_6_values[12]
    test_cc_6_val_13 = theo_cc_6_values[13]
    test_cc_6_val_14 = theo_cc_6_values[14]
    test_cc_6_val_15 = theo_cc_6_values[15]
    test_cc_6_val_79 = theo_cc_6_values[79]
    test_cc_6_val_100 = theo_cc_6_values[100]

    theo_book_1_test_cc_6_val = theo_cc_6_values[theo_cc6_book_col_map[1]]
    theo_book_4_test_cc_6_val = theo_cc_6_values[theo_cc6_book_col_map[4]]

    theo_cc_8_values = {
        1: "test cc8 1 - 96ebca6d-fd03-4449-995b-210a0fccf6a3",
        2: "test cc8 2 - fdddde7e-5574-478c-9608-4640e45f3ec6",
        3: "test cc8 3 - 9b9e8537-31cf-4683-af4b-5e2a33b75e8a",
        4: "test cc8 4 - b0cd931d-5325-4331-8d08-c038682eb4c3",
        5: "test cc8 5 - fd5ae8b5-3833-4466-ac34-2efb7dc13bc4",
        6: "test cc8 6 - 68042e03-d2f2-41a0-b08e-645123c12597",
        7: "test cc8 7 - b0cd931d-5325-4331-8d08-c038682eb4c3",
        8: "test cc8 8 - 413455b4-d046-4da7-8761-36b8a88fe088",
        9: "test cc8 9 - f4b6557c-4278-4e02-9d5f-7b2c88daa7e0",
        10: "test cc8 10 - 1d30e9e6-3ed4-4897-93e9-0b2929ff27f7",
        11: "test cc8 11 - 01afd8a1-813e-4c2b-b8a2-b76b1c3067b1",
        12: "test cc8 12 - 55323a3a-bacf-4056-b5f5-e6f540b92d05",
        13: "test cc8 13 - 56f272d2-bd4e-447d-8a3d-171357a5f6e2",
        14: "test cc8 14 - 562c6380-4c1f-413a-8cfa-612c7d9119ab",
        15: "test cc8 15 - 6e2a8e93-b7ad-4673-bc9e-589294004c38",
        16: "test cc8 16 - 4f266348-dde4-486a-b3e0-bee0baed5b02",
        17: "test cc8 17 - 849b8e8d-95a4-4018-9510-45fed629ee65",
        18: "test cc8 18 - 184852b7-f79d-4cb3-acff-4a0597bd2f23",
        19: "test cc8 19 - 60c2ab8f-ced7-4f8d-a977-9f2fb4be941c",
        20: "test cc8 20 - 56f272d2-bd4e-447d-8a3d-171357a5f6e2",
        21: "test cc8 21 - 77211d71-f8a7-411b-ac58-19af6f4ae350",
        22: "test cc8 22 - 4324fdc0-8cb1-4aa7-bb25-1714dd39cdca",
        23: "test cc8 23 - 669ba846-6730-4fc8-9299-eb1a5c3c082c",
        24: "test cc8 24 - 3dd78a6f-ff02-4916-a795-f35b7b86e84c",
        25: "test cc8 25 - 4324fdc0-8cb1-4aa7-bb25-1714dd39cdca",
        26: "test cc8 26 - 4622c89f-0e05-4ef0-9b18-1319209ee674",
        27: "test cc8 27 - f4217e2f-2e03-455d-bfbf-ed5964ae7ac0",
        28: "test cc8 28 - 65851d79-e6d6-4a89-9780-55b118cf0858",
        29: "test cc8 29 - 9b67e869-0ab7-4267-a5d3-3841d8b7145d",
        30: "test cc8 30 - 7d465381-1f61-4501-98a5-b95db064e4dc",
        31: "test cc8 31 - c47407dd-bd9e-478b-adfa-0585e8dee677",
        32: "test cc8 32 - f576fc20-e058-4859-a027-3c586d8e43c2",
        33: "test cc8 33 - 96ebca6d-fd03-4449-995b-210a0fccf6a3",
        34: "test cc8 34 - add9e315-3502-4f4b-95f7-0ad22e5592e4",
        35: "test cc8 35 - d442da62-b938-41e1-a069-0fb8bb85f340",
        36: "test cc8 36 - 44e87e9e-d716-4e10-89ba-db03682f20ed",
        37: "test cc8 37 - 69b09912-0efb-4c72-8914-cbbd2e4a9bdd",
        38: "test cc8 38 - 8cf64bff-18a0-4795-b44a-8ac350c5afa5",
        39: "test cc8 39 - 7f93e2df-1c66-4d29-a36b-3878c650c447",
        40: "test cc8 40 - 94d9c81a-9f6a-4669-9e65-78db57bab3a6",
        41: "test cc8 41 - 8cf64bff-18a0-4795-b44a-8ac350c5afa5",
        42: "test cc8 42 - 55085fbd-0504-4f37-8fc3-3b6f75f03d41",
        43: "test cc8 43 - be054193-535b-4bb9-b6e2-897d7a494156",
        44: "test cc8 44 - 5e3c2ba7-f3f0-46fe-a2b6-9a3162506d70",
        45: "test cc8 45 - d2b9f985-b203-466b-97d2-bde0527d5763",
        46: "test cc8 46 - 96ebca6d-fd03-4449-995b-210a0fccf6a3",
        47: "test cc8 47 - 1c69f042-1254-4c69-b804-c9b03be73ef7",
        48: "test cc8 48 - 4622c89f-0e05-4ef0-9b18-1319209ee674",
        49: "test cc8 49 - 7b3e4793-3302-4af2-bd2d-9d903258d151",
        50: "test cc8 50 - 78affa14-a6cb-4f88-a57e-99cb308f99f1",
        51: "test cc8 51 - 4da1e0c5-813a-4a01-8ef6-721d35650ce7",
        52: "test cc8 52 - 546667c5-de19-4c85-9d79-14ee90d9188a",
        53: "test cc8 53 - 42d53491-dc6c-4e9b-b8c3-d303e16ba806",
        54: "test cc8 54 - 44e87e9e-d716-4e10-89ba-db03682f20ed",
        55: "test cc8 55 - 28ef047e-f466-4721-b71f-dfb858e0b34a",
        56: "test cc8 56 - 8cb78344-d95e-4166-aa5a-5029c68a1f40",
        57: "test cc8 57 - 6e61e176-d873-4bef-a3f5-0eb41e20328d",
        58: "test cc8 58 - 7b3e4793-3302-4af2-bd2d-9d903258d151",
        59: "test cc8 59 - 65851d79-e6d6-4a89-9780-55b118cf0858",
        60: "test cc8 60 - 146ab80f-261f-44b3-a25a-85379e76abe9",
        61: "test cc8 61 - 56f272d2-bd4e-447d-8a3d-171357a5f6e2",
        62: "test cc8 62 - 01627073-b7f5-4602-819a-b85ba07394ee",
        63: "test cc8 63 - 65851d79-e6d6-4a89-9780-55b118cf0858",
        64: "test cc8 64 - 9b67e869-0ab7-4267-a5d3-3841d8b7145d",
        65: "test cc8 65 - 3542b654-e2d8-48a2-aaa3-7882aa50e259",
        66: "test cc8 66 - 585a2004-1ec7-458d-84c6-e84807aba9b2",
        67: "test cc8 67 - e242db80-72b7-41d6-9fa4-d86b61e72318",
        68: "test cc8 68 - 83c6871c-1ac1-4cec-9519-d6c5ad761b3b",
        69: "test cc8 69 - 93acce3a-7b3c-4afb-b717-b63150537fa6",
        70: "test cc8 70 - c6bc06b8-530c-44d0-9acf-a5cc20b3a221",
        71: "test cc8 71 - 546667c5-de19-4c85-9d79-14ee90d9188a",
        72: "test cc8 72 - e58e43b6-1488-4e47-8107-32c37d8f45e9",
        73: "test cc8 73 - 4c16166c-7b4f-4b32-a7c9-f039a9876785",
        74: "test cc8 74 - c5c0e3b8-7f0a-4925-a326-cc5bf2c4ecd6",
        75: "test cc8 75 - 49b21b3f-83fa-4640-af1d-ec8aabf55331",
        76: "test cc8 76 - 60c2ab8f-ced7-4f8d-a977-9f2fb4be941c",
        77: "test cc8 77 - 49458593-07f1-48f6-834b-fbafdfab119d",
        78: "test cc8 78 - 5a232c19-64ad-4ecb-894c-d020cc352438",
        79: "test cc8 79 - 0862542f-22bc-417c-81a7-0053304412e2",
        80: "test cc8 80 - 43e08bcd-9ebc-4c58-b290-aa280c66e3df",
        81: "test cc8 81 - 42d53491-dc6c-4e9b-b8c3-d303e16ba806",
        82: "test cc8 82 - 3939f972-fa38-45e1-9f3f-be69a8618ee2",
        83: "test cc8 83 - aec6fe91-2a11-4608-af38-a01d0e7cab1d",
        84: "test cc8 84 - 849b8e8d-95a4-4018-9510-45fed629ee65",
        85: "test cc8 85 - cdf28d51-749d-4f0f-bff8-2668abd652a1",
        86: "test cc8 86 - 9b67e869-0ab7-4267-a5d3-3841d8b7145d",
        87: "test cc8 87 - 546667c5-de19-4c85-9d79-14ee90d9188a",
        88: "test cc8 88 - 03210848-24c6-42ac-b918-74aba63e40f3",
        89: "test cc8 89 - 090a79e4-b4cf-40fa-9163-36773b820b92",
        90: "test cc8 90 - 813440de-8da1-4b21-a687-407407d0daeb",
        91: "test cc8 91 - d4201a09-0787-459b-9d35-0b8339042264",
        92: "test cc8 92 - f8f24390-b627-423a-97a1-aa980159df44",
        93: "test cc8 93 - 3542b654-e2d8-48a2-aaa3-7882aa50e259",
        94: "test cc8 94 - afaa77d3-ce17-4bc8-806f-4b2f1b278473",
        95: "test cc8 95 - c9e23001-d802-4f9b-91e1-cda7bb685c62",
        96: "test cc8 96 - eda46b9e-b66e-49bd-9458-68e86cc0d3d1",
        97: "test cc8 97 - f4b6557c-4278-4e02-9d5f-7b2c88daa7e0",
        98: "test cc8 98 - 4f266348-dde4-486a-b3e0-bee0baed5b02",
        99: "test cc8 99 - 44e87e9e-d716-4e10-89ba-db03682f20ed",
        100: "test cc8 100 - 67013d5f-d85d-4308-a208-a5162afc51ab",
    }

    theo_cc8_book_col_map = {
        1: 74,
        2: 6,
        4: 72,
        7: 17,
        9: 7,
        10: 21,
        15: 81,
        16: 11,
        17: 29,
        20: 93,
        21: 94,
        23: 27,
        25: 99,
        27: 31,
        29: 93,
        30: 53,
        32: 34,
        33: 17,
        34: 5,
        39: 58,
        40: 11,
        43: 42,
        44: 40,
        51: 31,
        53: 82,
        55: 3,
        56: 95,
        58: 56,
        59: 73,
        60: 73,
        63: 44,
        68: 73,
        69: 40,
        70: 65,
        71: 93,
        74: 68,
        75: 73,
        76: 69,
        77: 62,
        81: 77,
        87: 31,
        88: 28,
        96: 4,
        97: 5,
        98: 69,
        99: 95,
        102: 48,
        107: 47,
        109: 52,
        112: 30,
        113: 95,
        114: 13,
        119: 55,
        120: 6,
        122: 8,
        124: 7,
        125: 84,
        126: 79,
        127: 73,
        128: 1,
        129: 45,
        130: 76,
        131: 10,
        132: 95,
        136: 10,
        137: 57,
        140: 8,
        142: 69,
        143: 76,
        144: 9,
        147: 57,
        149: 79,
        150: 44,
        152: 81,
        153: 85,
        157: 69,
        159: 97,
        160: 72,
        161: 87,
        164: 35,
        168: 39,
        170: 42,
        172: 75,
        175: 91,
        179: 98,
        181: 33,
        184: 53,
        185: 47,
        186: 74,
        187: 19,
        188: 95,
        189: 52,
        190: 21,
        192: 2,
        193: 70,
        194: 21,
        197: 19,
        203: 39,
        205: 53,
        206: 39,
        207: 13,
        208: 78,
        209: 53,
        210: 5,
        211: 8,
        212: 62,
        213: 80,
        214: 48,
        217: 55,
        230: 63,
        232: 63,
        235: 90,
        237: 29,
        240: 65,
        242: 22,
        243: 18,
        244: 80,
        245: 23,
        248: 86,
        250: 68,
        252: 78,
        253: 94,
        254: 37,
        255: 27,
        260: 90,
        264: 75,
        266: 7,
        268: 19,
        270: 62,
        271: 85,
        272: 80,
        273: 4,
        276: 70,
        277: 28,
        278: 59,
        282: 94,
        283: 15,
        293: 20,
        294: 12,
        297: 92,
        298: 54,
        299: 47,
        300: 87,
    }

    theo_book_1_test_cc_8_val = theo_cc_8_values[theo_cc8_book_col_map[1]]
    theo_book_4_test_cc_8_val = theo_cc_8_values[theo_cc8_book_col_map[4]]

    theo_cc_8_rows_count = len(theo_cc_8_values)

    test_cc_8_val_1 = theo_cc_8_values[1]
    test_cc_8_val_7 = theo_cc_8_values[7]
    test_cc_8_val_10 = theo_cc_8_values[10]
    test_cc_8_val_12 = theo_cc_8_values[12]
    test_cc_8_val_13 = theo_cc_8_values[13]
    test_cc_8_val_14 = theo_cc_8_values[14]
    test_cc_8_val_15 = theo_cc_8_values[15]
    test_cc_8_val_79 = theo_cc_8_values[79]
    test_cc_8_val_100 = theo_cc_8_values[100]

    all_known_tables = sorted(theo_tables_and_columns.keys())

    db_tables = all_known_tables

    from collections import OrderedDict

    theo_custom_columns = {
        "books_custom_column_12_link",
        "books_custom_column_14_link",
        "books_custom_column_16_link",
        "books_custom_column_18_link",
        "books_custom_column_2_link",
        "books_custom_column_4_link",
        "books_custom_column_6_link",
        "books_custom_column_8_link",
        "custom_column_1",
        "custom_column_10",
        "custom_column_11",
        "custom_column_12",
        "custom_column_13",
        "custom_column_14",
        "custom_column_15",
        "custom_column_16",
        "custom_column_17",
        "custom_column_18",
        "custom_column_19",
        "custom_column_2",
        "custom_column_20",
        "custom_column_21",
        "custom_column_22",
        "custom_column_3",
        "custom_column_4",
        "custom_column_5",
        "custom_column_6",
        "custom_column_7",
        "custom_column_8",
        "custom_column_9",
        "tags_custom_column_22_link",
        "titles_custom_column_1_link",
    }

    # Todo: This does not, but needs to, include tags_custom_column_22_link and titles_custom_column_1_link
    theo_cc_columns_map = OrderedDict(
        [
            (
                "books_custom_column_12_link",
                [
                    "books_custom_column_12_link_id",
                    "books_custom_column_12_link_book",
                    "books_custom_column_12_link_value",
                ],
            ),
            (
                "books_custom_column_14_link",
                [
                    "books_custom_column_14_link_id",
                    "books_custom_column_14_link_book",
                    "books_custom_column_14_link_value",
                ],
            ),
            (
                "books_custom_column_16_link",
                [
                    "books_custom_column_16_link_id",
                    "books_custom_column_16_link_book",
                    "books_custom_column_16_link_value",
                    "books_custom_column_16_link_extra",
                ],
            ),
            (
                "books_custom_column_18_link",
                [
                    "books_custom_column_18_link_id",
                    "books_custom_column_18_link_book",
                    "books_custom_column_18_link_value",
                ],
            ),
            (
                "books_custom_column_2_link",
                [
                    "books_custom_column_2_link_id",
                    "books_custom_column_2_link_book",
                    "books_custom_column_2_link_value",
                ],
            ),
            (
                "books_custom_column_4_link",
                [
                    "books_custom_column_4_link_id",
                    "books_custom_column_4_link_book",
                    "books_custom_column_4_link_value",
                ],
            ),
            (
                "books_custom_column_6_link",
                [
                    "books_custom_column_6_link_id",
                    "books_custom_column_6_link_book",
                    "books_custom_column_6_link_value",
                    "books_custom_column_6_link_extra",
                ],
            ),
            (
                "books_custom_column_8_link",
                [
                    "books_custom_column_8_link_id",
                    "books_custom_column_8_link_book",
                    "books_custom_column_8_link_value",
                ],
            ),
            ("custom_column_1", ["custom_column_1_id", "custom_column_1_value"]),
            (
                "custom_column_10",
                [
                    "custom_column_10_id",
                    "custom_column_10_book",
                    "custom_column_10_value",
                ],
            ),
            (
                "custom_column_11",
                [
                    "custom_column_11_id",
                    "custom_column_11_book",
                    "custom_column_11_value",
                ],
            ),
            ("custom_column_12", ["custom_column_12_id", "custom_column_12_value"]),
            (
                "custom_column_13",
                [
                    "custom_column_13_id",
                    "custom_column_13_book",
                    "custom_column_13_value",
                ],
            ),
            ("custom_column_14", ["custom_column_14_id", "custom_column_14_value"]),
            (
                "custom_column_15",
                [
                    "custom_column_15_id",
                    "custom_column_15_book",
                    "custom_column_15_value",
                ],
            ),
            ("custom_column_16", ["custom_column_16_id", "custom_column_16_value"]),
            (
                "custom_column_17",
                [
                    "custom_column_17_id",
                    "custom_column_17_book",
                    "custom_column_17_value",
                ],
            ),
            ("custom_column_18", ["custom_column_18_id", "custom_column_18_value"]),
            (
                "custom_column_19",
                [
                    "custom_column_19_id",
                    "custom_column_19_book",
                    "custom_column_19_value",
                ],
            ),
            ("custom_column_2", ["custom_column_2_id", "custom_column_2_value"]),
            (
                "custom_column_20",
                [
                    "custom_column_20_id",
                    "custom_column_20_book",
                    "custom_column_20_value",
                ],
            ),
            (
                "custom_column_21",
                [
                    "custom_column_21_id",
                    "custom_column_21_book",
                    "custom_column_21_value",
                ],
            ),
            ("custom_column_22", ["custom_column_22_id", "custom_column_22_value"]),
            (
                "custom_column_3",
                [
                    "custom_column_3_id",
                    "custom_column_3_book",
                    "custom_column_3_value",
                ],
            ),
            ("custom_column_4", ["custom_column_4_id", "custom_column_4_value"]),
            (
                "custom_column_5",
                [
                    "custom_column_5_id",
                    "custom_column_5_book",
                    "custom_column_5_value",
                ],
            ),
            ("custom_column_6", ["custom_column_6_id", "custom_column_6_value"]),
            (
                "custom_column_7",
                [
                    "custom_column_7_id",
                    "custom_column_7_book",
                    "custom_column_7_value",
                ],
            ),
            ("custom_column_8", ["custom_column_8_id", "custom_column_8_value"]),
            (
                "custom_column_9",
                [
                    "custom_column_9_id",
                    "custom_column_9_book",
                    "custom_column_9_value",
                ],
            ),
            (
                "tags_custom_column_22_link",
                [
                    "tags_custom_column_22_link_id",
                    "tags_custom_column_22_link_book",
                    "tags_custom_column_22_link_value",
                ],
            ),
            (
                "titles_custom_column_1_link",
                [
                    "titles_custom_column_1_link_id",
                    "titles_custom_column_1_link_book",
                    "titles_custom_column_1_link_value",
                ],
            ),
        ]
    )

    # Todo: Scrub the datestamp column from this
    # Cannot add the same values multiple times to a text based custom column - text appears to be basically tag like
    # Todo: Would really like the bool values to be integers - or bools on the database
    # Todo: display seems to be fundamentally broken
    # From cc 12 on, all values should be multiple - unless it cannot be - due to the datatype
    cc_data_dict = OrderedDict(
        [
            (
                1,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "do_not_read",
                    "custom_column_id": 1,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "titles__do_not_read",
                    "custom_column_in_table": "titles",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                2,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "rating",
                    "custom_column_name": "books_cc_2_do_not_read_rating_not_multiple",
                    "custom_column_id": 2,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_2_do_not_read_rating_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                3,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "int",
                    "custom_column_name": "books_cc_3_do_not_read_int_not_multiple",
                    "custom_column_id": 3,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_3_do_not_read_int_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                4,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "books_cc_4_do_not_read_text_not_multiple",
                    "custom_column_id": 4,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_4_do_not_read_text_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                5,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "comments",
                    "custom_column_name": "books_cc_5_do_not_read_comments_not_multiple",
                    "custom_column_id": 5,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_5_do_not_read_comments_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                6,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "series",
                    "custom_column_name": "books_cc_6_do_not_read_series_not_multiple",
                    "custom_column_id": 6,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_6_do_not_read_series_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                7,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "composite",
                    "custom_column_name": "books_cc_7_do_not_read_composite_not_multiple",
                    "custom_column_id": 7,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_7_do_not_read_composite_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                8,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "enumeration",
                    "custom_column_name": "books_cc_8_do_not_read_enumeration_not_multiple",
                    "custom_column_id": 8,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_8_do_not_read_enumeration_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                9,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "float",
                    "custom_column_name": "books_cc_9_do_not_read_float_not_multiple",
                    "custom_column_id": 9,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_9_do_not_read_float_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                10,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "datetime",
                    "custom_column_name": "books_cc_10_do_not_read_datetime_not_multiple",
                    "custom_column_id": 10,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_10_do_not_read_datetime_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                11,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "bool",
                    "custom_column_name": "books_cc_11_do_not_read_bool_not_multiple",
                    "custom_column_id": 11,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_11_do_not_read_bool_not_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                12,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "rating",
                    "custom_column_name": "books_cc_12_do_not_read_rating_multiple",
                    "custom_column_id": 12,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_12_do_not_read_rating_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                13,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "int",
                    "custom_column_name": "books_cc_13_do_not_read_int_multiple",
                    "custom_column_id": 13,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_13_do_not_read_int_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                14,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "books_cc_14_do_not_read_text_multiple",
                    "custom_column_id": 14,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_14_do_not_read_text_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            # Todo: There should probably be a link table so that there can be multiple comments to a title?
            (
                15,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "comments",
                    "custom_column_name": "books_cc_15_do_not_read_comments_multiple",
                    "custom_column_id": 15,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_15_do_not_read_comments_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                16,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "series",
                    "custom_column_name": "books_cc_16_do_not_read_series_multiple",
                    "custom_column_id": 16,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_16_do_not_read_series_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                17,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "composite",
                    "custom_column_name": "books_cc_17_do_not_read_composite_multiple",
                    "custom_column_id": 17,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_17_do_not_read_composite_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                18,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "enumeration",
                    "custom_column_name": "books_cc_18_do_not_read_enumeration_multiple",
                    "custom_column_id": 18,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_18_do_not_read_enumeration_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "1",
                    "custom_column_editable": "1",
                },
            ),
            (
                19,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "float",
                    "custom_column_name": "books_cc_19_do_not_read_float_multiple",
                    "custom_column_id": 19,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_19_do_not_read_float_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                20,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "datetime",
                    "custom_column_name": "books_cc_20_do_not_read_datetime_multiple",
                    "custom_column_id": 20,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_20_do_not_read_datetime_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                21,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "bool",
                    "custom_column_name": "books_cc_21_do_not_read_bool_multiple",
                    "custom_column_id": 21,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "0",
                    "custom_column_display": "{}",
                    "custom_column_label": "books__books_cc_21_do_not_read_bool_multiple",
                    "custom_column_in_table": "books",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
            (
                22,
                {
                    "custom_column_scratch": "",
                    "custom_column_db_datatype": None,
                    "custom_column_datatype": "text",
                    "custom_column_name": "really_do_not_read",
                    "custom_column_id": 22,
                    "custom_column_mark_for_delete": 0,
                    "custom_column_normalized": "1",
                    "custom_column_display": "{}",
                    "custom_column_label": "tags__really_do_not_read",
                    "custom_column_in_table": "tags",
                    "custom_column_is_multiple": "0",
                    "custom_column_editable": "1",
                },
            ),
        ]
    )
