"""Canonical public WEMI container implementation surface.

Placement rule:
Core WEMI entity containers, WEMI-attached metadata-family containers, and agent
identity/profile/participation surfaces all live here.

Runtime-installed convenience properties are an accepted temporary ergonomic
layer in some families. They are convenience sugar, not the canonical core API.
"""

from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.work_container import WorkIdentity, WorkIdentities
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.work_metadata_container import WorkMetadata
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.work_metadata_hydrator import WorkMetadataHydrator
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.expression_container import ExpressionIdentity
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.expression_metadata_container import ExpressionMetadata
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.expression_metadata_hydrator import ExpressionMetadataHydrator
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.manifestation_container import ManifestationIdentity
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.manifestation_metadata_container import ManifestationMetadata
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.manifestation_metadata_hydrator import ManifestationMetadataHydrator
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.item_container import ItemIdentity
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.item_metadata_container import ItemMetadata
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.item_metadata_hydrator import ItemMetadataHydrator
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.agent_identity import AgentIdentity
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.agent_profile import AgentProfile, HumanAgentProfile, OrganisationAgentProfile
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.agent_credit_containers import AgentCreditBase, WorkAgentCredit, ExpressionAgentCredit, ManifestationAgentCredit, ItemAgentCredit, RoleCreditsContainer, WorkRoleCreditsContainer, ExpressionRoleCreditsContainer, ManifestationRoleCreditsContainer, ItemRoleCreditsContainer, BaseTargetAgentCreditsContainer, WorkAgentCreditsContainer, ExpressionAgentCreditsContainer, ManifestationAgentCreditsContainer, ItemAgentCreditsContainer
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.agent_participation import AgentProfileSummary, WorkSummary, ExpressionSummary, ManifestationSummary, ItemSummary, AgentParticipationEntry, AgentParticipationsByRole, AgentParticipationSnapshot
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.titles_containers import TitleKind, TitleBase, WorkTitle, ExpressionTitle, ManifestationTitle, ItemTitle, KindTitlesContainer, WorkKindTitlesContainer, ExpressionKindTitlesContainer, ManifestationKindTitlesContainer, ItemKindTitlesContainer, BaseTargetTitlesContainer, WorkTitlesContainer, ExpressionTitlesContainer, ManifestationTitlesContainer, ItemTitlesContainer, ItemWemiTitleSlice
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.notes_containers import NoteKind, NoteFormat, NoteVisibility, NoteBase, WorkNote, ExpressionNote, ManifestationNote, ItemNote, KindNotesContainer, WorkKindNotesContainer, ExpressionKindNotesContainer, ManifestationKindNotesContainer, ItemKindNotesContainer, BaseTargetNotesContainer, WorkNotesContainer, ExpressionNotesContainer, ManifestationNotesContainer, ItemNotesContainer
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.labels_containers import LabelKind, LabelBase, WorkLabel, ExpressionLabel, ManifestationLabel, ItemLabel, KindLabelsContainer, WorkKindLabelsContainer, ExpressionKindLabelsContainer, ManifestationKindLabelsContainer, ItemKindLabelsContainer, BaseTargetLabelsContainer, WorkLabelsContainer, ExpressionLabelsContainer, ManifestationLabelsContainer, ItemLabelsContainer
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.genres_containers import GenreKind, GenreBase, WorkGenre, ExpressionGenre, ManifestationGenre, ItemGenre, GenresContainerBase, WorkGenresContainer, ExpressionGenresContainer, ManifestationGenresContainer, ItemGenresContainer
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.subjects_containers import SubjectKind, SubjectBase, WorkSubject, ExpressionSubject, ManifestationSubject, ItemSubject, KindSubjectsContainer, WorkKindSubjectsContainer, ExpressionKindSubjectsContainer, ManifestationKindSubjectsContainer, ItemKindSubjectsContainer, BaseTargetSubjectsContainer, WorkSubjectsContainer, ExpressionSubjectsContainer, ManifestationSubjectsContainer, ItemSubjectsContainer
from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.identifier_containers import IdentifierStatus, IdentifierBase, WorkIdentifier, ExpressionIdentifier, ManifestationIdentifier, ItemIdentifier, SchemeIdentifiersContainer, WorkSchemeIdentifiersContainer, ExpressionSchemeIdentifiersContainer, ManifestationSchemeIdentifiersContainer, ItemSchemeIdentifiersContainer, BaseTargetIdentifiersContainer, WorkIdentifiersContainer, ExpressionIdentifiersContainer, ManifestationIdentifiersContainer, ItemIdentifiersContainer

from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.languages_containers import LanguageKind, LanguageBase, WorkLanguage, ExpressionLanguage, ManifestationLanguage, ItemLanguage, KindLanguagesContainer, WorkKindLanguagesContainer, ExpressionKindLanguagesContainer, ManifestationKindLanguagesContainer, ItemKindLanguagesContainer, BaseTargetLanguagesContainer, WorkLanguagesContainer, ExpressionLanguagesContainer, ManifestationLanguagesContainer, ItemLanguagesContainer

from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.dates_containers import DateKind, DateBase, WorkDate, ExpressionDate, ManifestationDate, ItemDate, KindDatesContainer, WorkKindDatesContainer, ExpressionKindDatesContainer, ManifestationKindDatesContainer, ItemKindDatesContainer, BaseTargetDatesContainer, WorkDatesContainer, ExpressionDatesContainer, ManifestationDatesContainer, ItemDatesContainer

from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.ratings_containers import RatingKind, RatingBase, WorkRating, ExpressionRating, ManifestationRating, ItemRating, KindRatingsContainer, WorkKindRatingsContainer, ExpressionKindRatingsContainer, ManifestationKindRatingsContainer, ItemKindRatingsContainer, BaseTargetRatingsContainer, WorkRatingsContainer, ExpressionRatingsContainer, ManifestationRatingsContainer, ItemRatingsContainer

from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.series_containers import SeriesKind, SeriesEntryBase, WorkSeriesEntry, ExpressionSeriesEntry, ManifestationSeriesEntry, ItemSeriesEntry, KindSeriesEntriesContainer, WorkKindSeriesEntriesContainer, ExpressionKindSeriesEntriesContainer, ManifestationKindSeriesEntriesContainer, ItemKindSeriesEntriesContainer, BaseTargetSeriesEntriesContainer, WorkSeriesEntriesContainer, ExpressionSeriesEntriesContainer, ManifestationSeriesEntriesContainer, ItemSeriesEntriesContainer

from LiuXin_alpha.metadata.containers.metadata_containers.wemi_containers.resources_containers import ResourceKind, ResourceBase, WorkResource, ExpressionResource, ManifestationResource, ItemResource, KindResourcesContainer, WorkKindResourcesContainer, ExpressionKindResourcesContainer, ManifestationKindResourcesContainer, ItemKindResourcesContainer, BaseTargetResourcesContainer, WorkResourcesContainer, ExpressionResourcesContainer, ManifestationResourcesContainer, ItemResourcesContainer

__all__ = [
    "WorkIdentity",
    "WorkIdentities",
    "WorkMetadata",
    "WorkMetadataHydrator",
    "ExpressionIdentity",
    "ExpressionMetadata",
    "ExpressionMetadataHydrator",
    "ManifestationIdentity",
    "ManifestationMetadata",
    "ManifestationMetadataHydrator",
    "ItemIdentity",
    "ItemMetadata",
    "ItemMetadataHydrator",
    "AgentIdentity",
    "AgentProfile",
    "HumanAgentProfile",
    "OrganisationAgentProfile",
    "AgentCreditBase",
    "WorkAgentCredit",
    "ExpressionAgentCredit",
    "ManifestationAgentCredit",
    "ItemAgentCredit",
    "RoleCreditsContainer",
    "WorkRoleCreditsContainer",
    "ExpressionRoleCreditsContainer",
    "ManifestationRoleCreditsContainer",
    "ItemRoleCreditsContainer",
    "BaseTargetAgentCreditsContainer",
    "WorkAgentCreditsContainer",
    "ExpressionAgentCreditsContainer",
    "ManifestationAgentCreditsContainer",
    "ItemAgentCreditsContainer",
    "AgentProfileSummary",
    "WorkSummary",
    "ExpressionSummary",
    "ManifestationSummary",
    "ItemSummary",
    "AgentParticipationEntry",
    "AgentParticipationsByRole",
    "AgentParticipationSnapshot",
    "TitleKind",
    "TitleBase",
    "WorkTitle",
    "ExpressionTitle",
    "ManifestationTitle",
    "ItemTitle",
    "KindTitlesContainer",
    "WorkKindTitlesContainer",
    "ExpressionKindTitlesContainer",
    "ManifestationKindTitlesContainer",
    "ItemKindTitlesContainer",
    "BaseTargetTitlesContainer",
    "WorkTitlesContainer",
    "ExpressionTitlesContainer",
    "ManifestationTitlesContainer",
    "ItemTitlesContainer",
    "ItemWemiTitleSlice",
    "NoteKind",
    "NoteFormat",
    "NoteVisibility",
    "NoteBase",
    "WorkNote",
    "ExpressionNote",
    "ManifestationNote",
    "ItemNote",
    "KindNotesContainer",
    "WorkKindNotesContainer",
    "ExpressionKindNotesContainer",
    "ManifestationKindNotesContainer",
    "ItemKindNotesContainer",
    "BaseTargetNotesContainer",
    "WorkNotesContainer",
    "ExpressionNotesContainer",
    "ManifestationNotesContainer",
    "ItemNotesContainer",
    "LabelKind",
    "LabelBase",
    "WorkLabel",
    "ExpressionLabel",
    "ManifestationLabel",
    "ItemLabel",
    "KindLabelsContainer",
    "WorkKindLabelsContainer",
    "ExpressionKindLabelsContainer",
    "ManifestationKindLabelsContainer",
    "ItemKindLabelsContainer",
    "BaseTargetLabelsContainer",
    "WorkLabelsContainer",
    "ExpressionLabelsContainer",
    "ManifestationLabelsContainer",
    "ItemLabelsContainer",
    "GenreKind",
    "GenreBase",
    "WorkGenre",
    "ExpressionGenre",
    "ManifestationGenre",
    "ItemGenre",
    "GenresContainerBase",
    "WorkGenresContainer",
    "ExpressionGenresContainer",
    "ManifestationGenresContainer",
    "ItemGenresContainer",
    "SubjectKind",
    "SubjectBase",
    "WorkSubject",
    "ExpressionSubject",
    "ManifestationSubject",
    "ItemSubject",
    "KindSubjectsContainer",
    "WorkKindSubjectsContainer",
    "ExpressionKindSubjectsContainer",
    "ManifestationKindSubjectsContainer",
    "ItemKindSubjectsContainer",
    "BaseTargetSubjectsContainer",
    "WorkSubjectsContainer",
    "ExpressionSubjectsContainer",
    "ManifestationSubjectsContainer",
    "ItemSubjectsContainer",
    "IdentifierStatus",
    "IdentifierBase",
    "WorkIdentifier",
    "ExpressionIdentifier",
    "ManifestationIdentifier",
    "ItemIdentifier",
    "SchemeIdentifiersContainer",
    "WorkSchemeIdentifiersContainer",
    "ExpressionSchemeIdentifiersContainer",
    "ManifestationSchemeIdentifiersContainer",
    "ItemSchemeIdentifiersContainer",
    "BaseTargetIdentifiersContainer",
    "WorkIdentifiersContainer",
    "ExpressionIdentifiersContainer",
    "ManifestationIdentifiersContainer",
    "ItemIdentifiersContainer",
    "LanguageKind",
    "LanguageBase",
    "WorkLanguage",
    "ExpressionLanguage",
    "ManifestationLanguage",
    "ItemLanguage",
    "KindLanguagesContainer",
    "WorkKindLanguagesContainer",
    "ExpressionKindLanguagesContainer",
    "ManifestationKindLanguagesContainer",
    "ItemKindLanguagesContainer",
    "BaseTargetLanguagesContainer",
    "WorkLanguagesContainer",
    "ExpressionLanguagesContainer",
    "ManifestationLanguagesContainer",
    "ItemLanguagesContainer",
    "DateKind",
    "DateBase",
    "WorkDate",
    "ExpressionDate",
    "ManifestationDate",
    "ItemDate",
    "KindDatesContainer",
    "WorkKindDatesContainer",
    "ExpressionKindDatesContainer",
    "ManifestationKindDatesContainer",
    "ItemKindDatesContainer",
    "BaseTargetDatesContainer",
    "WorkDatesContainer",
    "ExpressionDatesContainer",
    "ManifestationDatesContainer",
    "ItemDatesContainer",
    "RatingKind",
    "RatingBase",
    "WorkRating",
    "ExpressionRating",
    "ManifestationRating",
    "ItemRating",
    "KindRatingsContainer",
    "WorkKindRatingsContainer",
    "ExpressionKindRatingsContainer",
    "ManifestationKindRatingsContainer",
    "ItemKindRatingsContainer",
    "BaseTargetRatingsContainer",
    "WorkRatingsContainer",
    "ExpressionRatingsContainer",
    "ManifestationRatingsContainer",
    "ItemRatingsContainer",
    "SeriesKind",
    "SeriesEntryBase",
    "WorkSeriesEntry",
    "ExpressionSeriesEntry",
    "ManifestationSeriesEntry",
    "ItemSeriesEntry",
    "KindSeriesEntriesContainer",
    "WorkKindSeriesEntriesContainer",
    "ExpressionKindSeriesEntriesContainer",
    "ManifestationKindSeriesEntriesContainer",
    "ItemKindSeriesEntriesContainer",
    "BaseTargetSeriesEntriesContainer",
    "WorkSeriesEntriesContainer",
    "ExpressionSeriesEntriesContainer",
    "ManifestationSeriesEntriesContainer",
    "ItemSeriesEntriesContainer",
    "ResourceKind",
    "ResourceBase",
    "WorkResource",
    "ExpressionResource",
    "ManifestationResource",
    "ItemResource",
    "KindResourcesContainer",
    "WorkKindResourcesContainer",
    "ExpressionKindResourcesContainer",
    "ManifestationKindResourcesContainer",
    "ItemKindResourcesContainer",
    "BaseTargetResourcesContainer",
    "WorkResourcesContainer",
    "ExpressionResourcesContainer",
    "ManifestationResourcesContainer",
    "ItemResourcesContainer",
]
