# -*- coding: utf-8 -*-

"""
Write content to ereader pdb file.
"""
from __future__ import annotations

import typing as _typing

import io
import re
import struct
import zlib

try:
    from PIL import Image as _PILImage
except Exception:
    _PILImage = None

from LiuXin_alpha.file_formats.pdb.formatwriter import FormatWriter
from LiuXin_alpha.file_formats.pdb.header import PdbHeaderBuilder
from LiuXin_alpha.file_formats.pml.pmlml import PMLMLizer

from LiuXin_alpha.utils.localization import trans as _

__license__ = "GPL v3"
__copyright__ = "2009, John Schember <john@nachtimwald.com>"
__docformat__ = "restructuredtext en"

IDENTITY = "PNRdPPrs"

# This is an arbitrary number that is small enough to work. The actual maximum
# record size is unknown.
MAX_RECORD_SIZE = 8192


def _to_bytes(value: _typing.Any, encoding: str = "utf-8") -> _typing.Any:
    if value is None:
        return b""
    if isinstance(value, bytes):
        return value
    return str(value).encode(encoding, "replace")


def _thumbnail_resample() -> _typing.Any:
    if _PILImage is None:
        return None
    resampling = getattr(_PILImage, "Resampling", None)
    if resampling is not None and hasattr(resampling, "LANCZOS"):
        return resampling.LANCZOS
    return getattr(_PILImage, "ANTIALIAS", None)


class Writer(FormatWriter):
    def __init__(self: _typing.Self, opts: _typing.Any, log: _typing.Any) -> None:
        self.opts = opts
        self.log = log

    def write_content(self: _typing.Self, oeb_book: _typing.Any, out_stream: _typing.Any, metadata: _typing.Any = None) -> None:
        pmlmlizer = PMLMLizer(self.log)
        pml = str(pmlmlizer.extract_content(oeb_book, self.opts)).encode("cp1252", "replace")

        text, text_sizes = self._text(pml)
        chapter_index = self._index_item(br'(?s)\\C(?P<val>[0-4])="(?P<text>.+?)"', pml)
        chapter_index += self._index_item(br"(?s)\\X(?P<val>[0-4])(?P<text>.+?)\\X[0-4]", pml)
        chapter_index += self._index_item(br"(?s)\\x(?P<text>.+?)\\x", pml)
        link_index = self._index_item(br'(?s)\\Q="(?P<text>.+?)"', pml)
        images = self._images(oeb_book.manifest, pmlmlizer.image_hrefs)
        metadata = [self._metadata(metadata)]
        hr = [self._header_record(len(text), len(chapter_index), len(link_index), len(images))]

        """
        Record order as generated by Dropbook.
            1. eReader Header
            2. Compressed text
            3. Small font page index
            4. Large font page index
            5. Chapter index
            6. Links index
            7. Images
            8. (Extrapolation: there should be one more record type here though yet uncovered what it might be).
            9. Metadata
           10. Sidebar records
           11. Footnote records
           12. Text block size record
           13. "MeTaInFo\x00" word record
        """
        sections = hr + text + chapter_index + link_index + images + metadata + [text_sizes] + [b"MeTaInFo\x00"]

        lengths = [len(item) if item not in images else len(item[0]) + len(item[1]) for item in sections]

        pdb_header_builder = PdbHeaderBuilder(IDENTITY, metadata[0].partition(b"\x00")[0])
        pdb_header_builder.build_header(lengths, out_stream)

        for item in sections:
            if item in images:
                out_stream.write(item[0])
                out_stream.write(item[1])
            else:
                out_stream.write(item)

    def _text(self: _typing.Self, pml: _typing.Any) -> tuple[_typing.Any, ...]:
        pml_pages = []
        text_sizes = b""
        index = 0
        while index < len(pml):
            # Split on a nearby space when possible, otherwise hard-wrap.
            max_end = min(index + MAX_RECORD_SIZE, len(pml))
            split = pml.rfind(b" ", index, max_end)
            if split <= index:
                split = max_end

            chunk = pml[index:split]
            if not chunk:
                split = min(index + 1, len(pml))
                chunk = pml[index:split]

            pml_pages.append(zlib.compress(chunk))
            text_sizes += struct.pack(">H", len(chunk))
            index = split

        return pml_pages, text_sizes

    def _index_item(self: _typing.Self, regex: _typing.Any, pml: _typing.Any) -> _typing.Any:
        index = []
        for mo in re.finditer(regex, pml):
            item = b""
            if "text" in mo.groupdict():
                item += struct.pack(">L", mo.start())
                text = mo.group("text")
                # Strip all PML tags from text
                text = re.sub(br"\\U[0-9a-z]{4}", b"", text)
                text = re.sub(br"\\a\d{3}", b"", text)
                text = re.sub(br"\\.", b"", text)
                # Add spacing to denote heading depth.
                if "val" in mo.groupdict() and mo.group("val") is not None:
                    text = b"%s%s" % (b" " * 4 * int(mo.group("val")), text)
                item += text
                item += b"\x00"
            if item:
                index.append(item)
        return index

    def _images(self: _typing.Self, manifest: _typing.Any, image_hrefs: _typing.Any) -> _typing.Any:
        """
        Image format.

        0-4   : 'PNG '. There must be a space after PNG.
        4-36  : Image name. Must be exactly 32 bytes long. Pad with \x00 for names shorter than 32 bytes
        36-58 : Unknown.
        58-60 : Width.
        60-62 : Height.
        62-...: Raw image data in 8 bit PNG format.
        """
        images = []
        from LiuXin_alpha.file_formats.oeb.base import OEB_RASTER_IMAGES

        if _PILImage is None:
            self.log.warning("Pillow not available; skipping embedded image generation for eReader output.")
            return images

        resample = _thumbnail_resample()
        for item in manifest:
            if item.media_type in OEB_RASTER_IMAGES and item.href in image_hrefs:
                try:
                    im = _PILImage.open(io.BytesIO(item.data)).convert("P")
                    if resample is None:
                        im.thumbnail((300, 300))
                    else:
                        im.thumbnail((300, 300), resample)

                    data = io.BytesIO()
                    im.save(data, "PNG")
                    data = data.getvalue()
                    href = _to_bytes(image_hrefs[item.href], encoding="ascii")

                    header = b"PNG "
                    header += href.ljust(32, b"\x00")[:32]
                    header = header.ljust(58, b"\x00")
                    header += struct.pack(">HH", im.size[0], im.size[1])
                    header = header.ljust(62, b"\x00")

                    if len(data) + len(header) < 65505:
                        images.append((header, data))
                except Exception as e:
                    self.log.error("Error: Could not include file %s because %s." % (item.href, e))

        return images

    def _metadata(self: _typing.Self, metadata: _typing.Any) -> _typing.Any:
        """
        Metadata takes the form:
        title\x00
        author\x00
        copyright\x00
        publisher\x00
        isbn\x00
        :param metadata:
        :return:
        """

        title = _("Unknown")
        author = _("Unknown")
        local_copyright = ""
        publisher = ""
        isbn = ""

        if metadata:
            if len(metadata.title) >= 1:
                title = metadata.title[0].value
            if len(metadata.creator) >= 1:
                from LiuXin_alpha.metadata import authors_to_string

                author = authors_to_string([x.value for x in metadata.creator])
            if len(metadata.rights) >= 1:
                local_copyright = metadata.rights[0].value
            if len(metadata.publisher) >= 1:
                publisher = metadata.publisher[0].value

        return (
            "%s\x00%s\x00%s\x00%s\x00%s\x00" % (title, author, local_copyright, publisher, isbn)
        ).encode("cp1252", "replace")

    def _header_record(self: _typing.Self, text_count: _typing.Any, chapter_count: _typing.Any, link_count: _typing.Any, image_count: _typing.Any) -> _typing.Any:
        """
        text_count = the number of text pages
        image_count = the number of images
        :param text_count:
        :param chapter_count:
        :param link_count:
        :param image_count:
        :return:
        """
        compression = 10  # zlib compression.
        non_text_offset = text_count + 1

        chapter_offset = non_text_offset
        link_offset = chapter_offset + chapter_count

        if image_count > 0:
            image_data_offset = link_offset + link_count
            meta_data_offset = image_data_offset + image_count
            last_data_offset = meta_data_offset + 1
        else:
            meta_data_offset = link_offset + link_count
            last_data_offset = meta_data_offset + 1
            image_data_offset = last_data_offset

        if chapter_count == 0:
            chapter_offset = last_data_offset
        if link_count == 0:
            link_offset = last_data_offset

        record = b""

        record += struct.pack(">H", compression)  # [0:2]    # Compression. Specifies compression and drm.
        #                                                                2 = palmdoc, 10 = zlib. 260 and 272 = DRM
        record += struct.pack(">H", 0)  # [2:4]    # Unknown.
        record += struct.pack(">H", 0)  # [4:6]    # Unknown.
        record += struct.pack(">H", 25152)  # [6:8]    # 25152 is MAGIC. Somehow represents the cp1252
        #                                                                encoding of the text
        record += struct.pack(">H", 0)  # [8:10]   # Number of small font pages. 0 if page index is
        #                                                                not built.
        record += struct.pack(">H", 0)  # [10:12]  # Number of large font pages. 0 if page index is
        #                                                                not built.
        record += struct.pack(">H", non_text_offset)  # [12:14]  # Non-Text record start.
        record += struct.pack(">H", chapter_count)  # [14:16]  # Number of chapter index records.
        record += struct.pack(">H", 0)  # [16:18]  # Number of small font page index records.
        record += struct.pack(">H", 0)  # [18:20]  # Number of large font page index records.
        record += struct.pack(">H", image_count)  # [20:22]  # Number of images.
        record += struct.pack(">H", link_count)  # [22:24]  # Number of links.
        record += struct.pack(">H", 1)  # [24:26]  # 1 if has metadata, 0 if not.
        record += struct.pack(">H", 0)  # [26:28]  # Unknown.
        record += struct.pack(">H", 0)  # [28:30]  # Number of Footnotes.
        record += struct.pack(">H", 0)  # [30:32]  # Number of Sidebars.
        record += struct.pack(">H", chapter_offset)  # [32:34]  # Chapter index offset.
        record += struct.pack(">H", 2560)  # [34:36]  # 2560 is MAGIC.
        record += struct.pack(">H", last_data_offset)  # [36:38]  # Small font page offset. This will be the last
        #                                                                data offset if there are none.
        record += struct.pack(">H", last_data_offset)  # [38:40]  # Large font page offset. This will be the last
        #                                                                data offset if there are none.
        record += struct.pack(">H", image_data_offset)  # [40:42]  # Image offset. This will be the last data
        #                                                                offset if there are none.
        record += struct.pack(">H", link_offset)  # [42:44]  # Links offset. This will be the last data
        #                                                                offset if there are none.
        record += struct.pack(">H", meta_data_offset)  # [44:46]  # Metadata offset. This will be the last data
        #                                                                offset if there are none.
        record += struct.pack(">H", 0)  # [46:48]  # Unknown.
        record += struct.pack(">H", last_data_offset)  # [48:50]  # Footnote offset. This will be the last data
        #                                                                offset if there are none.
        record += struct.pack(">H", last_data_offset)  # [50:52]  # Sidebar offset. This will be the last data
        #                                                                offset if there are none.
        record += struct.pack(">H", last_data_offset)  # [52:54]  # Last data offset.

        for _ in range(54, 132, 2):
            record += struct.pack(">H", 0)  # [54:132]

        return record
