from __future__ import annotations

import os
import threading
from types import SimpleNamespace
import uuid

import pytest

from LiuXin_alpha.databases.database_driver_plugins.PostgreSQL.connection import (
    PostgresConnectionAdapter,
    connect_postgres,
)
from LiuXin_alpha.databases.database_driver_plugins.PostgreSQL.databasedriver import (
    DatabaseDriver,
)
from LiuXin_alpha.databases.driver_wrapper import DriverWrapper
from LiuXin_alpha.databases.macro_types import LinkValue
from LiuXin_alpha.databases.schema_specs import StorageColumnSpec, StorageLinkSpec


def _live_postgres_url() -> str:
    url = os.environ.get("LIUXIN_TEST_POSTGRES_URL", "").strip()
    if not url:
        pytest.skip("LIUXIN_TEST_POSTGRES_URL is not configured.")
    return url


def _admin_connection(metadata: dict[str, object]) -> PostgresConnectionAdapter:
    return PostgresConnectionAdapter(
        connect_postgres(metadata, prompt_for_password=False)
    )


def test_portable_macros_against_live_postgres() -> None:
    """Exercise the shared contract against a disposable PostgreSQL schema."""

    schema = f"liuxin_macro_test_{uuid.uuid4().hex}"
    metadata: dict[str, object] = {
        "postgres_url": _live_postgres_url(),
        "schema": schema,
    }
    driver = None
    wrapper = None
    admin = _admin_connection(metadata)
    try:
        with admin:
            admin.execute(f'CREATE SCHEMA "{schema}"')
    finally:
        admin.close()

    try:
        driver = DatabaseDriver(metadata, set_conn=True)
        wrapper = DriverWrapper(driver)
        db = SimpleNamespace(
            driver=driver,
            driver_wrapper=wrapper,
            lock=threading.RLock(),
        )
        driver.db = db
        driver.macros.db = db
        with driver.conn:
            driver.conn.executescript(
                """
                CREATE TABLE macro_live_left (
                    left_id BIGINT PRIMARY KEY,
                    label TEXT NOT NULL
                );
                CREATE TABLE macro_live_right (
                    right_id BIGINT PRIMARY KEY,
                    label TEXT NOT NULL
                );
                CREATE TABLE macro_live_links (
                    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    left_id BIGINT NOT NULL REFERENCES macro_live_left(left_id),
                    right_id BIGINT NOT NULL REFERENCES macro_live_right(right_id),
                    link_type TEXT,
                    priority INTEGER NOT NULL,
                    note TEXT,
                    UNIQUE (left_id, right_id),
                    UNIQUE (left_id, priority)
                );
                CREATE TABLE tags (
                    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tag TEXT,
                    tag_phash TEXT UNIQUE
                );
                INSERT INTO macro_live_left VALUES (1, 'one'), (2, 'two');
                INSERT INTO macro_live_right VALUES (10, 'ten'), (11, 'eleven'), (12, 'twelve');
                """
            )
        driver._zero_prop_cache()

        spec = StorageLinkSpec(
            primary_table="macro_live_left",
            secondary_table="macro_live_right",
            link_table="macro_live_links",
            primary_id_col="left_id",
            secondary_id_col="right_id",
            primary_link_col="left_id",
            secondary_link_col="right_id",
            type_link_col="link_type",
            priority_link_col="priority",
            typed=True,
            ordered=True,
            extra_link_columns=(
                StorageColumnSpec(
                    name="link_id",
                    ordinal=0,
                    declared_type="bigint",
                    is_primary_key=True,
                ),
                StorageColumnSpec(
                    name="note",
                    ordinal=5,
                    declared_type="text",
                ),
            ),
        )
        macros = driver.macros
        rows = macros.replace_links(
            spec,
            1,
            (
                LinkValue(10, link_type="author", extra={"note": "kept"}),
                LinkValue(11, link_type="editor"),
            ),
        )
        assert [row.priority for row in rows] == [2, 1]
        rows = macros.replace_links(
            spec,
            1,
            (
                LinkValue(11, link_type="editor"),
                LinkValue(10, link_type="author"),
                LinkValue(12, link_type="translator"),
            ),
        )
        assert [row.secondary_id for row in rows] == [11, 10, 12]
        assert next(row for row in rows if row.secondary_id == 10).extra["note"] == "kept"

        unique_groups = {
            frozenset(group)
            for group in driver._get_unique_column_groups("macro_live_links")
        }
        assert frozenset(("left_id", "right_id")) in unique_groups
        assert frozenset(("left_id", "priority")) in unique_groups

        with macros.temporary_value_table(
            (b"one", b"two"),
            declared_type="BLOB",
        ) as temp_table:
            assert driver.conn.execute(
                f'SELECT COUNT(*) FROM pg_temp."{temp_table}"'
            ).fetchone()[0] == 2

        tag_id = macros.ensure_table_value("tags", "tag", "Science Fiction")
        assert macros.ensure_table_value(
            "tags",
            "tag",
            " sciencefiction ",
        ) == tag_id
        assert macros.fingerprint_table("macro_live_links") == (
            macros.fingerprint_table("macro_live_links")
        )
    finally:
        if wrapper is not None:
            wrapper.close()
        if driver is not None:
            driver.close()
        admin = _admin_connection(metadata)
        try:
            with admin:
                admin.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
        finally:
            admin.close()
