"""Additive, idempotent migrations for durable storage-manager metadata."""

from __future__ import annotations

import dataclasses
import json
import time

from collections.abc import Mapping
from typing import Any


STORAGE_SCHEMA_VERSION = 2


@dataclasses.dataclass(slots=True, frozen=True)
class StorageMigrationReport:
    """Observable result of preparing one storage catalogue."""

    schema_version: int = STORAGE_SCHEMA_VERSION
    applied_migrations: tuple[str, ...] = ()
    envelope_rows_upgraded: int = 0


def can_migrate_storage_schema(db: Any) -> bool:
    """Return whether ``db`` exposes the portable transaction boundary."""

    macros = getattr(db, "macros", None)
    return callable(getattr(macros, "transaction", None)) and hasattr(
        db, "driver"
    )


def migrate_storage_schema(db: Any) -> StorageMigrationReport:
    """Apply known additive storage migrations and record their identities.

    This deliberately does not attempt arbitrary catalogue repair. It creates
    only the migration ledger and the pre-journal-to-current ingest journal;
    any other missing required table remains a clear bootstrap error.
    """

    tables_before = set(db.get_tables())
    applied: list[str] = []
    with db.macros.transaction() as connection:
        if "storage_schema_migrations" not in tables_before:
            connection.execute(_migration_ledger_ddl(db))
            applied.append("storage-0001-migration-ledger")
        if "storage_ingest_operations" not in tables_before:
            for statement in _ingest_journal_ddl(db):
                connection.execute(statement)
            applied.append("storage-0002-ingest-journal")

    if applied:
        db.get_tables(force_refresh=True)
        # SQLite's forced schema refresh replaces the driver's introspection
        # connection. Keep the Database compatibility alias on that live
        # connection rather than leaving it pointed at the closed predecessor.
        if hasattr(db, "conn"):
            db.conn = getattr(db.driver, "conn", None)
    for migration_id in (
        "storage-0001-migration-ledger",
        "storage-0002-ingest-journal",
    ):
        _record_migration(
            db,
            migration_id,
            applied=migration_id in applied,
        )
    return StorageMigrationReport(applied_migrations=tuple(applied))


def record_envelope_migration(db: Any, upgraded_rows: int) -> None:
    """Record adoption or application of the current envelope migration."""

    _record_migration(
        db,
        "storage-0003-envelope-v1",
        applied=bool(upgraded_rows),
        details={"rows_upgraded": int(upgraded_rows)},
    )


def _record_migration(
    db: Any,
    migration_id: str,
    *,
    applied: bool,
    details: Mapping[str, Any] | None = None,
) -> None:
    rows = db.macros.get_rows(
        "storage_schema_migrations",
        where={"storage_schema_migration_id": migration_id},
    )
    if rows:
        return
    payload = {"applied_during_bootstrap": bool(applied), **dict(details or {})}
    db.macros.insert_row(
        "storage_schema_migrations",
        {
            "storage_schema_migration_id": migration_id,
            "storage_schema_migration_version": STORAGE_SCHEMA_VERSION,
            "storage_schema_migration_applied_timestamp_ep_k": int(
                time.time() * 1000
            ),
            "storage_schema_migration_details_json": json.dumps(
                payload,
                sort_keys=True,
                separators=(",", ":"),
            ),
        },
        id_column="storage_schema_migration_id",
    )


def _migration_ledger_ddl(db: Any) -> str:
    integer = "BIGINT" if hasattr(db.driver, "schema") else "INTEGER"
    return f"""
        CREATE TABLE IF NOT EXISTS storage_schema_migrations (
          storage_schema_migration_id TEXT PRIMARY KEY,
          storage_schema_migration_version {integer} NOT NULL,
          storage_schema_migration_applied_timestamp_ep_k {integer} NOT NULL,
          storage_schema_migration_details_json TEXT NULL
        )
    """


def _ingest_journal_ddl(db: Any) -> tuple[str, ...]:
    postgres = hasattr(db.driver, "schema")
    integer = "BIGINT" if postgres else "INTEGER"
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if postgres
        else "INTEGER PRIMARY KEY"
    )
    timestamp_default = (
        "(extract(epoch from clock_timestamp()) * 1000)::bigint"
        if postgres
        else "(CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER))"
    )
    return (
        f"""
        CREATE TABLE IF NOT EXISTS storage_ingest_operations (
          storage_ingest_operation_id {identity},
          storage_ingest_operation_uuid TEXT NOT NULL,
          storage_ingest_operation_state TEXT NOT NULL DEFAULT 'started',
          storage_ingest_operation_store_uuid TEXT NULL,
          storage_ingest_operation_storage_key TEXT NULL,
          storage_ingest_operation_digital_asset_id {integer} NULL,
          storage_ingest_operation_asset_replica_id {integer} NULL,
          storage_ingest_operation_last_error TEXT NULL,
          storage_ingest_operation_created_timestamp_ep_k {integer} NOT NULL
            DEFAULT {timestamp_default},
          storage_ingest_operation_modified_timestamp_ep_k {integer} NOT NULL
            DEFAULT {timestamp_default},
          storage_ingest_operation_scratch TEXT NOT NULL,
          CONSTRAINT storage_ingest_operation_state_check CHECK (
            storage_ingest_operation_state IN (
              'started','publishing','published','committed','failed'
            )
          ),
          CONSTRAINT storage_ingest_operation_asset_fk FOREIGN KEY (
            storage_ingest_operation_digital_asset_id
          ) REFERENCES digital_assets (digital_asset_id)
            ON DELETE SET NULL ON UPDATE CASCADE,
          CONSTRAINT storage_ingest_operation_replica_fk FOREIGN KEY (
            storage_ingest_operation_asset_replica_id
          ) REFERENCES asset_replicas (asset_replica_id)
            ON DELETE SET NULL ON UPDATE CASCADE
        )
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_storage_ingest_operations_uuid
        ON storage_ingest_operations (storage_ingest_operation_uuid)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_storage_ingest_operations_state
        ON storage_ingest_operations (storage_ingest_operation_state)
        """,
    )


__all__ = [
    "STORAGE_SCHEMA_VERSION",
    "StorageMigrationReport",
    "can_migrate_storage_schema",
    "migrate_storage_schema",
    "record_envelope_migration",
]
