"""
Provide test postgres live smoke utility behavior.

The module keeps compatibility policy, normalization and resource ownership explicit
for callers.

Example:
    Exercise test postgres live smoke through a consuming regression::

        python -m pytest -q tests/scripts/test_postgres_live_smoke.py
"""
from __future__ import annotations

import json
import os

from scripts import run_postgres_live_smoke as smoke


def test_live_smoke_reports_missing_target_without_connecting(monkeypatch, capsys) -> None:
    """
    Perform the test live smoke reports missing target without connecting operation under explicit file-format and conversion rules.

    Example:
        Exercise test live smoke reports missing target without connecting through a consuming regression::

            python -m pytest -q tests/scripts/test_postgres_live_smoke.py


    :param monkeypatch: Value supplied for monkeypatch under the utility contract.
    :param capsys: Value supplied for capsys under the utility contract.
    :return: None; the operation mutates state, writes output or performs cleanup in
        place.
    """
    monkeypatch.delenv("LIUXIN_POSTGRES_URL", raising=False)
    monkeypatch.delenv("LIUXIN_DATABASE_URL", raising=False)
    monkeypatch.delenv("LIUXIN_POSTGRES_SERVICE", raising=False)
    monkeypatch.delenv("PGSERVICE", raising=False)

    rc = smoke.main(["--no-password-prompt", "--json"])

    assert rc == 2
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    assert payload["url"] == ""
    assert payload["target_kind"] == ""
    assert payload["steps"][0]["name"] == "configured"


def test_live_smoke_loads_export_env_file(monkeypatch, tmp_path) -> None:
    """
    Perform the test live smoke loads export env file operation under explicit file-format and conversion rules.

    Example:
        Exercise test live smoke loads export env file through a consuming regression::

            python -m pytest -q tests/scripts/test_postgres_live_smoke.py


    :param monkeypatch: Value supplied for monkeypatch under the utility contract.
    :param tmp_path: Value supplied for tmp path under the utility contract.
    :return: None; the operation mutates state, writes output or performs cleanup in
        place.
    """
    monkeypatch.delenv("LIUXIN_POSTGRES_URL", raising=False)
    monkeypatch.delenv("LIUXIN_POSTGRES_SERVICE", raising=False)
    monkeypatch.delenv("LIUXIN_POSTGRES_SCHEMA", raising=False)
    env_file = tmp_path / "liuxin-postgres.env"
    env_file.write_text(
        "\n".join(
            [
                "# Generated by LiuXin PostgreSQL CLI.",
                "export LIUXIN_POSTGRES_URL=postgresql://liuxin@example.invalid/library",
                "export LIUXIN_POSTGRES_SCHEMA=liuxin_test",
            ]
        ),
        encoding="utf-8",
    )

    try:
        smoke._load_env_file(env_file)

        assert os.environ["LIUXIN_POSTGRES_URL"] == "postgresql://liuxin@example.invalid/library"
        assert os.environ["LIUXIN_POSTGRES_SCHEMA"] == "liuxin_test"
    finally:
        os.environ.pop("LIUXIN_POSTGRES_URL", None)
        os.environ.pop("LIUXIN_POSTGRES_SCHEMA", None)


def test_live_smoke_loads_service_env_file(monkeypatch, tmp_path) -> None:
    """
    Perform the test live smoke loads service env file operation under explicit file-format and conversion rules.

    Example:
        Exercise test live smoke loads service env file through a consuming regression::

            python -m pytest -q tests/scripts/test_postgres_live_smoke.py


    :param monkeypatch: Value supplied for monkeypatch under the utility contract.
    :param tmp_path: Value supplied for tmp path under the utility contract.
    :return: None; the operation mutates state, writes output or performs cleanup in
        place.
    """
    monkeypatch.delenv("LIUXIN_POSTGRES_URL", raising=False)
    monkeypatch.delenv("LIUXIN_POSTGRES_SERVICE", raising=False)
    monkeypatch.delenv("LIUXIN_POSTGRES_SCHEMA", raising=False)
    env_file = tmp_path / "liuxin-postgres-service.env"
    env_file.write_text(
        "\n".join(
            [
                "# Generated by LiuXin PostgreSQL CLI.",
                "export LIUXIN_POSTGRES_SERVICE=liuxin_runtime",
                "export LIUXIN_POSTGRES_SCHEMA=liuxin_test",
            ]
        ),
        encoding="utf-8",
    )

    try:
        smoke._load_env_file(env_file)

        assert os.environ["LIUXIN_POSTGRES_SERVICE"] == "liuxin_runtime"
        assert os.environ["LIUXIN_POSTGRES_SCHEMA"] == "liuxin_test"
    finally:
        os.environ.pop("LIUXIN_POSTGRES_SERVICE", None)
        os.environ.pop("LIUXIN_POSTGRES_SCHEMA", None)


def test_live_smoke_passes_explicit_password_without_printing_it(monkeypatch, capsys) -> None:
    """
    Perform the test live smoke passes explicit password without printing it operation under explicit file-format and conversion rules.

    Example:
        Exercise test live smoke passes explicit password without printing it through a consuming regression::

            python -m pytest -q tests/scripts/test_postgres_live_smoke.py


    :param monkeypatch: Value supplied for monkeypatch under the utility contract.
    :param capsys: Value supplied for capsys under the utility contract.
    :return: The normalized value, metadata record, path, stream result or collection
        described above.
    """
    calls = []

    def fake_self_test(*args, **kwargs):
        """
        Perform the fake self test operation under explicit file-format and conversion rules.

        Example:
            Exercise test live smoke passes explicit password without printing it.fake self test through a consuming regression::

                python -m pytest -q tests/scripts/test_postgres_live_smoke.py


        :param args: Positional values forwarded to the compatibility implementation.
        :param kwargs: Keyword values forwarded to the compatibility implementation.
        :return: The normalized value, metadata record, path, stream result or collection
            described above.
        """
        calls.append(("self-test", args, kwargs))
        return {
            "backend": "postgresql",
            "url": "postgresql://liuxin@example.invalid/library",
            "target_kind": "url",
            "schema": "liuxin_test",
            "ok": True,
            "checks": [
                {"name": "configured", "ok": True, "message": "PostgreSQL target is configured"},
                {"name": "connection", "ok": True, "message": "connected"},
            ],
        }

    def fake_create_schema(metadata, *, password, prompt_for_password, schema):
        """
        Perform the fake create schema operation under explicit file-format and conversion rules.

        Example:
            Exercise test live smoke passes explicit password without printing it.fake create schema through a consuming regression::

                python -m pytest -q tests/scripts/test_postgres_live_smoke.py


        :param metadata: Value supplied for metadata under the utility contract.
        :param password: Value supplied for password under the utility contract.
        :param prompt_for_password: Value supplied for prompt for password under the utility
            contract.
        :param schema: Value supplied for schema under the utility contract.
        :return: None; the operation mutates state, writes output or performs cleanup in
            place.
        """
        calls.append(("create", metadata, password, prompt_for_password, schema))

    monkeypatch.delenv("LIUXIN_POSTGRES_PASSWORD", raising=False)
    monkeypatch.setattr(smoke, "run_postgres_self_test", fake_self_test)
    monkeypatch.setattr(smoke, "_create_schema", fake_create_schema)

    try:
        rc = smoke.main(
            [
                "--url",
                "postgresql://liuxin@example.invalid/library",
                "--schema",
                "liuxin_test",
                "--password",
                "smoke-secret",
                "--skip-crud",
                "--no-password-prompt",
                "--json",
            ]
        )

        assert rc == 0
        assert os.environ["LIUXIN_POSTGRES_PASSWORD"] == "smoke-secret"
        self_test_calls = [call for call in calls if call[0] == "self-test"]
        assert len(self_test_calls) == 2
        assert all(call[2]["password"] == "smoke-secret" for call in self_test_calls)
        assert ("create", {"postgres_url": "postgresql://liuxin@example.invalid/library", "schema": "liuxin_test"}, "smoke-secret", False, "liuxin_test") in calls
        output = capsys.readouterr().out
        assert "smoke-secret" not in output
    finally:
        os.environ.pop("LIUXIN_POSTGRES_PASSWORD", None)
